### PR TITLE
Enable Mono builds on CI

### PR DESCRIPTION
**Pull request by radical**
Tests on Mono/!windows are failing because `Shouldly`'s `net46` assembly
has pinokes to `kernel32.dll` which, of course, fails on Mac.
It works for netcore builds because it's `netstandard` assembly doesn't
have the pinokes.

### CODE REVIEW

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

**Comment by cdmihai** [comment]
>                             }

I think you need to add a branch here for Mono, to set the target and host.

---
Refers to: netci.groovy:44 in 02d8e9f. [](commit_id = 02d8e9f31c8e40e42371f7b8ec719ecfbb72b6ba, deletion_comment = False)

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

(I apologize to anyone for whom these requests are generating mail!)

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

(rebased on top of image update)

**Pull request merged**
