### PR TITLE
Guard against duplicate keys for 4.0 toolset.

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Hitting this on Unix. Follows the same pattern as the other adds in the method.

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
@ValMenn can you take a look?

**Comment by ValMenn** [comment]
The issue is the 4.0 version mentioned in src\XMakeCommandLine\app.config, which is incorrect. My upcoming PR will remove version 4.0 and 12.0 from the app.config and this fix will not be needed. At least for the normal case. Is there any other reason this might happen?

**Comment by JeremyKuhne** [comment]
I assume this could probably be introduced in other ways (bad reg keys?). If there is a reason we don't want to guard I'm ok with that, but it seems like a good one to have.

**Comment by ValMenn** [comment]
Registry could not cause it. The ***ReadAllToolsets*** method is always called with an empty dictionary of toolsets. It can only be loaded with a 4.0 version from a config file before your code is executed. But bad config could cause the problem, as we see, so....
LGTM

**Pull request merged**
