### PR TITLE
Work around universal string coercion in property functions

### LINKED ISSUE #249: PropertyFunctionGenericListReturn fails in xplat
This test is expected to return the string `"A;B;C;D"` but actually returns `"System.Collections.Generic.List`1[System.String]"`.  Clearly we've changed something to cause a `List<string>` to not get flattened, but it's not immediately obvious where.  I was suspicious of changes from 1da7bfd to `Expander`, but since the test fails on both full-framework and Core, that doesn't appear to be the problem.

### PR DESCRIPTION
**Pull request by rainersigwald**
This fixes #249, at least for unit tests.

@ValMenn does this look ok?  I'm a little concerned about fixing paths at the list-of-paths level, but this does fix all of the unit tests we have.

### CODE REVIEW

**Comment by ValMenn** [comment]
@rainersigwald  There seem to be other issues with the code, but the fix for your particular problem is good. The remaining issues include handling an array of strings (as you mention in your comment) and also fixing up the constant string below:
```C# 
                  if (sourceIndex == 0) 
                  { 
                       return expression; 
                  } 
```

**Comment by rainersigwald** [comment]
@ValMenn Should we merge this but leave the bug open to look at the more detailed problems?

**Comment by ValMenn** [comment]
I vote for that. Since the other problems were there all along, merging this won't make it any worse, only better

**Comment by AndyGerlicher** [comment]
LGTM

**Pull request merged**
