### PR TITLE
Import Directory.Build.targets in Microsoft.Common.CrossTarget.targets

### LINKED ISSUE #1721: Directory.build.targets not imported when cross-targeting
Microsoft.Common.CrossTargeting.targets doesn't import these. As a result properties and tasks defined in Directory.build.props, Directory.build.targets are not available in the outer build.

Repro:

1) Create a .NET Core Library with project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.0;net46</TargetFrameworks>
  </PropertyGroup>
</Project>
```

2) Add Directory.Build.targets next to the .csproj file:

```xml
<Project>  
  <Target Name="MyTarget">
    <Error Text="Boom!"/>
  </Target>
</Project>
```

3) Run
```
> msbuild /t:Restore ClassLibrary.csproj
...
> msbuild /t:MyTarget ClassLibrary.csproj
Project "ClassLibrary.csproj" on node 1 (MyTarget target(s)).
ClassLibrary.csproj : error MSB4057: The target "MyTarget" does not exist in the project.
Done Building Project "ClassLibrary.csproj" (MyTarget target(s)) -- FAILED.
```

If the project targets a single framework like so:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
</Project>
```

The target is invoked as expected:

```
Project "ClassLibrary.csproj" on node 1 (MyTarget target(s)).
Directory.Build.targets(7,5): error : Boom!
```

### PR DESCRIPTION
**Pull request by jeffkl**
I just copied and pasted this from [Microsoft.Common.targets](https://github.com/Microsoft/msbuild/blob/xplat/src/Tasks/Microsoft.Common.targets#L129-L141)

Closes #1721

@AndyGerlicher please bar check

### CODE REVIEW

**Comment by jeffkl** [comment]
FYI @nguerrera

**Comment by jeffkl** [comment]
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

**Comment by jeffkl** [comment]
@dotnet-bot test Windows_NT Build for CoreCLR please

**Comment by rainersigwald** [comment]
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

**Pull request merged**
