### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by gluck**
- many more remain but I focused on the visible ones (e.g. non UT)
- can provide a full listing of the remaining ones (scripted checks)

### CODE REVIEW

**Comment by pborreli** [comment]
nice work, by listing you mean it's a raw text list ? If yes, Ok I can take a look and fix them individually if you do so. If you mean you can provide a PR fixing them all, it's even better, be my guest :smile: you will receive a virtual :chocolate_bar: and :bouquet:

**Comment by dannyvv** [comment]
lgtm: :+1: 
Thanks!

**Comment by AndyGerlicher** [comment]
LGTM, thanks!

**Comment by gluck** [comment]
@pborreli raw (automated) listing is what I have, with few false positives that require manual checking.
I'll see whether I provide you the listing or a clean PR next week.

Thanks !

**Pull request merged**
