### PR TITLE
Protect against VsDevCmd changing the current directory

### PR DESCRIPTION
**Pull request by cdmihai**

### CODE REVIEW

**Comment by cdmihai** [comment]
@dotnet-bot test CI please

**Comment by cdmihai** [comment]
@dotnet-bot test CI please

**Comment by cdmihai** [comment]
@dotnet-bot test CI please

**Comment by dasMulli** [comment]
fwiw vsdevcmd behavior bit me recently as well..
this post helped https://developercommunity.visualstudio.com/content/problem/26780/vsdevcmdbat-changes-the-current-working-directory.html

> 1. If the "VSCMD_START_DIR" is defined in the environment, set the directory to that location.
> 
> 2. If the "%USERPROFILE%\Source", directory exists cd to that directory.
> 
> 3. If neither of the above, leave the current directory unchanged.
> 
> Therefore, in addition to the workaround that you mentioned, the Developer Command Prompt also provides the ability to set the final starting directory (ahead of invoking vsdevcmd.bat) as follows:
> 
> > @REM set the directory to the current directory (or directory of your choice)
> 
> > set "VSCMD_START_DIR=%CD%"
> 
> > "call <vsinstance_path>\Common7\Tools\VsDevCmd.bat"

**Comment by cdmihai** [comment]
@dotnet-bot test ci please

**Comment by cdmihai** [comment]
@dasMulli 

Thanks for the tip!

Though I still find this weird:

```
15:06:23 D:\j\w\innerloop_Win---c3d743df>echo D:\j\w\innerloop_Win---c3d743df   && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"   && echo D:\j\w\innerloop_Win---c3d743df   && dir   && dir build   && dir build\cibuild.cmd   && build\cibuild.cmd
15:06:23 D:\j\w\innerloop_Win---c3d743df 
15:06:23 **********************************************************************
15:06:23 ** Visual Studio 2017 Developer Command Prompt v15.5.4
15:06:23 ** Copyright (c) 2017 Microsoft Corporation
15:06:23 **********************************************************************
15:06:24 D:\j\w\innerloop_Win---c3d743df 
15:06:24  Volume in drive C has no label.
15:06:24  Volume Serial Number is 0AF9-C560
15:06:24 
15:06:24  Directory of C:\Users\dotnet-bot\source
```

**Comment by cdmihai** [comment]
@dasMulli nevermind, I see what's happening. %CD% is expanded in the entire command. I hate string replacement based execution ...

**Comment by rainersigwald** [comment]
@cdmihai don't look in the engine then 😈

**Comment by dasMulli** [comment]
I guess %cd% is evaluated by the outer shell before running the chained commands

**Comment by dasMulli** [comment]
digging out my own scripts: `pushd %cd% && [vsdevcmd] && popd`

**Comment by dasMulli** [comment]
lol. cross-post.
feel you

**Comment by rainersigwald** [comment]
@dasMulli I just set a user env var `VSCMD_START_DIR=S:\msbuild`. Thanks for linking that!

**Comment by cdmihai** [comment]
@dotnet-bot test ci please

**Comment by cdmihai** [comment]
@mmitche Any idea why this has started failing all of the sudden? Did jenkins use to set `VSCMD_START_DIR` but now it doesn't?

**Comment by cdmihai** [comment]
Huh, it's machine dependent:
Worked on  win2016-5cc2e0 (win2016-20180117) https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/innerloop_Windows_NT_Full_prtest/867/console
Did not work on  win2016-61b720 (win2016-20180117) https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/GenPRTest/job/innerloop_Windows_NT_Full/5/console

**Comment by dasMulli** [comment]
Looks like the one has a `C:\Users\dotnet-bot\source` that vsdevcmd then cds into.. (=> %USERPROFILE%\source)

**Comment by 4creators** [comment]
@cdmihai The solution used in this PR may be not work correctly. Behavior of VsDevCmd.bat for VS 15 is that it cleans all directory stack which is created by `pushd`, therefore, `popd` will not restore last pushed directory. Best solution is to use:
```
set VSCMD_START_DIR="%CD%" 
:: Or set VSCMD_START_DIR="%~dp0"
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
```

see https://github.com/dotnet/core-setup/pull/3450#discussion_r152643729

**Pull request merged**
