### PR TITLE
Update feed tasks version

### PR DESCRIPTION
**Pull request by mmitche**
Contains various fixes

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Windows_NT Build for CoreCLR please

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Windows_NT Build for Full please

**Comment by mmitche** [comment]
@AndyGerlicher That's really odd...why is it not finding cibuild.cmd...

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Windows_NT Build for Full please

**Comment by AndyGerlicher** [comment]
Looks like it's not getting the repo at all. Odd.

**Comment by mmitche** [comment]
@AndyGerlicher I almost wonder whether GitHub did something wrong.  Maybe the merge branch had no data in it...

@dotnet-bot test Windows_NT Build for CoreCLR please

**Pull request merged**
