### PR TITLE
Rolling builds for xplat

### PR DESCRIPTION
**Pull request by rainersigwald**
This probably isn't done.  Gotta do a bit of onion-peeling.

### CODE REVIEW

**Comment by rainersigwald** [comment]
Ok, progress.  The builds both succeed, but tests fail.

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
Ok, so with the fix for deploying the test assemblies as necessary + this fix, the builds are succeeding and tests are running (for full framework).

I'd like to merge this, then fix or ignore those tests for this branch to get us to green.  @AndyGerlicher?

**Comment by AndyGerlicher** [comment]
LGTM

**Pull request merged**
