### PR TITLE
Adding an xsd entry for 'Content->CopyToPublishDirectory'

### PR DESCRIPTION
**Pull request by tannergooding**
Resolves https://developercommunity.visualstudio.com/content/problem/27616/missing-intellisense-in-net-core-csproj-file.html

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @dotnet/project-system

**Comment by tannergooding** [comment]
@AndyGerlicher, are you aware if this needs a manual insertion to ensure VS picks up these changes for 15.3?

**Comment by AndyGerlicher** [comment]
It does need manual insertion into VS repo. I was going to wait till we're more sure we have all the changes that will be in 15.3 unless there's any hurry. This isn't the only change in schema though.

**Comment by tannergooding** [comment]
Thanks, and no hurry. Just wanted to know if this was part of an automatic or manual insertion 😄

**Pull request merged**
