### PR TITLE
dir.props: Do not disable debug file generation on Mono

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
LGTM

**Comment by AndyGerlicher** [comment]
Can you move the DebugSymbols property under the Debug-MONO specific property group `<PropertyGroup Condition="'$(Configuration)' == 'Debug-MONO'">`?

We think `UseRoslynCompilers` property is stale and the entire block can be deleted. Can you remove that [block](https://github.com/radical/msbuild/blob/mono-debug/dir.props#L20-L22) please?

**Comment by radical** [comment]
Updated

**Comment by rainersigwald** [comment]
I'm still a bit suspicious about why we're not producing symbols when we're building with CoreCLR/Roslyn. We can fix that later, though. LGTM.

**Pull request merged**
