### PR TITLE
Add netci definition for msbuild project

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
@mmitche Should we also change the CI build definition for our xplat branch?

**Comment by mmitche** [comment]
@rainersigwald The definition is only applied from the master branch currently.  The definition I wrote is building xplat and master (and PRs, which are essentially branch-less)

['*/master', '*/xplat', 'pr'].each { branch ->  
...

You can see your jobs here: http://dotnet-ci.cloudapp.net/job/Microsoft_msbuild/

**Pull request merged**
