### PR TITLE
Change IO calls to IFileSystem / FileUtilities and other improvements

### PR DESCRIPTION
**Pull request by cdmihai**
Based on #3480

Split of this PR from other stuff I am doing, since it is getting fairly large. And apparently it's open season for large sweeping edits :).
Replacing IO operations with IFileSystem seems like the healthy thing to do, as we'll be able to control the implementation for the entire codebase. Also, it will allow us to easily replace these calls with native implementations on Linux as well. Or, for example, eventually, to easily allow API users to define their own file system implementation.

### CODE REVIEW

**Comment by cdmihai** [comment]
No detectable changes. Though in theory, it should be better :)

### DesignTimeBuild Time (ms) (src\msbuild.master vs src\msbuild.mihai)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :white_check_mark: | yes | 40.8702 -> 39.7586 (-2.72%)
DotnetWebProject | :ok_hand: | no | 266.2607 -> 268.1579 (0.713%)
DotnetMvcProject | ::ok_hand: | no | 274.312 -> 270.6447 (-1.337%)
Picasso | :ok_hand: | no | 1674.107 -> 1675.1661 (0.063%)
SmallP2POldCsproj | :white_check_mark: | yes | 69.6042 -> 68.7346 (-1.249%)
SmallP2PNewCsproj | :red_circle: | yes | 723.3369 -> 726.9214 (0.496%)
LargeP2POldCsproj | :white_check_mark: | yes | 12539.3335 -> 12461.4611 (-0.621%)
OrchardCore | :white_check_mark: | yes | 54645.7894 -> 54474.3375 (-0.314%)

### DesignTimeBuild Memory (bytes) (src\msbuild.master vs src\msbuild.mihai)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 3095001 -> 3517375 (13.647%)
DotnetWebProject | ::ok_hand: | no | 14123347 -> 14043626 (-0.564%)
DotnetMvcProject | ::ok_hand: | no | 14292944 -> 14282889 (-0.07%)
Picasso | ::ok_hand: | no | 95062002 -> 94953442 (-0.114%)
SmallP2POldCsproj | :ok_hand: | no | 8609025 -> 8611815 (0.032%)
SmallP2PNewCsproj | :white_check_mark: | yes | 44130064 -> 44017278 (-0.256%)
LargeP2POldCsproj | :white_check_mark: | yes | 482027846 -> 456025004 (-5.394%)
OrchardCore | ::ok_hand: | no | 1376277858 -> 1372802633 (-0.253%)

### SerialEvaluationIsolatedContext Time (ms) (src\msbuild.master vs src\msbuild.mihai)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :white_check_mark: | yes | 36.6698 -> 36.2803 (-1.062%)
DotnetWebProject | ::ok_hand: | no | 57.8005 -> 57.7089 (-0.158%)
DotnetMvcProject | :red_circle: | yes | 63.8383 -> 64.103 (0.415%)
Picasso | :white_check_mark: | yes | 342.0244 -> 341.2468 (-0.227%)
SmallP2POldCsproj | :white_check_mark: | yes | 61.0154 -> 60.6945 (-0.526%)
SmallP2PNewCsproj | :red_circle: | yes | 238.4277 -> 241.1048 (1.123%)
LargeP2POldCsproj | :white_check_mark: | yes | 1038.8327 -> 1027.2773 (-1.112%)
OrchardCore | :ok_hand: | no | 3440.9747 -> 3443.7729 (0.081%)

### SerialEvaluationIsolatedContext Memory (bytes) (src\msbuild.master vs src\msbuild.mihai)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :ok_hand: | no | 5498281 -> 5533989 (0.649%)
DotnetWebProject | :ok_hand: | no | 3985252 -> 3988714 (0.087%)
DotnetMvcProject | ::ok_hand: | no | 4727349 -> 4720196 (-0.151%)
Picasso | :ok_hand: | no | 14558529 -> 14572987 (0.099%)
SmallP2POldCsproj | :white_check_mark: | yes | 3477826 -> 3470022 (-0.224%)
SmallP2PNewCsproj | :white_check_mark: | yes | 8930987 -> 8299915 (-7.066%)
LargeP2POldCsproj | :white_check_mark: | yes | 23558153 -> 21698266 (-7.895%)
OrchardCore | ::ok_hand: | no | 59116858 -> 58801708 (-0.533%)

### SerialEvaluationSharedContextSecondRun Time (ms) (src\msbuild.master vs src\msbuild.mihai)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | ::ok_hand: | no | 31.0048 -> 30.9841 (-0.067%)
DotnetWebProject | :white_check_mark: | yes | 51.479 -> 51.0176 (-0.896%)
DotnetMvcProject | :red_circle: | yes | 50.1954 -> 50.381 (0.37%)
Picasso | :red_circle: | yes | 300.6168 -> 304.7351 (1.37%)
SmallP2POldCsproj | :red_circle: | yes | 58.0666 -> 58.6749 (1.048%)
SmallP2PNewCsproj | :red_circle: | yes | 174.8318 -> 175.1098 (0.159%)
LargeP2POldCsproj | :ok_hand: | no | 921.9842 -> 922.5202 (0.058%)
Generated_100_100_v150 | :white_check_mark: | yes | 1375.9562 -> 1359.4477 (-1.2%)
OrchardCore | :white_check_mark: | yes | 1911.7888 -> 1900.04 (-0.615%)
Roslyn | :white_check_mark: | yes | 3224.7847 -> 3186.5885 (-1.184%)
WebLargeCore | :red_circle: | yes | 2176.6497 -> 2208.3865 (1.458%)

### SerialEvaluationSharedContextSecondRun Memory (bytes) (src\msbuild.master vs src\msbuild.mihai)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :white_check_mark: | yes | 5591379 -> 5588308 (-0.055%)
Picasso | :white_check_mark: | yes | 14785164 -> 14727218 (-0.392%)
SmallP2POldCsproj | :white_check_mark: | yes | 3404007 -> 3391883 (-0.356%)
SmallP2PNewCsproj | :ok_hand: | no | 10410929 -> 10480764 (0.671%)
LargeP2POldCsproj | :red_circle: | yes | 20652802 -> 22425682 (8.584%)
Generated_100_100_v150 | :white_check_mark: | yes | 33703371 -> 33375430 (-0.973%)
OrchardCore | :ok_hand: | no | 54101281 -> 54336600 (0.435%)
Roslyn | :red_circle: | yes | 84790447 -> 85598484 (0.953%)
WebLargeCore | :white_check_mark: | yes | 56983272 -> 55318429 (-2.922%)

### SerialEvaluationSharedContext Time (ms) (src\msbuild.master vs src\msbuild.mihai)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 42.434 -> 42.5155 (0.192%)
DotnetWebProject | :white_check_mark: | yes | 57.0156 -> 56.6971 (-0.559%)
DotnetMvcProject | :red_circle: | yes | 62.4106 -> 62.7315 (0.514%)
Picasso | :red_circle: | yes | 304.9943 -> 309.0209 (1.32%)
SmallP2POldCsproj | :red_circle: | yes | 56.7967 -> 57.3294 (0.938%)
SmallP2PNewCsproj | :red_circle: | yes | 205.5909 -> 206.2933 (0.342%)
LargeP2POldCsproj | :red_circle: | yes | 852.4103 -> 855.1331 (0.319%)
Generated_100_100_v150 | :white_check_mark: | yes | 1452.947 -> 1439.6602 (-0.914%)
OrchardCore | :white_check_mark: | yes | 3286.1205 -> 3268.4676 (-0.537%)
Roslyn | :white_check_mark: | yes | 3804.2252 -> 3775.2482 (-0.762%)
WebLargeCore | :red_circle: | yes | 3519.118 -> 3578.5758 (1.69%)

### SerialEvaluationSharedContext Memory (bytes) (src\msbuild.master vs src\msbuild.mihai)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :white_check_mark: | yes | 3003486 -> 2995893 (-0.253%)
DotnetWebProject | :white_check_mark: | yes | 4977986 -> 4971412 (-0.132%)
DotnetMvcProject | :white_check_mark: | yes | 5678404 -> 5671170 (-0.127%)
Picasso | :white_check_mark: | yes | 10504975 -> 10462724 (-0.402%)
SmallP2POldCsproj | :white_check_mark: | yes | 4367376 -> 4342042 (-0.58%)
SmallP2PNewCsproj | :ok_hand: | no | 7323136 -> 7334123 (0.15%)
LargeP2POldCsproj | ::ok_hand: | no | 21245562 -> 21219167 (-0.124%)
Generated_100_100_v150 | :white_check_mark: | yes | 35524580 -> 35284995 (-0.674%)
OrchardCore | :ok_hand: | no | 59759416 -> 59960716 (0.337%)
Roslyn | :ok_hand: | no | 86790832 -> 87037368 (0.284%)
WebLargeCore | :ok_hand: | no | 60178930 -> 60363373 (0.306%)

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for Full
@dotnet-bot test Windows_NT Build for CoreCLR

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for Full
@dotnet-bot test Windows_NT Build for CoreCLR

**Comment by cdmihai** [comment]
@mmitche Do you why this is happening? 
https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/innerloop_Windows_NT_Full_prtest/731/console
```
13:29:01 error: Failed to delete 'C:\Users\runner\.nuget\packages'.
13:29:01 error: Failed to delete 'C:\Users\runner\.nuget\packages\xunit.runner.console\2.3.1\tools\net452\xunit.abstractions.dll'.
13:29:01 error: Failed to delete 'C:\Users\runner\.nuget\packages\xunit.runner.console\2.3.1\tools\net452\xunit.console.x86.exe'.
13:29:01 error: Failed to delete 'C:\Users\runner\.nuget\packages\xunit.runner.console\2.3.1\tools\net452\xunit.runner.reporters.net452.dll'.
13:29:01 error: Failed to delete 'C:\Users\runner\.nuget\packages\xunit.runner.console\2.3.1\tools\net452\xunit.runner.utility.net452.dll'.
```

**Comment by AndyGerlicher** [comment]
@dotnet-bot test OSX10.13 Build for CoreCLR please

**Pull request merged**
