### PR TITLE
Zap whitespace at end-of-line solution-wide

### PR DESCRIPTION
**Pull request by SamB**
Might as well get this out of the way, so it doesn't clutter up the
diffs for commits that do substantive changes.

### CODE REVIEW

**Comment by rainersigwald** [comment]
I was surprised that CodeFormatter didn't do this but since it's all in line comments I guess I can see why.  Filed https://github.com/dotnet/codeformatter/issues/189 to teach it to do so.

LGTM.

**Comment by AndyGerlicher** [comment]
As much as I like this change, I would like to hold off. 1) It's a lot churn to merge with xplat right now and 2) I'll need to merge this with our internal sources. Unfortunately right now that's a manual process.

When/if CodeFormatter does this, I'm all for it. Or once the CoreCLR work calms down we have more changes like this we'd like to perform (@rainersigwald wanted to remove all unused usings at one point, which would be nice as well). Batching those together might make things easier.

**Comment by SamB** [comment]
@AndyGerlicher: Er, doesn't CodeFormatter only work on C# and VB?  What about all the other files?

**Comment by AndyGerlicher** [comment]
Yeah. It's really only the C# that I would be worried about though. The rest are pretty insignificant in comparison.

**Pull request closed without merging**
