### PR TITLE
Copy Task: implement hardlink support for non-Windows OS

### PR DESCRIPTION
**Pull request by akoeplinger**
Use the link() library function for the xplat MSBuild so creating hardlinks works on other platforms too.

See dotnet/buildtools#197

### CODE REVIEW

**Comment by ValMenn** [comment]
Why not create a MakeHardLink function in src/XMakeTasks/NativeMethods.cs and return the error code from it. You can then have all the system-dependent code in one place.

**Comment by akoeplinger** [comment]
@ValMenn I implemented your suggestion, let me know if there's something else to do.

**Comment by ValMenn** [comment]
LGTM

**Comment by AndyGerlicher** [comment]
Looks good, thanks!

**Pull request merged**
