### PR TITLE
Adding a couple new OptProf tests.

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Comment by livarcocc** [comment]
I can kick off a build in private (and burn the version number) and then kick of a optprof run for that build, just to make sure they run properly before merging...

**Comment by rainersigwald** [comment]
Seems worth doing given how everything always goes wrong in this area.

**Comment by livarcocc** [comment]
Sounds good. Doing it now.

**Comment by rainersigwald** [comment]
Internal official build + profile collection seems to have passed: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=291768&_a=release-environment-logs&environmentId=1319611.

I'm going to merge and try an official build consuming that data.

**Pull request merged**
