### PR TITLE
🐧💥 DO NOT MERGE: investigating Ubuntu build failures

### PR DESCRIPTION
**Pull request by rainersigwald**

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
I feel like having the penguin there makes me more likely to want to merge this.

**Comment by rainersigwald** [comment]
But it's an **exploding** penguin. No one wants that!

**Comment by rainersigwald** [comment]
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

**Comment by rainersigwald** [comment]
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

**Comment by rainersigwald** [comment]
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

**Comment by rainersigwald** [comment]
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

**Comment by rainersigwald** [comment]
Fixed by @mmitche in the CI configuration. Thanks!

**Pull request closed without merging**
