### PR TITLE
Merge master → xplat

### PR DESCRIPTION
**Pull request by rainersigwald**
This one was pretty straightforward, at last!

The .sln file was the only real conflict, and it's already a mess. I'll clean it up in my next PR.

### CODE REVIEW

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by cdmihai** [comment]
>                         batchFile("call \"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" && RebuildWithLocalMSBuild.cmd")

Oops, just realized that this does not do localized builds anymore :(
Should I do another PR to master re-enabling it?

---
Refers to: netci.groovy:32 in d966536. [](commit_id = d966536e272ba149bca91b1a34f79a8b52850b2e, deletion_comment = False)

**Comment by rainersigwald** [comment]
@cdmihai https://github.com/Microsoft/msbuild/blob/759f95cd9acab32f881918181e455f4571fbec73/cibuild.cmd#L5 causes localized builds on master. We need to figure out how to turn them on in xplat though, after my current round of PRs.

**Comment by cdmihai** [comment]
Ah, completely forgot about that :)
I'll respond on the cibuild.cmd branch

---
In reply to: [236677918](https://github.com/Microsoft/msbuild/pull/841#issuecomment-236677918) [](ancestors = 236677918)

**Comment by AndyGerlicher** [comment]
LGTM

**Pull request merged**
