### PR TITLE
use ReferenceCopyLocalPaths to resolve _DeploymentReferencePaths

### PR DESCRIPTION
**Pull request by Jinhuafei**
Fixes Clickonce part in issue #3069.

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
Note: This requires a coordinated change with VS. Targeting P4 insertion next week.

**Comment by xwlantian** [comment]
This change cause the `An attempt was made to load a program with an incorrect format.` build error when generating Clickonce manifest. Because the `ReferenceCopyLocalPaths` includes the unmanaged dlls and `ResolveManifestFiles` task's `ManagedAssemblies` parameter includes the `_DeploymentReferencePaths` 
 which should only include managed dlls. https://github.com/Microsoft/msbuild/blob/d42d3504057ef2b88dd4f68c4bfc5591371bd6fe/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3986

**Comment by xwlantian** [comment]
@Jinhuafei The project getting this error has `Gprc.Core` nuget package which has native dependecies. I think the unmanaged dlls are in the `RelatedFiles` of `CopyLocalFiles` which is generated by `ResolveAssemblyReference`
https://github.com/Microsoft/msbuild/blob/d8d43bca5bfe28e62c22211ddd1c5578cf3e37f8/src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs#L850-L859

**Comment by Jinhuafei** [comment]
@xwlantian I tried Grpc.Core nupkg in a winform app and published it without problem. Can you share your repro steps or msbuild log?

**Comment by xwlantian** [comment]
@Jinhuafei I could repro this issue using VS2017 15.8.1 and `grpc.core` nupkg (using `PackageReference` not `packages.config`), please check the `Enable ClickOnce security settings` in `Security` tab.

**Comment by xwlantian** [comment]
It looks like the unmanaged dlls(`grpc_csharp_ext.x64.dll`, `grpc_csharp_ext.x86.dll`) added by `ResolveNuGetPackageAssets` target.

1>Task "ResolveNuGetPackageAssets" (TaskId:9)
1>  Task Parameter:IncludeFrameworkReferences=True (TaskId:9)
1>  Task Parameter:RuntimeIdentifier=win (TaskId:9)
1>  Task Parameter:ProjectLanguage=C# (TaskId:9)
1>  Task Parameter:ProjectLockFile=C:\Users\*\Documents\Visual Studio 2017\Projects\WindowsFormsApp1\WindowsFormsApp1\obj\project.assets.json (TaskId:9)
1>  Task Parameter:
1>      ContentPreprocessorValues=
1>          rootnamespace
1>                  Value=WindowsFormsApp1
1>          assemblyname
1>                  Value=WindowsFormsApp1
1>          fullpath
1>                  Value=C:\Users\*\Documents\Visual Studio 2017\Projects\WindowsFormsApp1\WindowsFormsApp1
1>          outputfilename
1>                  Value=WindowsFormsApp1.exe
1>          filename
1>                  Value=WindowsFormsApp1.csproj (TaskId:9)
1>  Task Parameter:ContentPreprocessorOutputDirectory=obj\Debug\\NuGet (TaskId:9)
1>  Task Parameter:TargetMonikers=.NETFramework,Version=v4.6.1 (TaskId:9)
1>  Output Item(s): 
1>      ReferenceCopyLocalPaths=
1>          C:\Users\*\.nuget\packages\grpc.core\1.14.1\runtimes\win\native\grpc_csharp_ext.x64.dll
1>                  NuGetIsFrameworkReference=false
1>                  NuGetPackageId=Grpc.Core
1>                  NuGetPackageVersion=1.14.1
1>                  NuGetSourceType=Package
1>                  Private=false
1>          C:\Users\*\.nuget\packages\grpc.core\1.14.1\runtimes\win\native\grpc_csharp_ext.x86.dll
1>                  NuGetIsFrameworkReference=false
1>                  NuGetPackageId=Grpc.Core
1>                  NuGetPackageVersion=1.14.1
1>                  NuGetSourceType=Package
1>                  Private=false
1>          C:\Users\*\.nuget\packages\grpc.core\1.14.1\lib\net45\Grpc.Core.dll
1>                  NuGetIsFrameworkReference=false
1>                  NuGetPackageId=Grpc.Core
1>                  NuGetPackageVersion=1.14.1
1>                  NuGetSourceType=Package
1>                  Private=false
1>          C:\Users\*\.nuget\packages\grpc.core\1.14.1\lib\net45\Grpc.Core.pdb
1>                  NuGetIsFrameworkReference=false
1>                  NuGetPackageId=Grpc.Core
1>                  NuGetPackageVersion=1.14.1
1>                  NuGetSourceType=Package
1>                  OriginalItemSpec=C:\Users\*\.nuget\packages\grpc.core\1.14.1\lib\net45\Grpc.Core.dll
1>                  Private=false
1>          C:\Users\*\.nuget\packages\system.interactive.async\3.1.1\lib\net46\System.Interactive.Async.dll
1>                  NuGetIsFrameworkReference=false
1>                  NuGetPackageId=System.Interactive.Async
1>                  NuGetPackageVersion=3.1.1
1>                  NuGetSourceType=Package
1>                  Private=false (TaskId:9)
1>  Output Item(s): 
1>      _ReferencesFromNuGetPackages=
1>          C:\Users\*\.nuget\packages\grpc.core\1.14.1\lib\net45\Grpc.Core.dll
1>                  NuGetIsFrameworkReference=false
1>                  NuGetPackageId=Grpc.Core
1>                  NuGetPackageVersion=1.14.1
1>                  NuGetSourceType=Package
1>                  Private=false
1>          C:\Users\*\.nuget\packages\system.interactive.async\3.1.1\lib\net46\System.Interactive.Async.dll
1>                  NuGetIsFrameworkReference=false
1>                  NuGetPackageId=System.Interactive.Async
1>                  NuGetPackageVersion=3.1.1
1>                  NuGetSourceType=Package
1>                  Private=false
1>          Microsoft.CSharp
1>                  NuGetIsFrameworkReference=true
1>                  NuGetSourceType=Package
1>          System
1>                  NuGetIsFrameworkReference=true
1>                  NuGetSourceType=Package (TaskId:9)
1>  Output Item(s): ReferencedNuGetPackages=Grpc.Core (TaskId:9)
1>Done executing task "ResolveNuGetPackageAssets". (TaskId:9)

**Comment by Jinhuafei** [comment]
Thanks, I was able to repro the issue with packagereference mode. I need to double check with the folks about whether ReferenceCopyLocalPaths item group should include the native binaries. The behavior is different be package.config and package ref mode.

**Pull request merged**
