### PR TITLE
Switch to branch specific job generation

### PR DESCRIPTION
**Pull request by mmitche**
Changes over to branch specific job generation where the netci.groovy file in each branch is processed to generate jobs for that branch.  This allows drift in process between branches over time.

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by cdmihai** [comment]
@mmitche 
Thanks for the help!

Looks like it does not find the `getFullJobName` overload with isPR.

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Pull request merged**
