### PR TITLE
Update DotnetCli version to 1.0.0-preview3-003686

### PR DESCRIPTION
**Pull request by jeffkl**
This is needed in order to use some new stuff in the CLI

### CODE REVIEW

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

(I checked in changes to master that should capture `init-tools.log` from this run)

**Comment by jeffkl** [comment]
This is failing because `dotnet restore` is restoring stuff under `microsoft.dotnet.buildtools` instead of `Microsoft.DotNet.BuildTools`.  On OS X and Linux, the init-tools.sh then fails because of the casing of the directory 😢

**Comment by jeffkl** [comment]
We should merge the change into xplat right?

**Comment by rainersigwald** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Comment by rainersigwald** [comment]
@dotnet-bot Ubuntu Build for CoreCLR please

**Comment by jeffkl** [comment]
@dotnet-bot test Ubuntu Build for CoreCLR please 
I fixed init-tools.sh

**Comment by jeffkl** [comment]
Well that's interesting, some unit tests failed on OS X.

@dotnet-bot test Ubuntu Build for CoreCLR please

**Comment by jeffkl** [comment]
@dotnet-bot test OSX build for coreclr please

**Pull request merged**
