### PR TITLE
Test diagnosability improvements

### PR DESCRIPTION
**Pull request by rainersigwald**
Some improvements to tests that I made while investigating failures for node reuse.

### CODE REVIEW

**Comment by cdmihai** [comment]
Looks like a good change regardless :)

**Comment by rainersigwald** [comment]
Added a few more diagnosability improvements I added while investigating failures.

**Comment by rainersigwald** [comment]
That's a new one:

```
/Users/dotnet-bot/j/w/Microsoft_msbuild/master/innerloop_OSX10.13_CoreCLR_prtest/artifacts/Debug/bootstrap/netcoreapp2.1/MSBuild/NuGet.targets(104,5): error : The file '/Users/dotnet-bot/j/w/Microsoft_msbuild/master/innerloop_OSX10.13_CoreCLR_prtest/artifacts/2Debug/obj/MSBuild/project.assets.json' already exists. [/Users/dotnet-bot/j/w/Microsoft_msbuild/master/innerloop_OSX10.13_CoreCLR_prtest/src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj]
```

@dotnet-bot test OSX10.13 Build for CoreCLR please

**Comment by rainersigwald** [comment]
I don't think I touched this:

https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/innerloop_Windows_NT_Full_prtest/279/testReport/junit/Microsoft.Build.UnitTests.GetSDKReferenceFiles_Tests/GetSDKReferenceFilesTestFixture/PassReferenceWithNoReferenceDirectory/

@dotnet-bot test Windows_NT Build for Full please

**Pull request merged**
