### PR TITLE
Bump versions to 15.3.*

### PR DESCRIPTION
**Pull request by rainersigwald**
This more closely matches the intention that the current builds are
destined for release with the Visual Studio 15.3 wave. After this, the
(cosmetic) versions will match the logical release. The AssemblyVersion
remains 15.1 for compatibility.

### CODE REVIEW

**Comment by jeffkl** [comment]
Update MSBuildConstants.CurrentAssemblyFileVersion too I think

**Comment by AndyGerlicher** [comment]
This will reset to 15.3.0 right? Should we up the offset to keep what we're at now?

**Comment by rainersigwald** [comment]
I went back and forth on that, but I think it is more descriptive that way.

**Comment by rainersigwald** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Pull request merged**
