### PR TITLE
Load all projects as read-only in MSBuild.exe

### LINKED ISSUE #2576: Don't read comments when reading imports
In a trace of an evaluation of a large solution from a major partner, 1% of allocations during the evaluation is spent reading comments (their GC time is 25%, so we need to reduce allocations). For project file persistence we want to make sure to roundtrip comments - but for targets do we need them? 

image

### PR DESCRIPTION
**Pull request by jeffkl**
Uses `XmlReaderSettings` to ignore comments and whitespace for all projects.  At the moment we read comments but then report the content as just `String.Empty`.  The `XmlReader` still allocates a string for us which we immediately throw away.

This change adds a setting to `ProjectCollection` so that all projects loaded in the collection are treated as read-only.  For command-line builds, a ProjectCollection is created for the build episode.  End-users can create their own ProjectCollection with the setting as well.

Fixes #2576

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
### DesignTimeBuild Time (ms) (src\msbuild vs src\msbuild.jeff)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :white_check_mark: | yes | 36.5845 -> 36.4065 (-0.487%)
DotnetWebProject | :ok_hand: | no | 230.1308 -> 231.1049 (0.423%)
DotnetMvcProject | :ok_hand: | no | 232.7922 -> 233.5048 (0.306%)
Picasso | :white_check_mark: | yes | 1545.722 -> 1543.1251 (-0.168%)
SmallP2POldCsproj | :white_check_mark: | yes | 68.8146 -> 68.1377 (-0.984%)
SmallP2PNewCsproj | :red_circle: | yes | 649.2819 -> 650.7277 (0.223%)
LargeP2POldCsproj | :red_circle: | yes | 11258.4129 -> 11330.2536 (0.638%)
OrchardCore | :white_check_mark: | yes | 48644.5814 -> 48285.1216 (-0.739%)

### DesignTimeBuild Memory (bytes) (src\msbuild vs src\msbuild.jeff)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 6259065 -> 6266238 (0.115%)
DotnetWebProject | ::ok_hand: | no | 22933230 -> 21877163 (-4.605%)
DotnetMvcProject | ::ok_hand: | no | 22259073 -> 21340516 (-4.127%)
Picasso | :red_circle: | yes | 182421621 -> 186957517 (2.486%)
SmallP2POldCsproj | :red_circle: | yes | 8547276 -> 8570039 (0.266%)
SmallP2PNewCsproj | ::ok_hand: | no | 92122514 -> 90522671 (-1.737%)
LargeP2POldCsproj | :white_check_mark: | yes | 1082715524 -> 1040219870 (-3.925%)
OrchardCore | :white_check_mark: | yes | 2777824956 -> 2728487523 (-1.776%)

### SerialEvaluationIsolatedContext Time (ms) (src\msbuild vs src\msbuild.jeff)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :white_check_mark: | yes | 34.5251 -> 34.4331 (-0.266%)
DotnetWebProject | :ok_hand: | no | 48.1357 -> 48.2005 (0.135%)
DotnetMvcProject | :red_circle: | yes | 53.8864 -> 54.0912 (0.38%)
Picasso | :red_circle: | yes | 297.7509 -> 300.4826 (0.917%)
SmallP2POldCsproj | :white_check_mark: | yes | 51.6291 -> 51.2593 (-0.716%)
SmallP2PNewCsproj | :ok_hand: | no | 204.3136 -> 204.8061 (0.241%)
LargeP2POldCsproj | :red_circle: | yes | 894.2667 -> 902.272 (0.895%)
OrchardCore | :white_check_mark: | yes | 3204.287 -> 3190.9535 (-0.416%)

### SerialEvaluationIsolatedContext Memory (bytes) (src\msbuild vs src\msbuild.jeff)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :ok_hand: | no | 5677492 -> 5678814 (0.023%)
DotnetWebProject | :red_circle: | yes | 7652735 -> 7659871 (0.093%)
DotnetMvcProject | :red_circle: | yes | 8272610 -> 8281721 (0.11%)
Picasso | :white_check_mark: | yes | 15995961 -> 12701413 (-20.596%)
SmallP2POldCsproj | :red_circle: | yes | 6977223 -> 6996985 (0.283%)
SmallP2PNewCsproj | :white_check_mark: | yes | 15209780 -> 13595063 (-10.616%)
LargeP2POldCsproj | ::ok_hand: | no | 40159506 -> 38559547 (-3.984%)
OrchardCore | :ok_hand: | no | 64396353 -> 68123853 (5.788%)

### SerialEvaluationSharedContextSecondRun Time (ms) (src\msbuild vs src\msbuild.jeff)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :ok_hand: | no | 29.403 -> 29.447 (0.15%)
DotnetWebProject | :white_check_mark: | yes | 37.0096 -> 36.7551 (-0.688%)
DotnetMvcProject | :white_check_mark: | yes | 39.4894 -> 39.0219 (-1.184%)
Picasso | ::ok_hand: | no | 235.6743 -> 235.4419 (-0.099%)
SmallP2POldCsproj | :red_circle: | yes | 41.0387 -> 41.318 (0.681%)
SmallP2PNewCsproj | :white_check_mark: | yes | 130.2512 -> 129.9751 (-0.212%)
LargeP2POldCsproj | :red_circle: | yes | 654.5544 -> 660.1758 (0.859%)
Generated_100_100_v150 | :ok_hand: | no | 1127.381 -> 1128.3378 (0.085%)
OrchardCore | ::ok_hand: | no | 1564.3817 -> 1560.5502 (-0.245%)
Roslyn | :red_circle: | yes | 2603.2246 -> 2614.561 (0.435%)
WebLargeCore | ::ok_hand: | no | 1798.2319 -> 1792.2476 (-0.333%)

### SerialEvaluationSharedContextSecondRun Memory (bytes) (src\msbuild vs src\msbuild.jeff)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 5542801 -> 5543102 (0.005%)
DotnetWebProject | :red_circle: | yes | 6858968 -> 6865315 (0.093%)
DotnetMvcProject | :red_circle: | yes | 7285803 -> 7292626 (0.094%)
Picasso | :red_circle: | yes | 10854655 -> 11199302 (3.175%)
SmallP2POldCsproj | :red_circle: | yes | 6903170 -> 6944082 (0.593%)
SmallP2PNewCsproj | :red_circle: | yes | 22974307 -> 23072873 (0.429%)
LargeP2POldCsproj | :red_circle: | yes | 35834564 -> 36481812 (1.806%)
Generated_100_100_v150 | :red_circle: | yes | 44950579 -> 46310017 (3.024%)
OrchardCore | :red_circle: | yes | 56299039 -> 58860930 (4.551%)
Roslyn | :red_circle: | yes | 82958377 -> 86914021 (4.768%)
WebLargeCore | :red_circle: | yes | 69975831 -> 71927428 (2.789%)

### SerialEvaluationSharedContext Time (ms) (src\msbuild vs src\msbuild.jeff)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :white_check_mark: | yes | 33.8715 -> 33.7459 (-0.371%)
DotnetWebProject | :white_check_mark: | yes | 47.5793 -> 47.3493 (-0.483%)
DotnetMvcProject | :white_check_mark: | yes | 53.551 -> 53.14 (-0.767%)
Picasso | :ok_hand: | no | 249.5883 -> 250.4032 (0.326%)
SmallP2POldCsproj | :red_circle: | yes | 44.904 -> 45.0546 (0.335%)
SmallP2PNewCsproj | :ok_hand: | no | 166.6854 -> 167.3034 (0.371%)
LargeP2POldCsproj | :red_circle: | yes | 707.9823 -> 711.6937 (0.524%)
Generated_100_100_v150 | :ok_hand: | no | 1145.0907 -> 1145.3251 (0.02%)
OrchardCore | :ok_hand: | no | 2104.8438 -> 2107.7857 (0.14%)
Roslyn | :red_circle: | yes | 3130.5376 -> 3142.6218 (0.386%)
WebLargeCore | ::ok_hand: | no | 2254.0711 -> 2253.3607 (-0.032%)

### SerialEvaluationSharedContext Memory (bytes) (src\msbuild vs src\msbuild.jeff)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 5747665 -> 5747912 (0.004%)
DotnetWebProject | :red_circle: | yes | 7708725 -> 7717609 (0.115%)
DotnetMvcProject | :red_circle: | yes | 8318532 -> 8326714 (0.098%)
Picasso | :white_check_mark: | yes | 12839376 -> 11139145 (-13.242%)
SmallP2POldCsproj | :red_circle: | yes | 6968340 -> 7007770 (0.566%)
SmallP2PNewCsproj | :ok_hand: | no | 14677275 -> 14927120 (1.702%)
LargeP2POldCsproj | ::ok_hand: | no | 37030682 -> 36739613 (-0.786%)
Generated_100_100_v150 | :red_circle: | yes | 45772666 -> 46962536 (2.6%)
OrchardCore | :ok_hand: | no | 64001299 -> 66724946 (4.256%)
Roslyn | ::ok_hand: | no | 85688144 -> 85666085 (-0.026%)
WebLargeCore | :ok_hand: | no | 69069345 -> 70129820 (1.535%)

**Comment by jeffkl** [comment]
@AndyGerlicher do the perf numbers indicate if this change is worth it?  I can't decipher them...

**Comment by jeffkl** [comment]
@davkean does this look like it'll resolve #2576?  Our perf numbers are inconclusive

**Comment by davkean** [comment]
Really hard to tell - do you trust those numbers at all? It shows a large reduction in design-time build memory, but then regresses SerialEvaluationSharedContextSecondRun memory whatever that's doing.

**Pull request merged**
