### PR TITLE
add AppVeyor build, compile and run unit tests

### PR DESCRIPTION
**Pull request by ctaggart**
This allows this project and forks of this project to easily build and run all the unit tests on AppVeyor. Example test output:
https://ci.appveyor.com/project/ctaggart/msbuild/build/12/tests

### CODE REVIEW

**Comment by mmitche** [comment]
@ctaggart Is there a reason that the current Jenkins CI for PR/push testing is insufficient?

**Comment by ctaggart** [comment]
Yes. It doesn't build my fork or other contributes forks as we develop unless we do a pull request. Jenkins is just for Microsoft/msbuild and PRs to it. The AppVeyor script would allow any of the 323 forks to easily have their own build service. Many projects have multiple build services running. It is common to see Jenkins, AppVeyor and Travis all connected.

**Comment by AndyGerlicher** [comment]
We're using Jenkins for the CI, so we don't want to have this in our repo (if it ever breaks, we wouldn't know). Please keep this in your fork.

**Comment by ctaggart** [comment]
@AndyGerlicher You would know if it breaks. Every PR would be built by both. Several Microsoft projects are using it.

Does the Jenkins CI server run the unit tests? The AppVeyor build I made does run them and I've got three failing. I wanted to see if they were passing in Jenkins.

image
You can see the output for each test in AppVeyor by clicking on the test.
https://ci.appveyor.com/project/ctaggart/msbuild/build/15/tests

**Comment by mmitche** [comment]
Hmm, Jenkins should be running the unit tests, but it doesn't appear to be.  Are they run through build.cmd @AndyGerlicher (that's the ideal situation).  Otherwise I can set it up search and run them through the plugins.

**Pull request closed without merging**
