### PR TITLE
build.sh: Check for packages count if $pack or $dotnetBuildFromSource

### PR DESCRIPTION
**Pull request by radical**
.. as that directory is not used for other builds.

### CODE REVIEW

**Comment by radical** [comment]
@dotnet-bot test mono

**Comment by radical** [comment]
@dotnet-bot test mono

**Comment by rainersigwald** [comment]
hmm, win/core timed out? https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/innerloop_Windows_NT_CoreCLR_prtest/419/console

@dotnet-bot test Windows_NT Build for CoreCLR please

**Comment by rainersigwald** [comment]
I think if we take #3275 first we can get green Mono non-Test jobs for this . . .

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

(Mono jobs might pass?)

**Comment by radical** [comment]
`Mono` jobs don't have `-hostType mono`. bug in `netci.groovy`! We should get the same error for `Mono` and `MonoTest` jobs!

**Comment by rainersigwald** [comment]
lol, but they _pass_. Can't change it now!

**Pull request merged**
