### PR TITLE
Changes that allow MSBuild to run on Linux

### PR DESCRIPTION
**Pull request by ValMenn**
These changes resolve a number of issues MSBuild encounters on startup. All of them are pretty minor.
Note, that when the compilers are copied into the output directory, the System.Collections.Immutable.dll and System.Reflection.Metadata.dll may get overwritten with earlier versions (depends on file dates). This is a separate issue, but if correct versions are present, the result can build a simple project.

### CODE REVIEW

**Comment by ValMenn** [comment]
I think we should be able to only leave the home directory, in which case we'll have a single 'GetHome' function. This requires some understanding of how we are going to deal with toolsets and frameworks. So this is a quick workaround for the problem that should carry us until then.

**Comment by rainersigwald** [comment]
Works for me.  LGTM.

**Comment by AndyGerlicher** [comment]
LGTM assuming that the CI build passes.

**Comment by rainersigwald** [comment]
I don't know what's up with that hang/termination in tests.  Let's try again, shall we?

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by ValMenn** [comment]
System.Threading.ThreadPool was not copied to the output directory on "clean" systems. Some newer assembly versions must have removed the dependency, but on a system where it succeeded previously, the dependency was "remembered" and build worked. On a fresh system it failed. I added the assembly to the targets/runtime.project.json

**Pull request merged**
