### PR TITLE
Port traversal targets for cross-targeting to xplat branch 

### PR DESCRIPTION
**Pull request by nguerrera**
@cdmihai @jeffkl @AndyGerlicher @rainersigwald

### CODE REVIEW

**Comment by rainersigwald** [comment]
@nguerrera is it possible to merge instead of cherry-picking? That should reduce headache later.

**Comment by nguerrera** [comment]
@rainersigwald I was following https://github.com/Microsoft/msbuild/pull/1018#issuecomment-247100883

Also, if I merge, it will bring in all of master, do you want a full FI? I had made my commits against the merge-base of master and xplat, but the squash-merge requested rebased it to the HEAD of master.

**Comment by nguerrera** [comment]
Any idea what the failure to restore on OS X is about?

**Comment by nguerrera** [comment]
test OSX Build for CoreCLR please

**Comment by jeffkl** [comment]
@nguerrera I was able to get things to pass by rebasing onto xplat and force pushing.  Not sure why it worked...

https://github.com/Microsoft/msbuild/pull/1022

**Comment by nguerrera** [comment]
@jeffkl These commits are already on top of xplat latest so rebase would be a no-op.

**Comment by nguerrera** [comment]
Is anyone looking in to the root cause here? Anything else I can do to get this in?

**Comment by rainersigwald** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Comment by cdmihai** [comment]
Oh, I forgot about this on the master branch, but, if you want, you can also write a unit test or two to assert that the correct transition between the outer and inner build is happening. Totally up to you if you want to do it. @jeffkl did this for the project extension import, you can use his approach: https://github.com/Microsoft/msbuild/pull/994/files#diff-69f36dec75c7dfaca573deb2ee10097f

**Comment by nguerrera** [comment]
@cdmihai I will add tests in a follow-up PR.  Thanks for the pointer on how.

**Pull request merged**
