### PR TITLE
Replace Tuple -> struct Pair

### PR DESCRIPTION
**Pull request by davkean**
This was from 0.5 -> 1% allocations.

### CODE REVIEW

**Comment by davkean** [comment]
I ran this, but again - I'm having trouble believing these numbers unless the big decreases have huge number of transforms:

DotnetConsoleProject | Evaluation: Time (ms) | ::ok_hand: | no | 29.42 -> 29.2897 (-0.443%)
DotnetConsoleProject | Evaluation: Memory | :white_check_mark: | yes | 4612938 -> 4362790 (-5.423%)
DotnetWebProject | Evaluation: Time (ms) | :red_circle: | yes | 41.871 -> 45.7332 (9.224%)
DotnetWebProject | Evaluation: Memory | :white_check_mark: | yes | 6041295 -> 5943744 (-1.615%)
DotnetMvcProject | Evaluation: Time (ms) | :red_circle: | yes | 79.5815 -> 82.442 (3.594%)
DotnetMvcProject | Evaluation: Memory | :white_check_mark: | yes | 8302498 -> 8117427 (-2.229%)
Picasso | Evaluation: Time (ms) | :white_check_mark: | yes | 223.5462 -> 209.7916 (-6.153%)
Picasso | Evaluation: Memory | :white_check_mark: | yes | 31966591 -> 27832942 (-12.931%)
SmallP2POldCsproj | Evaluation: Time (ms) | :white_check_mark: | yes | 36.8747 -> 35.0461 (-4.959%)
SmallP2POldCsproj | Evaluation: Memory | :white_check_mark: | yes | 5107483 -> 4649467 (-8.968%)
Generated_100_100_v150 | Evaluation: Time (ms) | :white_check_mark: | yes | 1290.2636 -> 1225.8156 (-4.995%)
Generated_100_100_v150 | Evaluation: Memory | :white_check_mark: | yes | 170183102 -> 144673401 (-14.99%)
LargeP2POldCsproj | Evaluation: Time (ms) | :white_check_mark: | yes | 632.6196 -> 608.8298 (-3.761%)
LargeP2POldCsproj | Evaluation: Memory | :white_check_mark: | yes | 68924448 -> 60449496 (-12.296%)
roslyn | Evaluation: Time (ms) | :white_check_mark: | yes | 5109.8994 -> 4962.7952 (-2.879%)
roslyn | Evaluation: Memory | ::ok_hand: | no | 493903936 -> 491905140 (-0.405%)

**Comment by davkean** [comment]
tag @pilchie

**Comment by davkean** [comment]
@AndyGerlicher Can you run the perf tests for this change to see if these numbers are correct and I'm not doing something silly?

**Comment by AndyGerlicher** [comment]
Here's what I got. Seems pretty small. Odd differences between your results though. You run that on a VM? Let me know if you want access to the machine I use for perf.

### Evaluation: Time (ms)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :white_check_mark: | yes | 30.4342 -> 30.2113 (-0.732%)
DotnetWebProject | :white_check_mark: | yes | 49.4774 -> 49.3198 (-0.319%)
DotnetMvcProject | :red_circle: | yes | 86.1924 -> 86.4966 (0.353%)
Picasso | :red_circle: | yes | 257.0858 -> 258.2921 (0.469%)
SmallP2POldCsproj | :red_circle: | yes | 41.7239 -> 41.9707 (0.592%)
SmallP2PNewCsproj | :red_circle: | yes | 81.3506 -> 81.7168 (0.45%)
Generated_100_100_v150 | :white_check_mark: | yes | 1258.5643 -> 1246.1803 (-0.984%)
LargeP2POldCsproj | :red_circle: | yes | 733.3468 -> 742.9348 (1.307%)
roslyn | :red_circle: | yes | 5312.4182 -> 5345.2729 (0.618%)

### Evaluation: Memory (bytes)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | ::ok_hand: | no | 4912287 -> 4911893 (-0.008%)
DotnetWebProject | ::ok_hand: | no | 6812840 -> 6812308 (-0.008%)
DotnetMvcProject | ::ok_hand: | no | 8991971 -> 8991663 (-0.003%)
Picasso | ::ok_hand: | no | 35143262 -> 35143259 (0%)
SmallP2POldCsproj | ::ok_hand: | no | 5928057 -> 5927967 (-0.002%)
SmallP2PNewCsproj | :red_circle: | yes | 10485602 -> 10488192 (0.025%)
Generated_100_100_v150 | :white_check_mark: | yes | 146797135 -> 146785932 (-0.008%)
LargeP2POldCsproj | :ok_hand: | no | 85527904 -> 85529114 (0.001%)
roslyn | :white_check_mark: | yes | 582650762 -> 582624267 (-0.005%)

### Build: Time (ms)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 7.501 -> 7.5303 (0.391%)
DotnetWebProject | :white_check_mark: | yes | 9.2946 -> 9.2544 (-0.433%)
DotnetMvcProject | :red_circle: | yes | 10.0428 -> 10.1483 (1.051%)
Picasso | :red_circle: | yes | 2301.7976 -> 2313.6635 (0.516%)
SmallP2POldCsproj | :ok_hand: | no | 84.1259 -> 84.293 (0.199%)
SmallP2PNewCsproj | :red_circle: | yes | 86.8701 -> 87.1989 (0.378%)

### Build: Memory (bytes)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 1150084 -> 1154829 (0.413%)
DotnetWebProject | :white_check_mark: | yes | 1281036 -> 1277048 (-0.311%)
DotnetMvcProject | :white_check_mark: | yes | 1459096 -> 1453297 (-0.397%)
Picasso | :white_check_mark: | yes | 276322765 -> 269269079 (-2.553%)
SmallP2POldCsproj | :white_check_mark: | yes | 9737276 -> 9716240 (-0.216%)
SmallP2PNewCsproj | :white_check_mark: | yes | 9965061 -> 9960506 (-0.046%)

**Pull request merged**
