### PR TITLE
Merge #1104 to xplat

### PR DESCRIPTION
**Pull request by rainersigwald**
Only interesting conflicts were in `Tasks.csproj`--in xplat we'd split the targets into "interesting on netcore" and "not", so I had to bucket crosstargeting into "interesting".

### CODE REVIEW

**Comment by nguerrera** [comment]
The changes I recognize from master seem to have arrived fine.

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
I am fairly certain that this change didn't break `init-tools.sh`. It works on my Mac.

@dotnet-bot test OSX Build for CoreCLR please

**Comment by rainersigwald** [comment]
Tests pass on my Mac, so I'm going to go ahead with this.

**Pull request merged**
