### PR TITLE
Replace packages.config with project.json

### PR DESCRIPTION
**Pull request by rainersigwald**
Like dotnet/Roslyn#4753, we'd like to be on the more futureproof path.  Plus, hopefully this will make it easier to stay within striking distance of convergence between xplat and master.

### CODE REVIEW

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by jasonwilliams200OK** [comment]
Nit: you have commit 603f06d72fd42f8aaa37bd59bd66b7c03437c078 from other PR leaked into this one. You can rebase it out like this:

```cmd
cd msbuild
git checkout nuget-v3
git rebae -i HEAD~6
:: editor/notepad will open, remove the first line, save and close
git push -f  :: to re-write the history
```

IMO. :)

**Comment by rainersigwald** [comment]
@jasonwilliams200OK That was intentional; I was hoping to make sure I didn't break test result reporting.  In fact, of course, I broke *building* so it's irrelevant :cry:  I merged the other PR so this one is single-purpose again.

**Comment by rainersigwald** [comment]
@AndyGerlicher This revealed an interesting quirk of our build that I never saw before.  The second build (with our bootstrapped `MSBuild.exe`) doesn't use the same targets as the first, because the ToolsVersion is now 14.1.  That actually has interesting effects, because of this line:

```xml
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="'$(MicrosoftCommonPropsHasBeenImported)' != 'true' and Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')">
```

With the 14.1 toolset, we look at `C:\Program Files (x86)\MSBuild\14.1\Microsoft.Common.props`, which of course doesn't exist.  But because the `<Import>` is conditional, this doesn't fail anything--it just goes down a different codepath.  Notably, that codepath doesn't drag in the Nuget v3 targets from `C:\Program Files (x86)\MSBuild\14.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props`, which is why the build is failing now.

Any brilliant ideas about how to solve this?

**Comment by dsplaisted** [comment]
If the bootstrapped build is using the locally built version of MSBuild, then it should use `Microsoft.Common.Props` that comes from the local enlistment and is copied to the output path, right?

**Comment by rainersigwald** [comment]
@dsplaisted Yes, it should.  Getting it to actually do so has proven a bit tricky.  The core problem is that the Nuget targets work by assuming they are in a subfolder of MSBuildExtensionsPath, but since we don’t ship them they’re not in our local copy.  Right now I’m trying to figure out how to pull them from the installed location into our output path, but that will be more difficult on Unix when we don't have MSBuild installed.

I was curious how Roslyn handled nuget restore on Linux, so I looked:  while they're using MSBuild instead of xbuild, MSBuild on mono uses xbuild's targets, so Roslyn is able to drag in "installed" targets like so: https://github.com/dotnet/roslyn/blob/master/build/Targets/VSL.Settings.targets#L57

**Comment by dsplaisted** [comment]
@rainersigwald To self-compile the .NET Core version, we'll need to be able to run the NuGet targets, and we'll need to be able to do that without depending on anything installed on the machine.  The best solution is probably to have the NuGet team publish them in a NuGet package that we can depend on.  This could also solve the bootstrapped build problem when targeting .NET Framework.

**Comment by rainersigwald** [comment]
@dsplaisted I agree.  Do you know who we can ask on the NuGet team for such a thing?

For now, I think I've got it working with bootstrapping from the installed framework.  I even think that might work on Linux, because there `MSBuildExtensionsPath` points into a Mono folder that contains what we're looking for.

**Comment by rainersigwald** [comment]
Ok, with #193, things are passing.  Can somebody take a look? @AndyGerlicher @dsplaisted @ValMenn

**Comment by AndyGerlicher** [comment]
LGTM

**Pull request merged**
