### PR TITLE
FallbackTargetFrameworks in P2P refs

### LINKED ISSUE #2934: Adopt FallbackTargetFrameworks in GetReferenceNearestTargetFrameworkTask
After completion of https://github.com/NuGet/NuGet.Client/pull/1983, the call to that task in common.targets should support them through a project property.

cc @mishra14

### PR DESCRIPTION
**Pull request by rainersigwald**
Allows compatibility between a ProjectReference that doesn't build for
a directly-compatible TargetFramework but is compatible through
NuGet's AssetTargetFallback rules.

Closes #2934.

### CODE REVIEW

**Comment by rainersigwald** [comment]
@mishra14 is this all that's needed from our end? How can I test this?

**Comment by mishra14** [comment]
@rainersigwald this looks good. You should be able to test this by - 

1. get latest 15.7
2. install msbuild which contains the change
3. create a new UWP project and a net core 2.0 console app
4. add a reference from UWP project to the net core console app. This should fail.
5. add the following to the UWP csproj file - 

```
  <PropertyGroup>
    <AssetTargetFallback>netcoreapp2.0</AssetTargetFallback>
  </PropertyGroup>
```
6. add a reference from UWP project to the net core console app. This should work.

**Comment by rainersigwald** [comment]
@mishra14 Interesting! I'm seeing it pass on the command line--adding AssetTargetFallback=netcoreapp2.0 removes this error and the build succeeds

```
C:\Program Files (x86)\Microsoft Visual Studio\Preview\EntInt\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1656,5): error : Project '..\ConsoleApp1\ConsoleApp1.csproj' targets 'netcoreapp2.0'. It cannot be referenced by a project that targets 'UAP,Version=v10.0.17133'. [s:\repro\Microsoft\msbuild\issues\2934\App1\App1\App1.csproj]
```

But inside VS I can't add the reference and I see Package Manager errors:

```
NU1201: Project ConsoleApp1 is not compatible with uap10.0.17133 (UAP,Version=v10.0.17133). Project ConsoleApp1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
NU1201: Project ConsoleApp1 is not compatible with uap10.0.17133 (UAP,Version=v10.0.17133) / win10-arm. Project ConsoleApp1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
NU1201: Project ConsoleApp1 is not compatible with uap10.0.17133 (UAP,Version=v10.0.17133) / win10-arm-aot. Project ConsoleApp1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
NU1201: Project ConsoleApp1 is not compatible with uap10.0.17133 (UAP,Version=v10.0.17133) / win10-arm64-aot. Project ConsoleApp1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
NU1201: Project ConsoleApp1 is not compatible with uap10.0.17133 (UAP,Version=v10.0.17133) / win10-x64. Project ConsoleApp1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
NU1201: Project ConsoleApp1 is not compatible with uap10.0.17133 (UAP,Version=v10.0.17133) / win10-x64-aot. Project ConsoleApp1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
NU1201: Project ConsoleApp1 is not compatible with uap10.0.17133 (UAP,Version=v10.0.17133) / win10-x86. Project ConsoleApp1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
NU1201: Project ConsoleApp1 is not compatible with uap10.0.17133 (UAP,Version=v10.0.17133) / win10-x86-aot. Project ConsoleApp1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
```

This is with 
[uwp-references-netcoreapp2.zip](https://github.com/Microsoft/msbuild/files/1921280/uwp-references-netcoreapp2.zip) and applying the patch in this PR to my VS MSBuild install manually.

Is that a NuGet bug we need to follow up on?

**Comment by cdmihai** [comment]
Does the CI failure mean we have to bump up our Nuget dependency? `The "FallbackTargetFrameworks" parameter is not supported by the "GetReferenceNearestTargetFrameworkTask" task. Verify the parameter exists on the task, and it is a settable public instance property.`

**Comment by mishra14** [comment]
@rainersigwald We had an issue in NuGet where ATF did not work in P2P references. I have fixed it in https://github.com/NuGet/NuGet.Client/pull/2177 How do you want to proceed with this PR?

**Comment by rainersigwald** [comment]
Build changes that @AndyGerlicher is making in #3246 should unblock this.

**Comment by rainersigwald** [comment]
@Microsoft/msbuild-maintainers Looks like #3246 did indeed do the trick. This look ok?

**Pull request merged**
