### PR TITLE
Run tests under dotnet instead of coreclr host

### PR DESCRIPTION
**Pull request by rainersigwald**
Looks like we missed this one when we migrated most other things.

### CODE REVIEW

**Comment by jeffkl** [comment]
I'm assuming the failing tests don't mean this change is bad?  Otherwise it looks good to me.

**Comment by AndyGerlicher** [comment]
:shipit:

**Comment by rainersigwald** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Comment by cdmihai** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Comment by rainersigwald** [comment]
We've rerun it a few times. Pretty sure it's real 🙍. I'll look when I get a chance.

**Comment by rainersigwald** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

(post dotnet CLI update)

**Comment by rainersigwald** [comment]
Ok, here's my current understanding:

* @tmeschter wants this because a fix for #750 will only work inside the `dotnet` host
* Tests for this PR are failing legitimately: the failing tests involve copying `MSBuild.exe` to another directory and running it from there, which fails with `A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/private/var/folders/lh/m1h2nk097kzc5k8tlwhbf2kw0000gn/T/d21e7dc0988549219d8df36851fbcdee'.`
* I think _that_ will be fixed when we have a `deps.json`, which @jeffkl is working on

I'll get tests back to green by disabling them here to unblock the assembly-loading work.

**Comment by rainersigwald** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Comment by tmeschter** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Comment by tmeschter** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Pull request merged**
