### PR TITLE
Fix obsolete overload PtrToStructure

### PR DESCRIPTION
**Pull request by maddin2016**
This fixes obsolete overload`PtrToStructure` in `Copy_Tests.cs`.

### CODE REVIEW

**Comment by maddin2016** [comment]
I would like to discuss if this overload is deprecated or not. I have found some similiar [discussions.](https://github.com/dotnet/corefx/pull/10541).

**Comment by rainersigwald** [comment]
From that link, it sounds like the new generic version is preferred, even if the old version will continue to work and not be marked obsolete. Outside of the `shared/` folder (that gets compiled for .NET 3.5 and doesn't get to use new features), I like moving to newer mechanisms.

:shipit:

**Comment by jasonwilliams200OK** [comment]
@maddin2016, (for cleaner history of source tree) would be nice if you could rebase against master, so number of commits are reduced to one:

```sh
cd msbuild # your clone of your fork on local computer
git checkout fix-obsolete-method-PtrToStructure # your branch

# add upstream remote with organization/person name -> microsoft
# (this naming is just a good conversion that makes remote names easy
#  to remember by -- usually the name used in git docs is "upstream")
git remote add microsoft https://github.com/microsoft/msbuild

# and then the key thing: rebase against upstream target branch
# (it will keep your changes on top of the latest history of the
#  branch and remove noisy stuff like interim merge commits)
git pull --rebase microsoft master

# rewrite the history of your clone on remote server
# (automatically update this PR)
git push -f
```

Alternatively, the repo maintainers can squash the commits at the time of merging: https://help.github.com/articles/about-pull-request-merges/

~ happy coding :tada:

**Comment by AndyGerlicher** [comment]
LGTM. Thanks!

**Comment by maddin2016** [comment]
:+1:  No time to rebase :smile:

**Comment by jasonwilliams200OK** [comment]
Heh, yeah as you can see now there are unnecessary merge commits landed in the history under Aug 29: https://github.com/Microsoft/msbuild/commits/master.

**Comment by maddin2016** [comment]
@jasonwilliams200OK, what i meant was that i had no chance to rebase!!

**Comment by jasonwilliams200OK** [comment]
@maddin2016, I don't fault you for that, I mean there is always an option B to squash on merge. Don't take it too personal :wink:

**Comment by maddin2016** [comment]
:+1:

**Comment by AndyGerlicher** [comment]
Unfortunately I did squash and merge. If you look at the title/description of the "merge" commit it's what the UI would have presented when you select squash and merge. My only guess is some sort of stale data in the browser. It's possible I selected the wrong one (directly after reading the note from @jasonwilliams200OK to not do **exactly** that), but even so I clearly edited the message (removed the items for the subsequent commit messages). And I wouldn't have altered the title yet it doesn't have the standard merge commit title.

Very strange. Perhaps a GitHub bug?

**Comment by jasonwilliams200OK** [comment]
@AndyGerlicher, yes very strange.

The history shows this commit entry:

```
Fix obsolete overload PtrToStructure (#973)
AndyGerlicher committed on GitHub 2 days ago 
```

followed by @maddin2016's commits. The history suggests as if you have cherry-picked @maddin2016's commits on your master locally and pushed to master. Whereas, if this was merged from the UI, then this shouldn't be the case..seems very much like a bug.

Usually the squash on commit looks like this:

``` 
Remove self assignment (#964)
BBosman committed with AndyGerlicher 6 days ago
```
and the regular merge looks like this:

```
Merge pull request #967 from BBosman/casts
AndyGerlicher committed on GitHub 6 days ago 
```

**Pull request merged**
