### PR TITLE
Bootstrap NuGet download with msbuild instead of build.comd

### PR DESCRIPTION
**Pull request by dsplaisted**
This PR updates the build infrastructure to be closer to the current version in dotnet/buildtools.  It also downloads NuGet.exe as part of the MSBuild build instead of build.cmd.  This will help it work with the build lab infrastructure which needs to invoke an MSBuild project for the build.

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
LGTM

**Comment by rainersigwald** [comment]
LGTM

**Comment by weshaggard** [comment]
Interesting that you are going this direction. I'm actually thinking of going the opposite direction for the corefx repo. Why do you believe you need to go this way?

**Comment by dsplaisted** [comment]
> Interesting that you are going this direction. I'm actually thinking of going the opposite direction for the corefx repo. Why do you believe you need to go this way?

@weshaggard The entry point for MicroBuild needs to be an MSBuild project.  I don't think a script that downloads NuGet and then calls MSBuild is supported.

**Comment by weshaggard** [comment]
Interesting I'm going to have to look what @chcosta did for our xplat builds as I thought the were kicked off by a script.

**Comment by dsplaisted** [comment]
@weshaggard Are the xplat builds in MicroBuild or on something else like Jenkins?

**Comment by chcosta** [comment]
XPlat builds are in VSO (not MicroBuild) and are kicked off via a script.

**Pull request merged**
