### PR TITLE
Fix legacy msbuild issues

### PR DESCRIPTION
**Pull request by robashton**
MSBuild has caused me years of pain, replacing it with Make is probably sensible. :+1:

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
Not quite in the right spirit of this project. But please do feel free to create issues so we (or someone else) can address them. Thanks!

**Comment by mrange** [comment]
This PR makes me depressed. I guess it was intended as a joke but I only get sad.

**Comment by Bluerise** [comment]
Agreed. I don't like this as a joke. Glad to see you open source your stuff, MS.

**Comment by TommasoScalici** [comment]
I think GitHub is not the right place for humour...

**Comment by stack72** [comment]
+1 for this feature! Let's call is msbake ;)

**Comment by stack72** [comment]
OR 
http://mediacdn.snorgcontent.com/media/catalog/product/s/h/shakeandbake_fullpic_artwork.jpg

**Comment by charlesnw1** [comment]
@robashton Why don't you get working on that and submit a pull request when it's ready for preview. Or do you just want to be a prick/troll?

**Comment by stack72** [comment]
@charlesnw1 technically that's bullying - why so aggressive? It may be a legitimate request

**Pull request closed without merging**
