### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by yannisgu**
This PR adds an editorconfig as proposed in #17.

I took https://github.com/dotnet/roslyn/blob/master/.editorconfig and added the `insert_final_newline` and `trim_trailing_whitespace` from https://github.com/dotnet/corefx/blob/master/.editorconfig

### CODE REVIEW

**Comment by dhusemann** [comment]
I see that @KindDragon submitted a pull request for corefx to match Roslyn and coreclr.  https://github.com/dotnet/corefx/pull/1195 Update .editorconfig to match file from coreclr #1195 I would go with the https://github.com/dotnet/roslyn/blob/master/.editorconfig

**Comment by jasonwilliams200OK** [comment]
:+1: 
This is aligned with Roslyn's editorconfig + `insert_final_newline = true` and `trim_trailing_whitespace = true` which are important especially for code committed by Windows, otherwise it leaves a missing end of file marker in commits if user misses the newline.

**Comment by KindDragon** [comment]
@jasonwilliams200OK but it cause a lot of changes when you edit old files

**Comment by dhusemann** [comment]
I would say that trim_trailing_whitespace = true would require a Batch done on the entire project so there is a one time pain point before it is added to the .editorconfig probably accross all projects.

**Comment by KindDragon** [comment]
So better create separate PR with `trim_trailing_whitespace = true` and removed whitespaces

**Comment by dhusemann** [comment]
added this issue to codeformatter https://github.com/dotnet/codeformatter/issues/100

**Comment by jasonwilliams200OK** [comment]
@KindDragon, old files, as in three weeks ago old, when this project was added to GitHub? It should be fixed once for all and any new files pushed by git will be normalized before it hit the repo's surface.

**Comment by KindDragon** [comment]
@jasonwilliams200OK this repository probably synced with Microsoft internal repository, so some branches probably hided from us. This changes can cause a lot of conflicts with internal repository branches.

**Pull request merged**
