### PR TITLE
GenerateResources incrementality for netcore

### LINKED ISSUE #1197: GenerateResources task is not incremental on .NET Core
The `CoreResGen` target is [not incremental](https://github.com/Microsoft/msbuild/blob/672169fed3a16218f8301391f956c8279fc7dae7/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L2768-L2770), because it assumes that the `GenerateResources` task handles incrementality internally. It does . . . on full framework, when `FEATURE_BINARY_SERIALIZATION` is enabled and [`NeedToRebuildSourceFile`](https://github.com/Microsoft/msbuild/blob/575424a207f8b46b8299b48fdb930a4fb99ac402/src/XMakeTasks/GenerateResource.cs#L1410) gets called.

On .NET Core, though, that codepath falls back to the conservative-but-slow "always just rebuild".

(noticed by @eerhardt in https://github.com/dotnet/sdk/issues/284)

### PR DESCRIPTION
**Pull request by rainersigwald**
Closes #1197.

This implementation is sufficient for current .NET Core--see #1247 for
details. If we start supporting linked resources, this will produce false
up-to-date results and must be changed.

cc @danmosemsft @eerhardt

### CODE REVIEW

**Comment by danmosemsft** [comment]
LGTM thanks @rainersigwald . How do we get the dotnet/buildtools updated (which I guess updates the msbuild for dotnet/coreclr and dotnet/corefx)

**Comment by danmosemsft** [comment]
:shipit:

**Comment by rainersigwald** [comment]
Confirmed that this fixes the scenario from https://github.com/dotnet/sdk/issues/284 (on Windows). I'll look at the OS X failure shortly.

@danmosemsft To get this through to corefx/coreclr, we'll need to a) update buildtools and b) update the version reference in those repos. Unfortunately the current MSBuild version is pretty stale so part a) may be nontrivial. @joperezr has done those steps in the past.

**Comment by joperezr** [comment]
Once you have this change in a package, I'm happy to help getting it into buildtools and then to corefx/coreclr.

**Comment by rainersigwald** [comment]
@dotnet-bot test OSX Build for CoreCLR please

(checking for stability since there's a race condition in a lot of the incrementality tests on HFS+)

**Comment by danmosemsft** [comment]
@rainersigwald perhaps consider using #ifdef or XUnit attributes if possible so that the increased timeout is only for OSX. Otherwise all runs slow down unnecessarily.

**Comment by rainersigwald** [comment]
@danmosemsft Good point. Made it conditional on OS.

**Comment by rainersigwald** [comment]
@joperezr MSBuild packages versioned `15.1.0-preview-000358-00` should have this change. Ping me if there's trouble and we'll work through it.

**Pull request merged**
