### PR TITLE
remove debugging message from FileDirInfo

### LINKED ISSUE #755: Spurious "File not found" message when using Copy task
It looks like some debugging code was left in: https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeTasks/FileState.cs#L113

When I use the Copy task, everything seems to work fine, but I get spurious "File not found" messages which are kinda ugly :).

For example:

```
CopyBuildOutput:
  Creating directory "C:\Users\anurse\Code\aspnet\Options\artifacts\build\Microsoft.Extensions.Options.ConfigurationExtensions\Debug".
  Copying file from "C:\Users\anurse\Code\aspnet\Options\src\Microsoft.Extensions.Options.ConfigurationExtensions\bin\Debug\Microsoft.Extensions.Options.ConfigurationExtensions.1.1.0-t002d21da9.nupkg" to "C:\Users\anurse\Code\aspnet\Options\artifacts\build\Microsoft.Extensions.Options.ConfigurationExtensions\Debug\Microsoft.Extensions.Options.ConfigurationExtensions.1.1.0-t002d21da9.nupkg".
File not found (2): C:\Users\anurse\Code\aspnet\Options\artifacts\build\Microsoft.Extensions.Options.ConfigurationExtensions\Debug\Microsoft.Extensions.Options.ConfigurationExtensions.1.1.0-t002d21da9.symbols.nupkg
  Copying file from "C:\Users\anurse\Code\aspnet\Options\src\Microsoft.Extensions.Options.ConfigurationExtensions\bin\Debug\Microsoft.Extensions.Options.ConfigurationExtensions.1.1.0-t002d21da9.symbols.nupkg" to "C:\Users\anurse\Code\aspnet\Options\artifacts\build\Microsoft.Extensions.Options.ConfigurationExtensions\Debug\Microsoft.Extensions.Options.ConfigurationExtensions.1.1.0-t002d21da9.symbols.nupkg".
File not found (3): C:\Users\anurse\Code\aspnet\Options\artifacts\build\Microsoft.Extensions.Options.ConfigurationExtensions\Debug\netstandard1.1\Microsoft.Extensions.Options.ConfigurationExtensions.deps.json
  Creating directory "C:\Users\anurse\Code\aspnet\Options\artifacts\build\Microsoft.Extensions.Options.ConfigurationExtensions\Debug\netstandard1.1".
  Copying file from "C:\Users\anurse\Code\aspnet\Options\src\Microsoft.Extensions.Options.ConfigurationExtensions\bin\Debug\netstandard1.1\Microsoft.Extensions.Options.ConfigurationExtensions.deps.json" to "C:\Users\anurse\Code\aspnet\Options\artifacts\build\Microsoft.Extensions.Options.ConfigurationExtensions\Debug\netstandard1.1\Microsoft.Extensions.Options.ConfigurationExtensions.deps.json".
```

### PR DESCRIPTION
**Pull request by anurse**
I wasn't able to get it fully building locally (I didn't try very hard though, honestly ;)), but this is a pretty innocuous small change :). I assume there's some kind of CI process that will be able to check if I messed up the syntax :D.

Fixes #755 

/cc @rainersigwald

### CODE REVIEW

**Comment by rainersigwald** [comment]
Test hung, but that seems *really* unlikely to be the fault of this change! http://dotnet-ci.cloudapp.net/job/Microsoft_msbuild/job/_OSX_prtest/554/consoleFull#-16758747638101fac1-935e-4556-95f9-7a0e25ca0b52

@dotnet-bot test this please

**Comment by rainersigwald** [comment]
Thanks! This will reduce my own irritation with our build greatly :+1: 

LGTM.

**Comment by anurse** [comment]
Cool. I can't merge (no write access), but it sounds like it's good to go.

**Comment by rainersigwald** [comment]
@anurse Our policy is "approval by two maintainers" and 2/3 of the team is on vacation today, so it'll probably be in tomorrow :)

**Comment by anurse** [comment]
No problem, thanks for the heads-up on that policy :)

**Comment by rainersigwald** [comment]
hey @Microsoft/msbuild-maintainers that are back from vacation: any objections?

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
Thanks, @anurse for your contribution!

**Pull request merged**
