### PR TITLE
LOC CHECKIN | Microsoft/msbuild master | 20180518

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for CoreCLR please
@dotnet-bot test Ubuntu14.04 Build for CoreCLR please

Much flakiness in our tests :(
https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/innerloop_Windows_NT_CoreCLR_prtest/506/
https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/innerloop_Ubuntu14.04_CoreCLR_prtest/495/

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Ubuntu14.04 Build for CoreCLR please

**Comment by cdmihai** [comment]
@v-zbsail there's a conflict in the PR. What is the process for this? Do you restart localization?

**Comment by v-zbsail** [comment]
@cdmihai the agreed process is that we create the temporary branch at the same time as we take the files for localization to help you with possible conflict resolution.

**Pull request merged**
