### PR TITLE
Change microsoft.net.compilers to capital Microsoft.Net.Compilers to …

### PR DESCRIPTION
**Pull request by mikkeljohnsen**
…allow it working on Unix (case-sensitive filesystems)

### CODE REVIEW

**Comment by dasMulli** [comment]
I though NuGet deliberately uses lowercase package names in the cache folder to allow case insensitive references (making everything lowercase)

**Comment by cdmihai** [comment]
I confirm, on my windows machine everything in `repoRoot/packages` is lowercase. @mikkeljohnsen, under what conditions are you seeing capitalized directories under `repoRoot/packages`?

**Comment by mikkeljohnsen** [comment]
This is my packages/ folder:

```
-rw-r--r--. 1 mkj mkj    0  3 apr 14:21 BuildTools.semaphore
drwxr-xr-x. 1 mkj mkj   10  3 apr 14:20 MicroBuild.Core
drwxr-xr-x. 1 mkj mkj   52  3 apr 14:20 Microsoft.DotNet.BuildTools
drwxr-xr-x. 1 mkj mkj   40  3 apr 14:20 Microsoft.DotNet.BuildTools.GenAPI
drwxr-xr-x. 1 mkj mkj   36  3 apr 14:20 Microsoft.Net.Compilers
drwxr-xr-x. 1 mkj mkj 6008 14 apr  2016 msbuild
drwxr-xr-x. 1 mkj mkj   12  3 apr 14:20 Nerdbank.GitVersioning
drwxr-xr-x. 1 mkj mkj   10  3 apr 14:20 NuSpec.ReferenceGenerator
drwxr-xr-x. 1 mkj mkj   10  3 apr 14:20 xunit.runner.console

```

I don't see any option for setting the packages to be lower-case. This is "NuGet Version: 3.5.0.1996" on Linux (Fedora 25).

**Comment by jeffkl** [comment]
The reason the folders are proper cased is because we're passing `--legacy-packages-directory` in `init-tools.sh` [here](https://github.com/Microsoft/msbuild/blob/master/init-tools.sh#L18).  This was set at the time because a dependency we have (BuildTools) had everything proper cased and when NuGet switched to lowercase directory names it broke us.

**Comment by AndyGerlicher** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Comment by rainersigwald** [comment]
@radical @directhex can you take a look at this? It appears to only affect the Mono codepath.

**Comment by rainersigwald** [comment]
Closing this PR because it's ancient and it should be superseded by #2868.

**Pull request closed without merging**
