### PR TITLE
Lower verbosity of BeforeTargets/AfterTargets diagnostics

### PR DESCRIPTION
**Pull request by danmosemsft**
Fixes https://github.com/Microsoft/msbuild/issues/1217

Test failures in GetUnversionedSDKUnionMetadataLocation and some response file tests seem unrelated.

@rainersigwald

### CODE REVIEW

**Comment by danmosemsft** [comment]
@jeffkl do I need to submit a PR for xplat (where we consume MSBuidl) or will it get there soon anyway?

**Comment by rainersigwald** [comment]
@danmosemsft This has been merged to xplat. Do you need an updated build in a particular VS branch or anything?

**Comment by danmosemsft** [comment]
My bad - you're right, it's there.

**Comment by rainersigwald** [comment]
Yeah, I really wish GitHub made it easier to see what branches a commit is in . . .

**Pull request merged**
