### PR TITLE
Move to System.CodeDom 4.5.0

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
See #3627, this is causing issues for WPF and WinForms

**Comment by nguerrera** [comment]
MSBuild 16 can run on .NET Core 2.x and will do so in the 2.1 and optional 2.2 CLI that ship with VS 16.


Also not sure about what is impacted in the .net framework case by this package reference. 

But if we can take latest here, we might need dependency uptake, which would probably be blocked on move to arcade in progress.

The other thing we can do is make PresentationBuildTasks ref RTM without impacting shared framework. That's probably better than forcing msbuild to bleeding edge? What do you think? I might need some help making that change to PBT.

**Comment by ericstj** [comment]
>  make PresentationBuildTasks ref RTM without impacting shared framework

Yeah, let's do that.  I can help.

**Comment by livarcocc** [comment]
@nguerrera @rainersigwald should we finally take this for 16.2?

**Comment by rainersigwald** [comment]
I don't know of a reason not to.

**Comment by nguerrera** [comment]
Replaced by https://github.com/dotnet/cli/issues/11444, which will ensure we lift up to current and supports source build. I think it is better for us to handle this unification in the toolset publishing because it allows the consitituent repos to package themselves up in other ways that might need to ship on a different schedule, etc.

**Pull request closed without merging**
