### PR TITLE
Adopt Shouldly for test assertions

### PR DESCRIPTION
**Pull request by jeffkl**
Update Framework unit tests to use Shouldly

[Shouldly](https://github.com/shouldly/shouldly) provides extension methods for assertions and also creates very detailed messages when assertions fail.  The documentation is here:  http://shouldly.readthedocs.io

### CODE REVIEW

**Comment by dasMulli** [comment]
fyi the CLI repo makes heavy use of [FluentAssertions](https://github.com/fluentassertions/fluentassertions) and already built a set of [very useful extensions](https://github.com/dotnet/cli/tree/master/test/Microsoft.DotNet.Tools.Tests.Utilities/Assertions) for it, mostly around filesystem concerns (e.g. [`binDirectory.Should().HaveFilesMatching("*.dll", SearchOption.AllDirectories);`](https://github.com/dotnet/cli/blob/6ecc1fc6c3f58bde065413cc869fb7f97d296143/test/EndToEnd/GivenDotNetUsesMSBuild.cs#L45))

**Comment by jeffkl** [comment]
@dotnet-bot test Windows_NT Build for CoreCLR please

**Comment by jeffkl** [comment]
@dotnet-bot test this please

**Comment by jeffkl** [comment]
@dotnet-bot test Windows_NT Build for CoreCLR please

**Comment by jeffkl** [comment]
@dotnet-bot test this please

**Comment by jeffkl** [comment]
@dotnet-bot test Windows_NT Build for Full please

**Comment by jeffkl** [comment]
@AndyGerlicher can I merge this now?

**Pull request merged**
