### PR TITLE
Escape expected output in ImportedProjectsSdkImportsAreInPreprocessedOutput

### LINKED ISSUE #2932: ImportedProjectsSdkImportsAreInPreprocessedOutput test is failing in CI
But passing locally. Disabling it to get on with merging.
FYI @jeffkl 

1b8fa71b83eac9141a6cff8d858b03af2c4a9140

### PR DESCRIPTION
**Pull request by jeffkl**
Fixes #2932

### CODE REVIEW

**Comment by jeffkl** [comment]
@cdmihai what's up with these build failures?

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for CoreCLR please
@dotnet-bot test Windows_NT Build for Full please

**Comment by cdmihai** [comment]
Those failures are new under the sun :)
It looks as if the VS script is changing the current directory, but that can't be it.

**Comment by cdmihai** [comment]
Investigating in https://github.com/Microsoft/msbuild/pull/2937 😢

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by cdmihai** [comment]
The remaining CI jobs seem to be dangling ... zombie jobs from before the old build logic. Triggered a deletion of the master jobs, hopefully that will remove them.

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by cdmihai** [comment]
@dotnet-bot test ci please

**Comment by cdmihai** [comment]
@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
the master branch generator job doesn't seem to exist, and no master branch jobs exist. All of the CIs into master are just dangling :(

**Pull request merged**
