### PR TITLE
Pdb git and source link

### PR DESCRIPTION
**Pull request by KirillOsenkov**

### CODE REVIEW

**Comment by rainersigwald** [comment]
Ok, now I'm additionally confused by the interplay between this and https://github.com/dotnet/roslyn/pull/18539.

**Comment by KirillOsenkov** [comment]
I don't think we should worry about that since we still have the limitation of the MS internal symbol server not supporting any of this.

We now have three PRs that adds source indexing, let's pick one! I vote for this one :)

**Comment by nguerrera** [comment]
Are coreclr symbols indexed anywhere today? Trying to debug dotnet/sdk#1299 and having a hard time finding symbols.

**Comment by rainersigwald** [comment]
@nguerrera You're talking about MSBuild-on-core symbols? We attempt to index them but I think the symbol server gets confused and doesn't actually work. I'm reswizzling our official build in a way that will (I think) cause them to be published to VSTS (devdiv.microsoft.com) for internal folks. And then hopefully we can get this in soonish and just embed the symbols.

**Comment by nguerrera** [comment]
Yes, that's what I meant

**Comment by rainersigwald** [comment]
@nguerrera Symbols should be available internally under \\cpvsbuild\drops\MSBuild\MSBuild-All-Signed-Release if a gremlin hasn't gotten to them. And we turned /deterministic on, so they should be reconstructible if it comes to that.

(to tide you over until we actually fix things)

**Comment by rainersigwald** [comment]
@KirillOsenkov can you take a look and see if any of the places where I disabled this seem too sketchy?

You can tell my fixes are going to be amazing by the quantity of `fixup!` commits.

**Comment by KirillOsenkov** [comment]
All looks good to me, thanks so much for doing this!

**Comment by rainersigwald** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Comment by rainersigwald** [comment]
Just tried this--it looks like it's working beautifully for .NET Core:

image

(and that `XMake.cs` was downloaded!)

But something's not right with the full framework assemblies--VS prompts me to find source files. It's possibly related to the VSTS "index sources" step that's post-processing the binaries even after PDBGit, but doesn't support non-VSTS source locations. Maybe that's removing something? I'll continue to poke at a thing or two.

**Comment by KirillOsenkov** [comment]
Note that you can use `Pdb2Xml.exe /srcsrv Microsoft.Build.dll` and it will dump an XML file which the srcsrv section. You need to have the .pdb right next to the .dll.

https://github.com/dotnet/symreader-converter
https://dotnet.myget.org/feed/symreader-converter/package/nuget/Pdb2Xml/1.0.0-beta1-61722-03

Or you can just open the .pdb in the editor of your choice and search for SRCSRV, it'll be towards the bottom ;)

**Comment by rainersigwald** [comment]
Caught a mistake (wrong version in the import for SourceLink) and force-pushed it, but GitHub hasn't caught up. When it realizes that it needs to re-merge and re-test I'll merge this.

**Comment by rainersigwald** [comment]
Odd failed test: https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/innerloop_Ubuntu16.04_CoreCLR_prtest/58/testReport/junit/Microsoft.Build.UnitTests.GenerateResource_Tests.InProc/RequiredTransformations/ForceSomeOutOfDate/

```
MESSAGE:
Assert.True() Failure\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at Microsoft.Build.UnitTests.GenerateResource_Tests.Utilities.ExecuteTask(GenerateResource t) at Microsoft.Build.UnitTests.GenerateResource_Tests.InProc.RequiredTransformations.ForceSomeOutOfDate()
```

**Comment by rainersigwald** [comment]
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

**Comment by rainersigwald** [comment]
@dotnet-bot test Ubuntu14.04 Build for CoreCLR please

**Comment by rainersigwald** [comment]
@dotnet-bot test Ubuntu14.04 Build for CoreCLR please

**Comment by KirillOsenkov** [comment]
🎆 🍾 👍

**Pull request merged**
