### PR TITLE
Skip CI test result archiving if no test result files found

### PR DESCRIPTION
**Pull request by cdmihai**
We can't differentiate PR jobs by the branch they target. This is an issue because PRs targeting master should only have Windows CI jobs. 

For tests, this means the CI should only collect test results when test result files are there. The only risk here is that if someone turns off the tests entirely, the main build succeeds and Jenkins will not complain.

### CODE REVIEW

**Comment by rainersigwald** [comment]
Change seems reasonable. Is this fixing a problem we're currently seeing?

**Comment by AndyGerlicher** [comment]
Only thing I don't like about this is if there are no tests reported I would consider that a failure. How about always report when on Windows and set `reported=true` then if `reported==false` after the switch optionally report?

**Comment by cdmihai** [comment]
Added a flag so windows builds require test results to be there.

**Comment by cdmihai** [comment]
No test run summaries for !Windows CI jobs in the PR CI results.

---
In reply to: [219143399](https://github.com/Microsoft/msbuild/pull/619#issuecomment-219143399) [](ancestors = 219143399)

**Comment by AndyGerlicher** [comment]
LGTM

**Comment by rainersigwald** [comment]
Got it.

LGTM

---
In reply to: [219188863](https://github.com/Microsoft/msbuild/pull/619#issuecomment-219188863) [](ancestors = 219188863,219143399)

**Pull request merged**
