### PR TITLE
Remove forked Framework code

### PR DESCRIPTION
**Pull request by rainersigwald**
We added local copies of these things because they weren't available in .NET Core 1.0. Since we now target 2.x, we can delete code.

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
@dotnet-bot test this please

**Comment by AndyGerlicher** [comment]
@dotnet-bot test OSX10.13 Build for CoreCLR please

**Comment by AndyGerlicher** [comment]
FYI pushed a rebase for CI refresh reasons.

**Comment by AndyGerlicher** [comment]
Ubuntu and OSX hanging at the same place 2 times in a row :(

**Comment by rainersigwald** [comment]
Something obviously continues to be wrong, but I don't know what. Even attempting CI-like builds works on both my Mac and Ubuntu 18.04 machines. Trying in a 16.04 container now.

**Comment by rainersigwald** [comment]
My 16.04 container fails only `Microsoft.Build.Tasks.UnitTests.Unzip_Tests.LogsErrorIfReadOnlyFileCannotBeOverwitten` (looks like it's not actually getting marked readonly or something).

**Comment by akoeplinger** [comment]
> (looks like it's not actually getting marked readonly or something).

@rainersigwald it's more likely that you're root inside of your container, the root user can still write to read-only files.

**Comment by rainersigwald** [comment]
I didn't change anything but now the build passes in CI like it always did on my machines. I think we should go forward with the change; if it starts failing again we can dig in then. Sound ok, @livarcocc?

**Comment by livarcocc** [comment]
Let's do it.

**Pull request merged**
