### PR TITLE
Specifically passing in empty arrays to methods expecting params Arrays to fix build break on corefx caused by upgrade on buildtools.

### PR DESCRIPTION
**Pull request by joperezr**
Specifically passing in empty arrays to methods expecting params Arrays to fix build break on corefx caused by upgrade on buildtools.

Whenever a method expects:
```cs
public void myMethod(params object[])... 
```
and nothing gets passed in, the compiler will by default add a:
```cs
Array.Empty<object>()
```
which is not supported on frameworks lower than 4.6 or Mono msbuild. Given a recent change in buildtools to consume the nuget package "Microsoft.Build.Tasks.Core" (version: 0.1.0-preview-00005), builds in Razzle (uses .Net Framework 4.5) and linux are broken when trying to consume buildtools. The ask is to submit this code to generate a new package for Microsoft.Build.Tasks.Core and then reference that back from buildtools so that the build break is fixed.

### CODE REVIEW

**Comment by joperezr** [comment]
cc @weshaggard @dsplaisted

**Comment by weshaggard** [comment]
It sucks that we have to do this but I don't see any easier way to do it right now. Thanks for fixing this @joperezr.

LGTM

**Comment by joperezr** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
Just trying to make sure I understand the situation:

There's a Roslyn optimization for assemblies that target 4.6+ that is (in #173) getting misapplied because MSBuild "rounds up" the reference assemblies.  Here it's applied because the .NET Core reference assemblies have `Array.Empty<T>`, but then that's failing when run on a .NET 4.5 host, meaning we can't produce a single assembly that's compatible with full-framework 4.5 AND .NET Core, because to target .NET Core we have to use fancy new reference assemblies that trigger the optimization, and to target 4.5 we have to use old ones that don't trigger it, and that's unresolvable.

So yeah, this seems like the best option for now.  Should we ask the Roslyn folks to reevaluate that optimization in light of this?

If that understanding is correct, LGTM.

**Comment by rainersigwald** [comment]
It looks like the test failures are related to this change:

```
09:02:16      FailedResXReaderWithAllOutputResourcesSpecified [FAIL]
09:02:16         Microsoft.Build.Shared.InternalErrorException : MSB0001: Internal MSBuild Error: Invalid resource parameter type, was System.Object[]
09:02:16         Stack Trace:
09:02:17            d:\j\workspace\Microsoft_msbuild\innerloop_prtest\src\Shared\ErrorUtilities.cs(60,0): at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
09:02:17            d:\j\workspace\Microsoft_msbuild\innerloop_prtest\src\Shared\ResourceUtilities.cs(263,0): at Microsoft.Build.Shared.ResourceUtilities.FormatString(String unformatted, Object[] args)
09:02:17            d:\j\workspace\Microsoft_msbuild\innerloop_prtest\src\Shared\TaskLoggingHelper.cs(267,0): at Microsoft.Build.Utilities.TaskLoggingHelper.FormatString(String unformatted, Object[] args)
09:02:17            d:\j\workspace\Microsoft_msbuild\innerloop_prtest\src\Shared\TaskLoggingHelperExtension.cs(114,0): at Microsoft.Build.Tasks.TaskLoggingHelperExtension.FormatResourceString(String resourceName, Object[] args)
09:02:17            d:\j\workspace\Microsoft_msbuild\innerloop_prtest\src\Shared\TaskLoggingHelper.cs(509,0): at Microsoft.Build.Utilities.TaskLoggingHelper.LogMessageFromResources(MessageImportance importance, String messageResourceName, Object[] messageArgs)
09:02:17            d:\j\workspace\Microsoft_msbuild\innerloop_prtest\src\Shared\TaskLoggingHelper.cs(489,0): at Microsoft.Build.Utilities.TaskLoggingHelper.LogMessageFromResources(String messageResourceName, Object[] messageArgs)
09:02:17            d:\j\workspace\Microsoft_msbuild\innerloop_prtest\src\XMakeTasks\GenerateResource.cs(2476,0): at Microsoft.Build.Tasks.ProcessResourceFiles.ProcessFile(String inFile, String outFileOrDir)
09:02:17            d:\j\workspace\Microsoft_msbuild\innerloop_prtest\src\XMakeTasks\GenerateResource.cs(2340,0): at Microsoft.Build.Tasks.ProcessResourceFiles.Run(TaskLoggingHelper log, ITaskItem[] assemblyFilesList, List`1 inputs, List`1 satelliteInputs, List`1 outputs, Boolean sourcePath, String language, String namespacename, String resourcesNamespace, String filename, String classname, Boolean publicClass, Boolean extractingResWFiles, String resWOutputDirectory)
09:02:17            d:\j\workspace\Microsoft_msbuild\innerloop_prtest\src\XMakeTasks\GenerateResource.cs(771,0): at Microsoft.Build.Tasks.GenerateResource.Execute()
09:02:17            GenerateResource_Tests.cs(1405,0): at Microsoft.Build.UnitTests.GenerateResource_Tests.InProc.TransformationErrors.FailedResXReaderWithAllOutputResourcesSpecified()
```

**Comment by joperezr** [comment]
I'm clossing this PR since we won't be doing this to fix the issue anymore. Instead, we have made some changes in the buildtools package to address this problem.

**Comment by rainersigwald** [comment]
@joperezr Can you link the buildtools changes here?  Mostly I'm just curious.

**Comment by joperezr** [comment]
Sure, basically we had to create two versions of the task library, one that runs in .Net Core, and one that targets .Net 4.5. This way, when we load buildtools in an environment that doesn't support 4.6 we will simply use the targets compiled for 4.5. The merged PR is: dotnet/buildtools#342

**Pull request closed without merging**
