### PR TITLE
Release branding for 16.3

### PR DESCRIPTION
**Pull request by rainersigwald**
We shouldn't merge this until we're ready, as every change after that will require a manual version bump.

### CODE REVIEW

**Comment by rainersigwald** [comment]
We also can't do this until we've gotten release-branded CoreFX, because of this error:

```
error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "System.Resources.Extensions [4.6.0-preview9.19416.11, )" or update the version field in the nuspec.
```

**Comment by livarcocc** [comment]
Hum, it seems like we will then have to insert msbuild along with the SDK into VS then. As the whole thing will have to be final.

cc @mmitche @johnbeisner

**Comment by mmitche** [comment]
Got it.  Yeah, hold off on this until we verify that we won't accidentally publish the final bits to public feeds.

**Comment by mmitche** [comment]
@rainersigwald is the corefx package that msbuild depends on an OOB package?

**Comment by rainersigwald** [comment]
@ericstj is `System.Resources.Extensions` an OOB package?

**Comment by ericstj** [comment]
Define OOB.  It is a package that can work on more than just .NETCore.  It carries a .NETStandard implementation.  It builds out of corefx and versions with the product.  Just like every other package in CoreFx (eg: System.Reflection.Metadata, System.Collections.Immutable, etc).  Let me know if this answers your question or not.

**Comment by mmitche** [comment]
> Define OOB. It is a package that can work on more than just .NETCore. It carries a .NETStandard implementation. It builds out of corefx and versions with the product. Just like every other package in CoreFx (eg: System.Reflection.Metadata, System.Collections.Immutable, etc). Let me know if this answers your question or not.

Yep.  It was a question of whether they should be depending on this package in context of Microsoft.NETCore.App.  This is fine as it is.

**Comment by ericstj** [comment]
Yeah, it's not part of the base shared framework so they need the dependency.

**Comment by livarcocc** [comment]
We now have a stable version for these dependencies.

@mmitche will push the packages to the feed.

**Comment by mmitche** [comment]
Holding off on this until I get a quick arcade update to ensure no accidental stable publishing

**Pull request merged**
