### PR TITLE
Include GetAssemblyIdentity task in netstandard2.0 build.

### PR DESCRIPTION
**Pull request by dasMulli**
Enables the GetAssemblyIdentity task on the new ns2.0 build.

### CODE REVIEW

**Comment by dasMulli** [comment]
@dotnet-bot test ci please

**Comment by dasMulli** [comment]
@dotnet-bot test this please

**Comment by dasMulli** [comment]
@cdmihai are dotnet-bot commands restricted to members here?..

**Comment by rainersigwald** [comment]
Yay, CI is fixed.

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Windows_NT Build for Full please

**Comment by dasMulli** [comment]
Weird issue, the last two fullfx builds failed on different `GetSDKReference` tests. Locally this works (though I get a build engine test failure locally on master and pr branch)..

@dotnet-bot test Windows_NT Build for Full please

**Comment by rainersigwald** [comment]
I just realized "there's no tests turned on for this" but then I looked and there aren't any tests for it period :(

I'd guess there is some flakiness yet to be ironed out in the tests post-netstandard2.0, but I don't see how this could have caused any problems so let's just go ahead.

**Pull request merged**
