### PR TITLE
Fix build on RHEL 7

### PR DESCRIPTION
**Pull request by omajid**
- Add detection for `rhel.7-x64` runtime id to cibuild.sh
- Add `rhel.7-x64` runtime ids to project.json's with runtime sections

Tested on RHEL 7.3 with a `./cibuild.sh`.

### CODE REVIEW

**Comment by omajid** [comment]
Yes. I tested it (only) on RHEL 7.3.

**Comment by rainersigwald** [comment]
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

(it looks like something convinced the init script that it was running on 16.10? But the machine was named `ubuntu1604-20170216-40d4a0` which I assume implies 16.04 . . .)

**Comment by borgdylan** [comment]
16.10 support need to be added along with 17.04 as well. Ubuntu 17.04 will be out in April.

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

**Comment by omajid** [comment]
Is the issue being experience by the builder a general issue or is it a bug in the fix?

**Comment by rainersigwald** [comment]
@omajid I don't think it's related to your change; I plan to spend some time today chasing it down. No action needed from you at the moment . . .

**Comment by rainersigwald** [comment]
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

**Comment by rainersigwald** [comment]
Looks good. @Microsoft/msbuild-maintainers can I get a second opinion?

**Comment by AndyGerlicher** [comment]
Thanks! Sorry for the confusion on had build issues not related to this change.

**Comment by omajid** [comment]
Thanks for accepting this!

**Pull request merged**
