### PR TITLE
Fix merge issue: remove incorrect and stale duplicates of targets

### PR DESCRIPTION
**Pull request by nguerrera**
@raines Somehow the merge in #1105 brought in the fix from #1104 as a separate copy of the target and surrounding code, but above the old code that is still broken!

cc @eerhardt @srivatsn

### CODE REVIEW

**Comment by nguerrera** [comment]
@mmitche Is jenkins still having trouble getting through the queue?

**Comment by mmitche** [comment]
@nguerrera Just a bit backed up.  I requested another core increase so that should help.  But it looks like you're stuff just started

**Comment by nguerrera** [comment]
Is the Mac build stuck?

**Comment by rainersigwald** [comment]
@nguerrera looks like it. I'll be optimistic.

**Pull request merged**
