### PR TITLE
Linux build

### PR DESCRIPTION
**Pull request by ValMenn**
Build for Linux on Windows.

This adds new configuration to build for Linux on Windows. The results starts running (does not fully run, though).

### CODE REVIEW

**Comment by dsplaisted** [comment]
I would like us to consider whether we need separate configurations building for Linux.  Ideally, the .NET Core version of MSBuild itself should be identical across platforms, and it would just need a different version of the .NET Core runtime to run on each platform.

For that to work, we'd need to disable the registry access on Windows when compiling for .NET Core.  I think that's OK.  It may mean that we can't use .NET Core MSBuild to build projects targeting full .NET Framework, but that wasn't a scenario we were targeting anyway.

If we don't introduce separate configurations for Linux, then we will need to come up with a way of deploying the right runtime for a target OS.

If we do want to go ahead and add separate configurations for Linux, then we should add FEATURE_WIN32_REGISTRY to DefineConstants in dir.props for configurations that should continue to use the registry.

**Comment by rainersigwald** [comment]
I agree that it'd be nice to have only one NetCore configuration.  I added a few feature flags that discuss the reasons that MSBuild touches the registry--`REGISTRY_TOOLSETS` and `REGISTRY_SDKS`.  I think so far I've only disabled tests with them but they should apply to product code as well.

**Comment by ValMenn** [comment]
The 3rd commit adds FEATURE_WIN32_REGISTRY if we are targeting Windows. I agree that the versions should differ by runtime only, but having different configurations is a reasonable interim solution in my opinion until we find how to deal with that.

**Comment by dsplaisted** [comment]
The resolution of our discussion was that we're OK with having separate configurations for Linux right now, but would like to remove them when we have a better way of deploying the right runtime.

So, this PR LGTM, though I don't know about the CI failure.

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
LGTM.  With a bit of prodding and my fixes merged in CI seems happy too.

**Comment by AndyGerlicher** [comment]
LGTM

**Pull request merged**
