### PR TITLE
Convert to xunit

### PR DESCRIPTION
**Pull request by rainersigwald**
This takes the rest of the tests to xunit.  It builds but some tests are definitely failing.  I mostly just want to see the test report from the PR build :smiley:

I expect to rebase/squash/generally rewrite history before I'm done here, so don't base any changes off these commits.

### CODE REVIEW

**Comment by Maxwe11** [comment]
Do we still need Microsoft.VisualStudio.QualityTools.UnitTestFramework reference in *.csproj file?

**Comment by AndyGerlicher** [comment]
That's a lot to look through, but looks good! Had one comment, and yeah what Maxwe11 said. Can't wait to get this into xplat so we can have one test framework!

**Comment by rainersigwald** [comment]
Ok, CI build is passing now, if maybe not reliably.  I suspect we'll be hunting bugs and unreliabilities in tests for a while :persevere:.

@Maxwe11 @AndyGerlicher I think I addressed your concerns.

All: I know this is huge, but can you take a look now?

**Comment by dsplaisted** [comment]
In [TaskRegistry_Tests.cs](https://github.com/rainersigwald/msbuild/blob/77444e4047d2e8e963180c8eed09478808ff3f92/src/XMakeBuildEngine/UnitTests/BackEnd/TaskRegistry_Tests.cs), what's the reason for compiling an assembly on the fly instead of just building it as part of the test build?

**Comment by dsplaisted** [comment]
In [AssemblyTaskFactory_Tests](https://github.com/rainersigwald/msbuild/commit/33fae7b764b36f47f15d2bdbd7faa3d27f4991f9), xUnit's [Assert.IsNotType](https://github.com/xunit/xunit/blob/789ac3bbcaaf5fd860bbeb8dec70e81e39eb373d/src/xunit.assert/Asserts/TypeAsserts.cs#L57) has a different behavior.  It checks if the types are exactly identical, not whether the type is assignable from type of the object.

**Comment by dsplaisted** [comment]
Looks like [several](https://github.com/rainersigwald/msbuild/commit/fff28fe0a581812305c0cb5fd970e31110d7f114) [of](https://github.com/rainersigwald/msbuild/commit/90e021dc5020307ec5ef2de205538523238183d6) [the](https://github.com/rainersigwald/msbuild/commit/13c2723afe67bc7ee00d0d9859982b87da3f2e97) commits for the automated conversion to xUnit have the wrong first line for the commit description: `Convert Utilities unit tests to xunit`

**Comment by dsplaisted** [comment]
Left some comments but LGTM! :shipit:

**Comment by AndyGerlicher** [comment]
LGTM

**Comment by rainersigwald** [comment]
Filed #211 to stop building things unnecessarily in our unit tests (@dsplaisted).

**Comment by rainersigwald** [comment]
@dsplaisted I couldn't see any place where duplicate node request IDs would be interesting, and it doesn't seem to have caused any functional problems.  Leaving as is for now.

**Pull request merged**
