### PR TITLE
IDE0028: Simplify object collection

### PR DESCRIPTION
**Pull request by pi1024e**
All changes were done by the IDE

### CODE REVIEW

**Comment by rainersigwald** [comment]
Can you be extremely pedantic about what you did to produce the refactoring here? Was it a "fix all in solution" on `IDE0028`? Which solution did you have open at the time (`MSBuild.sln` or `MSBuild.dev.sln`)? Did you do any manual fixups afterward?

**Comment by pi1024e** [comment]
Every change was automatic. I did no manual fixes or changes.

**Comment by pi1024e** [comment]
cc: @rainersigwald

**Comment by pi1024e** [comment]
It was a fix all solution, but I checked every single one and disabled the refactorings of object collection that was incorrect.

**Comment by pi1024e** [comment]
MSBuild.dev.sln was open at the time

**Comment by rainersigwald** [comment]
Team triage: Thank you for the pull request. At the moment, we don't have a formally defined `.editorconfig` code style, so we'd like to defer all automated style fixes until we do (#4092).

**Pull request closed without merging**
