### PR TITLE
Update .NET CLI and fix change in file pattern match behavior on non-Windows

### PR DESCRIPTION
**Pull request by jeffkl**
Update .NET CLI from 2.1.300-preview2-008046 to 2.1.300-preview2-008293

This pulls in changes to corefx where non-Windows will now have more consistent behavior with Windows in regards to file pattern matching.  Unfortunately, the behavior in Windows is incorrect for our needs so we now need to manually correct matches on all platforms.

https://github.com/dotnet/corefx/issues/27779

Tracking updating the behavior later here: https://github.com/Microsoft/msbuild/issues/3060

### CODE REVIEW

**Comment by jeffkl** [comment]
Holding off on merging this until its passing on Mac

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by jeffkl** [comment]
@dotnet-bot test OSX10.13 Build for CoreCLR please

**Comment by jeffkl** [comment]
@dotnet-bot test OSX10.13 Build for CoreCLR please

**Comment by jeffkl** [comment]
@dotnet-bot test OSX10.13 Build for CoreCLR please

**Pull request merged**
