### PR TITLE
Change Microsoft.VisualBasic.targets encoding to utf-8

### LINKED ISSUE #306: Visual Basic targets are not in UTF-8
https://github.com/Microsoft/msbuild/blob/7eaf6cb744bdd48e8b88b952758e604e8d9ee638/src/XMakeTasks/Microsoft.VisualBasic.targets#L1

```xml
<?xml version="1.0" encoding="Windows-1252"?>
```

This caused test failures: 
```
System.Xml.XmlException : System does not support 'Windows-1252' encoding.
```

Which will be real failures as soon as we start building VB projects.

### PR DESCRIPTION
**Pull request by cdmihai**
Fixes #306.

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
LGTM. Wasn't there a test that was disabled as part of this though? Or did that turn out to not be the case?

**Comment by cdmihai** [comment]
The test tried to parse multiple common targets, and the failing VB one was commented out: https://github.com/cdmihai/msbuild/blob/81e911cec108fa81a66f79963b3c621d98c7e347/src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs#L480-L481

I un-commented it.

**Comment by rainersigwald** [comment]
LGTM pending UT fixes and re-test.

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Pull request merged**
