### PR TITLE
RI vs15.7_sourcebuild to master

### PR DESCRIPTION
**Pull request by cdmihai**

### CODE REVIEW

**Comment by rainersigwald** [comment]
I'm ok with manual testing, I think.

@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
RHEL: same references-not-working thing https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/GenPRTest/job/innerloop_RHEL7.2_CoreCLR_SourceBuild_prtest/2/

**Comment by cdmihai** [comment]
I ran the windows tests locally and they pass. The windows full framework CI is failing with the expected reason of not having a nuget resolver to download the repotoolset sdk.

**Comment by rainersigwald** [comment]
Windows is working when it uses the right jobs, see details on https://github.com/Microsoft/msbuild/pull/3262

I say go ahead.

**Pull request merged**
