### PR TITLE
Don't call registry on non-Windows platforms.

### PR DESCRIPTION
**Pull request by mfilippov**

### CODE REVIEW

**Comment by rainersigwald** [comment]
Can you elaborate on what problems you ran into here? I suspect this is probably ok (at least for now) since we don't have MOTW detection on Mac at the moment, but I'm not _sure_ it's the right thing, and would like more details.

**Comment by mfilippov** [comment]
@rainersigwald I catch this problem on macOS when try to call resgen target. I think COM call in static ctor it is not a good idea. In other places of this class Native calls wrapped by platform check. Sorry for formatting changes I revert it.

**Comment by rainersigwald** [comment]
On the Mono runtime, or .NET Core?

**Comment by mfilippov** [comment]
On mono.

**Comment by radical** [comment]
Um this is what we have on mono - https://github.com/mono/msbuild/commit/fdf84d1ea9152b9e222ac3d7800c3d7d5c6f7368

**Comment by rainersigwald** [comment]
@radical I think I prefer this approach since it's a smaller change, aligning better with the `resgen.exe` code this is copypasta of. Would you be willing to take this and back out yours?

**Comment by rainersigwald** [comment]
> Though I think the commit message with the stack traces would be useful here.

Agreed; I'll pull that in when I merge this.

> Maybe add a comment for `allowMOTW` explaining it (allow/check dangerous resources?) or rename the field (self documenting :p)

This code originated in a different, closed-source internal project, and I tried to make minimal changes to it in case we need to pull a patch forward through that and up to the present. So I agree with this criticism but won't implement it, to keep the code like the internal stuff.

**Comment by rainersigwald** [comment]
Thanks, @mfilippov.

**Pull request merged**
