### PR TITLE
Roslyn-based code task factory

### PR DESCRIPTION
**Pull request by jeffkl**
Compiles an in-memory `netstandard2.0` assembly using `csc.exe` and loads the task.  This means it uses Roslyn compiler instead of CodeDom so it can be cross platform. 

I've implemented it to follow the same task XML as the existing `CodeTaskFactory` so that existing in-line tasks can move to it by changing the task factory name.  

```xml
<UsingTask  
    TaskName="DoNothing"  
    TaskFactory="RoslynCodeTaskFactory"  
    AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >  
    <ParameterGroup />  
    <Task>  
      <Reference Include="" />  
      <Using Namespace="" />  
      <Code Type="Fragment" Language="cs">  
      </Code>  
    </Task>  
  </UsingTask>  
```

There is concern that there might be a breaking change some where so I can't replace the existing `CodeTaskFactory`.  Users will need to opt-in to it.

I also need to update documentation so that its discoverable and deprecate my Roslyn-based code task factory.

Follow-up items:

- [ ] Update documentation (https://github.com/MicrosoftDocs/visualstudio-docs/issues/805)

### CODE REVIEW

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by cdmihai** [comment]
@dotnet-bot test RHEL7.2 Build for CoreCL please

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by jeffkl** [comment]
@dotnet-bot test this please

**Comment by jeffkl** [comment]
@jaredpar FYI I'm finally going to ship this as part of MSBuild since we're on NETStandard2.0.  We still have to ship ref assemblies `netstandard.dll` and `mscorlib.dll` but that's a lot less than before.

**Comment by AndyGerlicher** [comment]
Pushed a merge commit to resolve a conflict from DownloadFile

**Pull request merged**
