### PR TITLE
Ref asm bugfixes

### PR DESCRIPTION
**Pull request by rainersigwald**
These look like good places to use ref assemblies if present--but we need to track down owners for the various tools here and confirm that they're correct.

@jcouv

### CODE REVIEW

**Comment by rainersigwald** [comment]
Updated with a fix for #2165 and removal of the UpToDateCheckInputs items (which should be an extremely minor perf boost).

**Comment by rainersigwald** [comment]
Per conversation with @AndyGerlicher, we're going to postpone the non-GenerateResources part of this fix until we can confirm that using ref assemblies is correct with tool owners.

The risks are that if it's wrong, we might break all consumers of the winmdexp and lc targets. If we continue with the current state, reference assemblies are less effective in some scenarios. That seems like a good tradeoff at this stage of 15.3.

**Comment by jcouv** [comment]
Makes sense. Let's keep an open issue?

**Comment by rainersigwald** [comment]
@jcouv Already had the commit so I just opened #2181 to take the changes that I noticed when inspecting common.targets.

**Pull request merged**
