### PR TITLE
Update attribute can only appear in static items

### LINKED ISSUE #1618: Update construct seems to update all items regardless of match when run in target
``` XML
<Project>
  <ItemGroup>
     <X Include="A;B;C" />
     <X Update="B" Metadata="Just on B" />
     <X Update="NonExistent" Metadata="Useless" />
  </ItemGroup>

  <Target Name="Build">
    <Warning Text="Before in-target update: %(X.Identity) %(X.Metadata)" />
    
   <ItemGroup>
      <X Update="A" Metadata="Just on A" />
      <X Update="NonExistent" Metadata="Huh" />
   </ItemGroup>
      
   <Warning Text="After in-target update: %(X.Identity) %(X.Metadata)" />
 </Target>
</Project>
```

Expected after target runs:
* A has Metadata= "Just on A" and B has Metadata "Just on B", C has no Metadata=""

Actual:
* They all have Metadata="Huh"

```
C:\temp\test.proj(10,5): warning : Before in-target update: A
C:\temp\test.proj(10,5): warning : Before in-target update: B Just on B
C:\temp\test.proj(10,5): warning : Before in-target update: C
C:\temp\test.proj(17,4): warning : After in-target update: A Huh
C:\temp\test.proj(17,4): warning : After in-target update: B Huh
C:\temp\test.proj(17,4): warning : After in-target update: C Huh
```

@AndyGerlicher @rainersigwald

### PR DESCRIPTION
**Pull request by cdmihai**
Resolves #1618

### CODE REVIEW

**Comment by nguerrera** [comment]
Can we take this to ship room? I think we need this in RTW

**Comment by rainersigwald** [comment]
@nguerrera I don't think it meets the bar now, but we can bring it up in standup today.

**Comment by nguerrera** [comment]
Isn't it a now or never language change? Does bar sill have that. This feels like silent bad code gen equivalent for msbuild. It would be breaking to make it work as I expect if not an error now.

**Comment by nguerrera** [comment]
Also bragging to go from non error to error

**Comment by cdmihai** [comment]
Ideally, the _correct_ thing to do is to error now for RTW, to increase the user friendliness and debug-ability. And then, post RTW, allow Update for targets too. Along with everything else in #1124.

Prior to dev15, msbuild did have an `Update` only for dynamic items (items in targets). It works like this: #955. This is the code path that hits if you put an Update inside targets. The Update gets ignored and the old behaviour kicks in, which is equivalent to `<Compile Update="@(Compile)">`.

More details [here](https://msdn.microsoft.com/en-us/library/ms171453.aspx#BKMK_AttributesWithinTargets).

**Comment by nguerrera** [comment]
Agree on error now support later.

I'm aware of the existing target mechanism, but it is cumbersome. Could you guys look at my use case in the bug comment and let me know how to express it with just a condition?

**Comment by rainersigwald** [comment]
I was just surprised this didn't happen. Did we decide not to make this an error? Did we just miss shiproom? I don't remember at all :(

**Comment by cdmihai** [comment]
Same here, no idea what happened. My vague memory is ship-room miss-alignment. Should we bring the error back? Or just wait until we port Update to targets?

**Pull request closed without merging**
