### PR TITLE
Bootstrapped build in macOS CI job

### PR DESCRIPTION
**Pull request by rainersigwald**
@livarcocc do you recall if this was _intentionally_ different? Otherwise seems like it should match.

### CODE REVIEW

**Comment by livarcocc** [comment]
I think at the time I didn't think it was needed. I am fine with the change though. Better coverage.

**Comment by rainersigwald** [comment]
/azp run

(Making sure it still works)

**Comment by rainersigwald** [comment]
This is a test to see if I can put text _before_ the Pipelines keywords.

/azp run

**Pull request merged**
