### PR TITLE
more readable

### PR DESCRIPTION
**Pull request by callmekohei**
It's a little hard to read init-tool.sh.

So I think that it should be more readble.

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
I like this, but if you look at #2868 we're about to update our toolsets and change a lot of the way we're building, I don't think these changes will transfer easily :(. If you did want to commit off of that branch (which will go to master soon), that's something we would consider. Really do appreciate you taking the time to improve things. Hope some of this work can be saved.

**Comment by fbessho** [comment]
@AndyGerlicher I'm an outsider here but are you asking @callmekohei to merge his change to init-tool.sh to the `exp/update-toolset` branch?
When I check the branch, #2868 doesn't touch `init-tool.sh` so I think adding his change on this PR to the `exp/update-toolset` branch can be done easily.

I can see init-tools.*cmd* in `git diff` below but not init-tools.*sh*.
```
git diff --name-only origin/master..origin/exp/update-toolset | grep "init-tools"
init-tools.cmd
```

**Comment by rainersigwald** [comment]
`init-tools.sh` should no longer be used in the `exp/update-toolset` branch.  It should have been deleted like `init-tools.cmd` was. Thanks for noticing @fbessho.

@callmekohei Sorry, but since the script is obsoleted by that PR I don't think we should take this. I really appreciate the work, though--the changes are very nice!

**Comment by callmekohei** [comment]
Thank you (^_^)/

**Pull request closed without merging**
