### PR TITLE
Removing redundant contructors (empty is provided by default)

### PR DESCRIPTION
**Pull request by arthur-peka**
Those constructors seem to be totally unnecessary, as compiler generates empty ones by default

### CODE REVIEW

**Comment by dannyvv** [comment]
lgtm: :+1: 
Thanks, before we merge, would you mind squashing the 3 commits into one though?

**Comment by arthur-peka** [comment]
@dannyvv here you go

**Comment by dannyvv** [comment]
Lgtm: :+1: 
Thanks for doing so.

**Comment by AndyGerlicher** [comment]
LGTM, thanks!

**Pull request merged**
