### PR TITLE
Update dotnet CLI and build tools

### PR DESCRIPTION
**Pull request by jeffkl**
Dotnet CLI to 1.0.0-preview2-003131
Build tools to latest 1.0.26-prerelease-00822-03

### CODE REVIEW

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by jeffkl** [comment]
For some reason, this is failing to restore on Ubuntu.  I haven't been able to figure out why on my VM.

**Comment by jeffkl** [comment]
I ended up copying the dotnet CLI version from corefx and then updating init-tools from there as well.  Not sure how stable this version is though.

@eerhardt might know if this version is safe...

**Comment by jeffkl** [comment]
It's ironic that it works on Linux now but fails on OS X.  @rainersigwald could you please try this out when you get a chance?  I can't see the init-tools.log in our CI build right?

**Comment by eerhardt** [comment]
That CLI version is just as good as any pre-release version.  It is newer than the Preview2 we shipped in July.  But it isn't the absolute latest from our "master" branch.  Since CoreFX is using it, it should be fine for you.

**Comment by jeffkl** [comment]
Thanks Eric.

**Pull request merged**
