### PR TITLE
Revert "Disable GitVersioning in CI to work around #1409"

### PR DESCRIPTION
**Pull request by rainersigwald**
This reverts commit d83721a9b39c59d67a6c8721d93bae26b65c4eb5.

### CODE REVIEW

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for Desktop  please

**Comment by rainersigwald** [comment]
@jeffkl Uh, is it shallow fetching again?

**Comment by jeffkl** [comment]
It did in the first build but not in the second?  And the build definition is correct...
image

**Comment by rainersigwald** [comment]
@dotnet-bot test Windows_NT Build for Desktop please

**Comment by AndyGerlicher** [comment]
@mmitche It seems like the "Shallow clone" thing was turned on by default within the last week or so which breaks us. We need all history from the branch we're building to calculate our version number. I assume that will be still supported going forward? We turned it off but it seems to have broken again and now working again. Just wanted to give you a heads up in case it's something you're working on?

**Pull request merged**
