### PR TITLE
Restructure project folders

### LINKED ISSUE #1637: Restructure folders prior to branching for SDK selfhost
Move unit test folders up a level, rename folders to reflect current names (remove XMake).

I'm going to do a commit per folder.  Then do a commit that fixes all of the references.  Hopefully that will make Git happy...

### PR DESCRIPTION
**Pull request by jeffkl**
I did the folder and project renames in separate commits but one commit for fixing the project references.  I still need to test what the merge story is going to be like.

|  Old  | New  |
|---|---|
|  Framework\UnitTests  | Framework.UnitTests  |
| OrcasEngine\UnitTests  | Deprecated\Engine.UnitTests  |
| OrcasEngine  | Deprecated\Engine  |
| Engine\OrcasEngine.csproj  | Deprecated\Engine\Microsoft.Build.Engine.csproj  |
| Engine.UnitTests\OrcasEngineUnitTests.csproj  | Deprecated\Engine.UnitTests\Microsoft.Build.Engine.UnitTests.csproj  |
| Utilities\UnitTests  | Utilities.UnitTests  |
| XMakeBuildEngine\UnitTests  | Build.UnitTests  |
| XMakeBuildEngine  | Build  |
| XMakeCommandLine\UnitTests  | MSBuild.UnitTests  |
| XMakeCommandLine\MSBuildTaskHost  | MSBuildTaskHost  |
| XMakeCommandLine  | MSBuild  |
| XMakeConversion\UnitTests  | Deprecated\Conversion.UnitTests  |
| Deprecated\Conversion\XMakeConversion.csproj  | Deprecated\Conversion\Microsof.Build.Conversion.csproj  |
| XMakeTasks\UnitTests  | Tasks.UnitTests  |
| XMakeTasks\XMakeTasksUnitTests  | Tasks.UnitTests2  |
| XMakeTasks | Tasks |

Closes #1637

### CODE REVIEW

**Comment by jeffkl** [comment]
I have fixed `MSBuild.sln`!

**Comment by AndyGerlicher** [comment]
Talked with Jeff. Will move `Engine` and `Conversion` to `Deprecated\Engine` and `Deprecated\Conversion`

**Comment by jeffkl** [comment]
I have moved Microsoft.Build.Engine and Microsoft.Build.Conversion to a Deprecated folder.

I also changed the commits to be as dotnet-bot.

**Comment by jeffkl** [comment]
@dotnet-bot test Windows_NT Build for Desktop please

**Pull request merged**
