### PR TITLE
Fix TrackedDependenciesTests on mac ..

### PR DESCRIPTION
**Pull request by radical**
.. by fixing changing paths like "foo\\bar" to Path.Combine("foo", "bar"). And fixing it to work on systems which don't support <1sec file time information, like mac.

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
Do you know why the diff doesn't display? "1,200 additions and 1,199 deletions", is that right? Or any idea what went wrong?

**Comment by radical** [comment]
I think it doesn't display it because the commit content is too big. You can see it with command line git though. Here is a gist of that commit: https://gist.github.com/radical/c3187c3ac9ec91483353 . 

All the changes in this are, as mentioned in the commit message, essentially - change "foo\\bar" to Path.Combine("foo", "bar").

There was a change in the earlier commit that broke a test windows, so, I have removed that and updated the PR.

**Comment by AndyGerlicher** [comment]
I just ended up downloading the files and diffing them locally. Looks good though, thanks for doing that (there were a lot of paths to fix!!).

**Comment by jasonwilliams200OK** [comment]
@radical if you rename `gistfile1.txt` to `gistfile1.diff` it will even syntax highlight the diff in the gist link. 

Similar to how `diff` works here in markdown comments, when code content is wrapped between ```` ```diff ```` and ```` ``` ````, like so:

```diff
diff --git a/src/Utilities/UnitTests/TrackedDependencies/TrackedDependenciesTests.cs b/src/Utilities/UnitTests/TrackedDependencies/TrackedDependenciesTests.cs
index 052b580..e98273f 100644
--- a/src/Utilities/UnitTests/TrackedDependencies/TrackedDependenciesTests.cs
+++ b/src/Utilities/UnitTests/TrackedDependencies/TrackedDependenciesTests.cs
@@ -312,27 +312,27 @@ namespace Microsoft.Build.UnitTests.TrackedDependencies
         {
             Console.WriteLine("Test: SingleCanonicalCL");
             // Prepare files
-            DependencyTestHelper.WriteAll("TestFiles\\one.h", "");
-            DependencyTestHelper.WriteAll("TestFiles\\one.cpp", "");
-            DependencyTestHelper.WriteAll("TestFiles\\one.obj", "");
+            DependencyTestHelper.WriteAll(Path.Combine("TestFiles", "one.h"), "");
+            DependencyTestHelper.WriteAll(Path.Combine("TestFiles", "one.cpp"), "");
+            DependencyTestHelper.WriteAll(Path.Combine("TestFiles", "one.obj"), "");
````

**Comment by jasonwilliams200OK** [comment]
@radical, it is advised in many many repos on GitHub that never to leave the description box in both PRs and Issues empty. In some repos such as joyent/node, they don't even accept any PR without proper description and docs. Moreover, they have standard format for [writing the commit message](https://github.com/joyent/node/blob/master/CONTRIBUTING.md#commit), which is reflected in their [commit history](https://github.com/joyent/node/commits/master).
Your made a gigantic amount of changes in one file, it deserves (at least) few lines of explanation on what you fixed, how you fixed it and why it was necessary; for future reference.
That being said, it is never too late, you can still edit the first comment on this page and also commit message using `git commit --amend`, edit message and then `git push -f`.

**Comment by radical** [comment]
@jasonwilliams200OK I thought I had selected 'diff' as the Language while creating the gist. My bad! Thanks for the suggestion about the triple quotes.

The actual commits have the relevant info about them:
```
[tests] Workaround for file time information having >=1s resolution
TrackingDependenciesTests depend on comparing time difference between
creation of files, and it expects 100ms resolution. On windows,
GetFileAttributesEx is used to obtain this, but on mono/mac, we get
1s resolution from the File.GetLastWriteFileUtc(..) api.

This is a workaround to use 1s time delay on !Windows.

A bug has been filed for mono:
https://bugzilla.xamarin.com/show_bug.cgi?id=30083
```

And ..

```
[tests] Fix TrackedDependenciesTests/mac by using Path.Combine instead of ..

.. hardcoded path separators like "foo\\bar".
```

Did you mean that I should add more info to the second(bigger) commit or were you talking about copy/pasting this in the merge commit (first PR comment) ?

Assuming the former, I have improved it to:

```
    [tests] Fix TrackedDependenciesTests/mac by using Path.Combine ..

    instead of hardcoded path separators like "foo\\bar". These paths are
    being used while writing entries to the .tlog files and for creating
    dependent files for the various tests. This breaks on Unix, so, use
    Path.Combine to construct the paths.
```

**Comment by jasonwilliams200OK** [comment]
:+1: 
I was talking about first comment https://github.com/Microsoft/msbuild/pull/101#issue-76835388 which is empty.

**Comment by radical** [comment]
Fixed.

**Pull request merged**
