### PR TITLE
Remove prerelease tag from MSBuild 14 packages

### PR DESCRIPTION
**Pull request by jeffkl**
I will publish them to NuGet.org and MyGet unless anyone objects...

### CODE REVIEW

**Comment by rainersigwald** [comment]
:shipit:

**Comment by AndyGerlicher** [comment]
LGTM

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for Desktop please

**Comment by jeffkl** [comment]
I have pushed the packages to your MyGet feed as well as NuGet.org... We're live!

**Pull request merged**
