### PR TITLE
RI vs15.7

### PR DESCRIPTION
**Pull request by rainersigwald**

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
Any idea whe readonly xml change shows up in the diff? That was a port of a commit already in master.

**Comment by rainersigwald** [comment]
The diff view on the website shows HEAD versus merge-base: the changes in the source branch relative to where it diverged from the destination branch. When there are cherry-picks like here that can be a bit misleading.

You can look at the diff between what the branch currently is and what the branch would be after merge by fetching a special ref.

```
git fetch Microsoft pull/3164/merge:merged-3164

git diff -b Microsoft/master..merged-3164
```

```diff
diff --git a/src/Build/BackEnd/BuildManager/BuildParameters.cs b/src/Build/BackEnd/BuildManager/BuildParameters.cs
index 4fd688bcb..11293faf2 100644
--- a/src/Build/BackEnd/BuildManager/BuildParameters.cs
+++ b/src/Build/BackEnd/BuildManager/BuildParameters.cs
@@ -124,7 +124,11 @@ namespace Microsoft.Build.Execution
         /// By default, it is enabled.
         /// </summary>
 #if FEATURE_NODE_REUSE
-        private bool _enableNodeReuse = true;
+        /// <remarks>
+        /// Enable node reuse by default only on Windows for now
+        /// due to https://github.com/Microsoft/msbuild/issues/3161
+        /// </remarks>
+        private bool _enableNodeReuse = NativeMethodsShared.IsWindows;
 #else
         private bool _enableNodeReuse = false;
 #endif
diff --git a/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs b/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs
index f06f656f9..c22a93741 100644
--- a/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs
+++ b/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs
@@ -177,7 +177,13 @@ namespace Microsoft.Build.BackEnd
         /// </summary>
         public void ShutdownAllNodes()
         {
-            ShutdownAllNodes(NodeProviderOutOfProc.GetHostHandshake(ComponentHost.BuildParameters.EnableNodeReuse), NodeProviderOutOfProc.GetClientHandshake(), NodeContextTerminated);
+            // if no BuildParameters were specified for this build,
+            // we must be trying to shut down idle nodes from some
+            // other, completed build. If they're still around,
+            // they must have been started with node reuse.
+            bool nodeReuse = ComponentHost.BuildParameters?.EnableNodeReuse ?? true;
+
+            ShutdownAllNodes(NodeProviderOutOfProc.GetHostHandshake(nodeReuse), NodeProviderOutOfProc.GetClientHandshake(), NodeContextTerminated);
         }
 
         #endregion
diff --git a/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs b/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
index cab8c225f..0fcd76d3a 100644
--- a/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
+++ b/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
@@ -115,16 +115,7 @@ namespace Microsoft.Build.BackEnd
             // INodePacketFactory
             INodePacketFactory factory = new NodePacketFactory();
 
-            // Find proper msbuild executable name
-            string msbuildExeName = Environment.GetEnvironmentVariable("MSBUILD_EXE_NAME");
-
-            if (String.IsNullOrEmpty(msbuildExeName))
-            {
-                msbuildExeName = "MSBuild.exe";
-            }
-
-            // Search for all instances of the msbuild process and create a list of them
-            List<Process> nodeProcesses = new List<Process>(Process.GetProcessesByName(Path.GetFileNameWithoutExtension(msbuildExeName)));
+            List<Process> nodeProcesses = GetPossibleRunningNodes();
 
             // Find proper MSBuildTaskHost executable name
             string msbuildtaskhostExeName = NodeProviderOutOfProcTaskHost.TaskHostNameForClr2TaskHost;
@@ -180,12 +171,10 @@ namespace Microsoft.Build.BackEnd
                 }
             }
 
-            if (String.IsNullOrEmpty(msbuildLocation))
-            {
-                msbuildLocation = "MSBuild.exe";
-            }
-
 #if FEATURE_NODE_REUSE
+            // Try to connect to idle nodes if node reuse is enabled.
+            if (_componentHost.BuildParameters.EnableNodeReuse)
+            {
                 var candidateProcesses = GetPossibleRunningNodes(msbuildLocation);
 
                 CommunicationsUtilities.Trace("Attempting to connect to each existing msbuild.exe process in turn to establish node {0}...", nodeId);
@@ -215,6 +204,7 @@ namespace Microsoft.Build.BackEnd
                         return new NodeContext(nodeId, nodeProcess.Id, nodeStream, factory, terminateNode);
                     }
                 }
+            }
 #endif
 
             // None of the processes we tried to connect to allowed a connection, so create a new one.
@@ -290,8 +280,13 @@ namespace Microsoft.Build.BackEnd
             return null;
         }
 
-        private List<Process> GetPossibleRunningNodes(string msbuildLocation)
+        private List<Process> GetPossibleRunningNodes(string msbuildLocation = null)
         {
+            if (String.IsNullOrEmpty(msbuildLocation))
+            {
+                msbuildLocation = "MSBuild.exe";
+            }
+
             var expectedProcessName = Path.GetFileNameWithoutExtension(GetCurrentHost() ?? msbuildLocation);
 
             List<Process> nodeProcesses = new List<Process>(Process.GetProcessesByName(expectedProcessName));
@@ -604,17 +599,26 @@ namespace Microsoft.Build.BackEnd
             }
         }
 
+#if RUNTIME_TYPE_NETCORE
+        private static string CurrentHost;
+#endif
+
         /// <summary>
-        /// Identify the .NET host of the current process
+        /// Identify the .NET host of the current process.
         /// </summary>
         /// <returns>The full path to the executable hosting the current process, or null if running on Full Framework on Windows.</returns>
         private static string GetCurrentHost()
         {
 #if RUNTIME_TYPE_NETCORE
+            if (CurrentHost == null)
+            {
                 using (Process currentProcess = Process.GetCurrentProcess())
                 {
-                return currentProcess.MainModule.FileName;
+                    CurrentHost = currentProcess.MainModule.FileName;
                 }
+            }
+
+            return CurrentHost;
 #else
             return null;
 #endif
diff --git a/src/MSBuild/XMake.cs b/src/MSBuild/XMake.cs
index eaf17e4ad..a9c323ac3 100644
--- a/src/MSBuild/XMake.cs
+++ b/src/MSBuild/XMake.cs
@@ -545,7 +545,7 @@ namespace Microsoft.Build.CommandLine
 #endif
                 int cpuCount = 1;
 #if FEATURE_NODE_REUSE
-                bool enableNodeReuse = true;
+                bool enableNodeReuse = NativeMethodsShared.IsWindows;
 #else
                 bool enableNodeReuse = false;
 #endif
@@ -2110,7 +2110,7 @@ namespace Microsoft.Build.CommandLine
         {
             bool enableNodeReuse;
 #if FEATURE_NODE_REUSE
-            enableNodeReuse = true;
+            enableNodeReuse = NativeMethodsShared.IsWindows;
 #else
             enableNodeReuse = false;
 #endif
diff --git a/version.json b/version.json
index 315c0cf88..07f7b0cc2 100644
--- a/version.json
+++ b/version.json
@@ -1,6 +1,7 @@
 {
   "version": "15.8-preview",
   "assemblyVersion": "15.1",
+  "buildNumberOffset": "10",
   "cloudBuild": {
     "buildNumber": {
       "enabled": true,
```

**Comment by rainersigwald** [comment]
^ and that pointed out to me that we need to specially merge the `version.json` file. I'm going to close this PR and open another.

**Comment by rainersigwald** [comment]
Replaced by #3168.

**Pull request closed without merging**
