### PR TITLE
LOC CHECKIN | Microsoft/msbuild vs16.1 20190502

### PR DESCRIPTION
**Pull request by v-mdriml**

### CODE REVIEW

**Comment by Pilchie** [comment]
Thanks for the heads up - let's get it inserted soon.

**Comment by tmeschter** [comment]
This should be the last set of loc changes for 16.1.

**Comment by rainersigwald** [comment]
Insertion will be gated on some coordination with @rrelyea due to the setup-authoring changes, but I'll get a build ready for that ASAP.

**Comment by tmeschter** [comment]
@rainersigwald @Pilchie Hold off for the moment. The PR actually _reset_ the translation of an item that hadn't been changed. :-( I'm going to fix it up manually, and I'll have a PR in an hour or less.

**Pull request merged**
