### PR TITLE
Use IEnumerable.OfType<T>() instead of our custom FilteringEnumerable

### PR DESCRIPTION
**Pull request by jeffkl**
Pending perf tests, this is just a house cleaning change.

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
### DesignTimeBuild Time (ms) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | ::ok_hand: | no | 43.8337 -> 43.7396 (-0.215%)
DotnetWebProject | ::ok_hand: | no | 268.9995 -> 267.1239 (-0.697%)
DotnetMvcProject | ::ok_hand: | no | 282.212 -> 276.6302 (-1.978%)
Picasso | :white_check_mark: | yes | 1687.832 -> 1685.1742 (-0.157%)
SmallP2POldCsproj | :white_check_mark: | yes | 70.4401 -> 70.2767 (-0.232%)
SmallP2PNewCsproj | :white_check_mark: | yes | 739.5356 -> 734.9211 (-0.624%)
OrchardCore | ::ok_hand: | no | 55305.2112 -> 55290.0058 (-0.027%)
WebLargeCore | ::ok_hand: | no | 61761.5003 -> 60845.5196 (-1.483%)

### DesignTimeBuild Memory (bytes) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :ok_hand: | no | 2359210 -> 2370211 (0.466%)
DotnetWebProject | ::ok_hand: | no | 14481805 -> 14463887 (-0.124%)
DotnetMvcProject | ::ok_hand: | no | 14663465 -> 14602628 (-0.415%)
Picasso | :red_circle: | yes | 92007996 -> 93410964 (1.525%)
SmallP2POldCsproj | :red_circle: | yes | 8582042 -> 8591854 (0.114%)
SmallP2PNewCsproj | ::ok_hand: | no | 44039557 -> 44003807 (-0.081%)
OrchardCore | ::ok_hand: | no | 1368461538 -> 1364236650 (-0.309%)
WebLargeCore | :ok_hand: | no | 1387455770 -> 1395609089 (0.588%)

### ParallelEvaluationIsolatedContext Time (ms) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 42.8325 -> 42.9404 (0.252%)
DotnetWebProject | :white_check_mark: | yes | 58.513 -> 58.2224 (-0.497%)
DotnetMvcProject | :white_check_mark: | yes | 64.6671 -> 64.1601 (-0.784%)
Picasso | :red_circle: | yes | 166.6183 -> 170.5036 (2.332%)
SmallP2POldCsproj | ::ok_hand: | no | 36.027 -> 36.021 (-0.017%)
SmallP2PNewCsproj | :red_circle: | yes | 104.1449 -> 105.8923 (1.678%)
Generated_100_100_v150 | ::ok_hand: | no | 666.6613 -> 665.1035 (-0.234%)
OrchardCore | :red_circle: | yes | 1164.3796 -> 1172.3574 (0.685%)
Roslyn | :ok_hand: | no | 1487.1185 -> 1487.7418 (0.042%)
WebLargeCore | ::ok_hand: | no | 1381.0328 -> 1363.1702 (-1.293%)

### ParallelEvaluationIsolatedContext Memory (bytes) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 2963786 -> 2979887 (0.543%)
DotnetWebProject | :red_circle: | yes | 4906613 -> 4914553 (0.162%)
DotnetMvcProject | :red_circle: | yes | 5615577 -> 5631243 (0.279%)
Picasso | :white_check_mark: | yes | 12292560 -> 11466634 (-6.719%)
SmallP2POldCsproj | :red_circle: | yes | 4510033 -> 4556669 (1.034%)
SmallP2PNewCsproj | :white_check_mark: | yes | 8952568 -> 8492546 (-5.138%)
Generated_100_100_v150 | ::ok_hand: | no | 35069123 -> 34617202 (-1.289%)
OrchardCore | :white_check_mark: | yes | 62244991 -> 59974768 (-3.647%)
Roslyn | ::ok_hand: | no | 89942456 -> 89838136 (-0.116%)
WebLargeCore | ::ok_hand: | no | 66043258 -> 64957124 (-1.645%)

### ParallelEvaluationSharedContext Time (ms) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :ok_hand: | no | 42.6076 -> 42.6497 (0.099%)
DotnetWebProject | :white_check_mark: | yes | 59.3196 -> 58.245 (-1.812%)
DotnetMvcProject | :white_check_mark: | yes | 64.1874 -> 64.0786 (-0.17%)
Picasso | :ok_hand: | no | 167.1091 -> 168.2164 (0.663%)
SmallP2POldCsproj | :white_check_mark: | yes | 36.0412 -> 35.8972 (-0.4%)
SmallP2PNewCsproj | :red_circle: | yes | 101.3541 -> 102.5154 (1.146%)
Generated_100_100_v150 | ::ok_hand: | no | 670.4678 -> 668.8891 (-0.235%)
OrchardCore | ::ok_hand: | no | 1141.9433 -> 1133.8918 (-0.705%)
Roslyn | :white_check_mark: | yes | 1469.8064 -> 1464.5626 (-0.357%)
WebLargeCore | :white_check_mark: | yes | 1366.4014 -> 1343.1563 (-1.701%)

### ParallelEvaluationSharedContext Memory (bytes) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 2962126 -> 2978616 (0.557%)
DotnetWebProject | :red_circle: | yes | 4903961 -> 4913595 (0.196%)
DotnetMvcProject | :red_circle: | yes | 5615599 -> 5628338 (0.227%)
Picasso | ::ok_hand: | no | 11786965 -> 11549084 (-2.018%)
SmallP2POldCsproj | :red_circle: | yes | 4504528 -> 4545448 (0.908%)
SmallP2PNewCsproj | :white_check_mark: | yes | 9399067 -> 9000883 (-4.236%)
Generated_100_100_v150 | :ok_hand: | no | 34156569 -> 34165922 (0.027%)
OrchardCore | :ok_hand: | no | 61567442 -> 62095978 (0.858%)
Roslyn | ::ok_hand: | no | 87714233 -> 87092985 (-0.708%)
WebLargeCore | ::ok_hand: | no | 65172899 -> 63262955 (-2.931%)

### SerialEvaluationIsolatedContext Time (ms) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | ::ok_hand: | no | 36.5907 -> 36.5567 (-0.093%)
DotnetWebProject | :white_check_mark: | yes | 59.2669 -> 58.9577 (-0.522%)
DotnetMvcProject | :white_check_mark: | yes | 66.3517 -> 65.0102 (-2.022%)
Picasso | :ok_hand: | no | 343.7562 -> 343.9631 (0.06%)
SmallP2POldCsproj | :red_circle: | yes | 61.0035 -> 61.2373 (0.383%)
SmallP2PNewCsproj | :white_check_mark: | yes | 245.4488 -> 243.4628 (-0.809%)
Generated_100_100_v150 | :white_check_mark: | yes | 1725.4442 -> 1709.4072 (-0.929%)
OrchardCore | :white_check_mark: | yes | 3493.0035 -> 3481.9168 (-0.317%)
Roslyn | :red_circle: | yes | 4101.5662 -> 4116.0184 (0.352%)
WebLargeCore | :white_check_mark: | yes | 3965.4109 -> 3935.8071 (-0.747%)

### SerialEvaluationIsolatedContext Memory (bytes) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | ::ok_hand: | no | 5566289 -> 5554852 (-0.205%)
DotnetWebProject | :red_circle: | yes | 3936924 -> 3949575 (0.321%)
DotnetMvcProject | :ok_hand: | no | 4564200 -> 4566168 (0.043%)
Picasso | :ok_hand: | no | 13509692 -> 13588030 (0.58%)
SmallP2POldCsproj | :red_circle: | yes | 3196442 -> 3282264 (2.685%)
SmallP2PNewCsproj | :red_circle: | yes | 8300550 -> 8471315 (2.057%)
Generated_100_100_v150 | :red_circle: | yes | 33721610 -> 34389887 (1.982%)
OrchardCore | :ok_hand: | no | 58977864 -> 59354223 (0.638%)
Roslyn | :ok_hand: | no | 83386415 -> 83591781 (0.246%)
WebLargeCore | :red_circle: | yes | 57747665 -> 59592768 (3.195%)

### SerialEvaluationSharedContextSecondRun Time (ms) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 34.3754 -> 34.5525 (0.515%)
DotnetWebProject | :white_check_mark: | yes | 62.796 -> 61.1383 (-2.64%)
DotnetMvcProject | :white_check_mark: | yes | 64.9902 -> 64.8147 (-0.27%)
Picasso | :white_check_mark: | yes | 345.9733 -> 344.8161 (-0.334%)
SmallP2POldCsproj | :ok_hand: | no | 63.6201 -> 63.6385 (0.029%)
SmallP2PNewCsproj | :red_circle: | yes | 232.5926 -> 235.0381 (1.051%)
Generated_100_100_v150 | :red_circle: | yes | 1668.4954 -> 1679.3891 (0.653%)
OrchardCore | :red_circle: | yes | 3352.0103 -> 3369.3539 (0.517%)
Roslyn | ::ok_hand: | no | 4027.596 -> 4011.0522 (-0.411%)
WebLargeCore | :white_check_mark: | yes | 3743.5299 -> 3695.9207 (-1.272%)

### SerialEvaluationSharedContextSecondRun Memory (bytes) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 5697737 -> 5706882 (0.161%)
DotnetWebProject | :red_circle: | yes | 4076939 -> 4088656 (0.287%)
DotnetMvcProject | :red_circle: | yes | 4824435 -> 4835049 (0.22%)
Picasso | :red_circle: | yes | 14258525 -> 14643377 (2.699%)
SmallP2POldCsproj | :red_circle: | yes | 3322090 -> 3367149 (1.356%)
SmallP2PNewCsproj | :white_check_mark: | yes | 7440345 -> 7220240 (-2.958%)
Generated_100_100_v150 | :white_check_mark: | yes | 33601724 -> 33492497 (-0.325%)
OrchardCore | :white_check_mark: | yes | 59414788 -> 58210940 (-2.026%)
Roslyn | :ok_hand: | no | 85259142 -> 85619597 (0.423%)
WebLargeCore | ::ok_hand: | no | 59604168 -> 59437296 (-0.28%)

### SerialEvaluationSharedContext Time (ms) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 42.8386 -> 43.1142 (0.643%)
DotnetWebProject | :white_check_mark: | yes | 58.9337 -> 57.858 (-1.825%)
DotnetMvcProject | ::ok_hand: | no | 63.7064 -> 63.6908 (-0.024%)
Picasso | :red_circle: | yes | 343.9449 -> 345.4045 (0.424%)
SmallP2POldCsproj | ::ok_hand: | no | 60.2721 -> 60.2506 (-0.036%)
SmallP2PNewCsproj | :red_circle: | yes | 230.4977 -> 231.6766 (0.511%)
Generated_100_100_v150 | :red_circle: | yes | 1694.8413 -> 1702.0312 (0.424%)
OrchardCore | :red_circle: | yes | 3379.7755 -> 3399.3384 (0.579%)
Roslyn | ::ok_hand: | no | 4041.225 -> 4037.7023 (-0.087%)
WebLargeCore | :white_check_mark: | yes | 3780.5122 -> 3730.4674 (-1.324%)

### SerialEvaluationSharedContext Memory (bytes) (src\msbuild.A vs src\msbuild.B)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 2962095 -> 2978606 (0.557%)
DotnetWebProject | :red_circle: | yes | 4903849 -> 4912994 (0.186%)
DotnetMvcProject | :red_circle: | yes | 5613815 -> 5628687 (0.265%)
Picasso | :red_circle: | yes | 10191488 -> 10304573 (1.11%)
SmallP2POldCsproj | :red_circle: | yes | 4266001 -> 4298566 (0.763%)
SmallP2PNewCsproj | :red_circle: | yes | 8162302 -> 8509865 (4.258%)
Generated_100_100_v150 | :red_circle: | yes | 33532074 -> 34238682 (2.107%)
OrchardCore | ::ok_hand: | no | 58838624 -> 58262142 (-0.98%)
Roslyn | ::ok_hand: | no | 83669404 -> 83613410 (-0.067%)
WebLargeCore | :red_circle: | yes | 58226523 -> 60180343 (3.356%)

**Comment by jeffkl** [comment]
@davkean I was wondering if you had any insight on how to make this code path allocate less?  Is our `FilteringEnumerable<T>` better than `OfType<T>`?

**Comment by davkean** [comment]
It will be a wash; I don't think it will reduce or increase allocations. Removing those ReadOnlyCollection allocations, however...

**Comment by jeffkl** [comment]
@AndyGerlicher please merge or close 😃

**Pull request merged**
