### PR TITLE
Detect shared projects when parsing solution files

### LINKED ISSUE #3183: Request: Expose whether a project is a shared project in SolutionFile
When using the solution file parser, it would be convenient if shared projects were given a special value in the `SolutionProjectType` enum (rather than just `Unknown`). This would make it easier to skip shared projects when processing a solution.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #3183

### CODE REVIEW

**Comment by DustinCampbell** [comment]
> I wish our parser wasn't the one to use for this but since it is . . .

I agree. It'd be great if there were a solution-parsing API available that wasn't so tied to the semantics of what MSBuild needs to build. Getting to that's on my list someday. :smile:

**Comment by DustinCampbell** [comment]
The RHEL7.2 failure does not look related to my change. @rainersigwald : Is this a known failure?

**Comment by cdmihai** [comment]
@dotnet-bot test RHEL7.2 Build for CoreCLR please

**Comment by rainersigwald** [comment]
@cdmihai has it ever passed? the current history is all red :(

**Comment by cdmihai** [comment]
@DustinCampbell probably unrelated. I restarted it. If it fails again we can just ignore it, since I don't see how your changes could cause that.

**Comment by DustinCampbell** [comment]
@cdmihai: FWIW, I'd already kicked it a few times directly on Jenkins. Looks like this one might be failing in general.

**Comment by DustinCampbell** [comment]
Feel free to merge when everyone is comfortable with this. I don't have write access.

**Comment by rainersigwald** [comment]
Thanks @DustinCampbell!

**Pull request merged**
