### PR TITLE
Publish darc

### PR DESCRIPTION
**Pull request by chcosta**
@livarcocc 

I assume .vsts-dotnet.yml is only for internal builds.

Validation build is in progress - https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2314166
I had to create a different build definition because I didn't have permissions to push to Microsoft/msbuild (I could only push to my fork), as a result, I wasn't able to validate that I haven't broken signing but I think it should be fine.

### CODE REVIEW

**Comment by chcosta** [comment]
validation build failed with this error

```
E:\A\_work\338\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19052.1\tools\Publish.proj(161,5): error MSB4044: The "PublishSymbols" task was not given a value for the required parameter "PersonalAccessToken".
```

I'll figure out what I did to break this.

**Comment by chcosta** [comment]
This validation job looks like it published correctly - https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2314265

**Comment by chcosta** [comment]
I don't have permissions to merge this repo, @livarcocc, can you handle merging this?

**Comment by rainersigwald** [comment]
Looks like CI is now failing with

```

Job Windows_NT: Variable group Publish-Build-Assets could not be found. The variable group does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz

Job Asset_Registry_Publish: Variable group Publish-Build-Assets could not be found. The variable group does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz
```

**Comment by chcosta** [comment]
DevDiv doesn't auto-authorize the build definitions.  I reauthorized it and the build is currently in progress.  Sorry about not calling that out specifically.  I'd almost forgotten about how annoying that is.  Almost..

**Comment by rainersigwald** [comment]
I understand some of those words! Is there a for-dummies version you can link to or a quick step-by-step description of what you did, in case this happens again in the future?

**Comment by chcosta** [comment]
Haha, this is the nonsense I was talking about - https://github.com/dotnet/arcade/blob/master/Documentation/AzureDevOps/AzureDevOpsOnboarding.md#resource-authorization

It's a really poor experience and super annoying, and in dnceng we have a better experience than what remains in the devdiv azure DEVOPS account.

**Pull request merged**
