### PR TITLE
Remove netcoreap20

### PR DESCRIPTION
**Pull request by cdmihai**

### CODE REVIEW

**Comment by cdmihai** [comment]
Here's me thinking that deleting the tfm will just work. :)

**Comment by cdmihai** [comment]
@crummel, does this break any sourcebuild scenarios?

**Comment by crummel** [comment]
@cdmihai This should be fine for source-build.  We should be on at least netcoreapp2.1 for everything consuming MSBuild.  I'll try it out but no need to hold it up on our account.

**Comment by joeltankam** [comment]
@AndyGerlicher can you please explain why it was necessary to remove .NET Standard 2.0 targeting (d351690) ? 
Now libraries (not applications) referencing `Microsoft.Build` can no longer target .NET Standard, which is inconvenient.

**Comment by AndyGerlicher** [comment]
I don't really remember the details, but I'm pretty sure that Microsoft.Build.dll uses APIs that are not available in all implementations of netstandard2.0. I think we're in agreement here that it is inconvenient, but I don't believe that it can be resolved without breaking changes.

**Comment by dsplaisted** [comment]
@joeltankam The reason was that it's not generally possible to create working .NET Standard build tasks.  There are lots of APIs (System.Reflection.Metadata, System.Collections.Immutable, System.Text.Json) where build tasks that use those APIs need to include the implementations, and the implementations are different for .NET Core and .NET Framework.  So compiling an MSBuild task for .NET Standard doesn't help if you need to ship different dependencies for .NET Core and .NET Framework.

**Comment by joeltankam** [comment]
@AndyGerlicher @dsplaisted Thank you.

**Pull request merged**
