### PR TITLE
Support process trees with both 32- and 64-bit processes in FileTracker

### PR DESCRIPTION
**Pull request by rainersigwald**
:memo: This is destined for the Update 3 branch. I'll merge to master in another PR after it's in there.

This ports internal changes made to support an update to `Tracker.exe` and `FileTracker.dll` that allows them to support a process tree that has mixed 64-bit and 32-bit processes.

These changes will not work without a build of Update 3 installed, because Tracker and FileTracker are built inside the Microsoft firewall and not publicly available. Filed #649 to track making them available. The tests can also be re-enabled by making Update 3 a requirement to build on Windows (once it exists outside the firewall).

### CODE REVIEW

**Comment by cdmihai** [comment]
LGTM. Curious why the mysterious test fail

**Comment by rainersigwald** [comment]
@dotnet-bot test Windows_NT Build please

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build please

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Pull request merged**
