### PR TITLE
Nuked ThreadingUtilities.cs

### PR DESCRIPTION
**Pull request by khellang**
This file does *not* compile and is clearly not used anywhere :confused:

### CODE REVIEW

**Comment by akoeplinger** [comment]
Corresponding issue: https://github.com/Microsoft/msbuild/issues/4

**Comment by dannyvv** [comment]
lgtm: :+1:

**Comment by AndyGerlicher** [comment]
LGTM!

**Comment by knocte** [comment]
I suggest that the *why* is kept in commit messages as well as PullRequest descriptions. Otherwise people looking at git history will not understand some changes.

**Comment by khellang** [comment]
@knocte If you want everyone to understand *all* changes done to a project, I don't think it's enough with commit messages. The PR clearly states why.

**Comment by akoeplinger** [comment]
@khellang sure, but if I'm looking at this commit from something else than github, I don't get the link to the PR it comes from. Putting the description into the commit message helps there.

**Comment by knocte** [comment]
Exactly, there's a link from the PR to the commit, but not the other way around.

**Comment by akoeplinger** [comment]
@knocte just FYI, GitHub actually links to the PR from the commit:

PR Link

**Comment by khellang** [comment]
GitHub *does* link to the PR, and there's a merge commit in the history that has a link to it.



It even shows from forks:



Here's the merge commit: https://github.com/Microsoft/msbuild/commit/e96e44d213c33e2aaf33f5f3bcdbc74048c29039

**Comment by knocte** [comment]
> I'm not saying that commits shouldn't have the why included, but it's too late for me to do anything about it now.

I know, I'm just advicing for next commits.

> @knocte just FYI, GitHub actually links to the PR from the commit

Github yes, but not git. Sometimes I use gitk to examine history, for example, as it's way faster.

**Pull request merged**
