### PR TITLE
More user friendly SDK error message

### PR DESCRIPTION
**Pull request by cdmihai**
It was hard to debug the problem so I added more context to the error message.

### CODE REVIEW

**Comment by rainersigwald** [comment]
LGTM

**Comment by ValMenn** [comment]
The change looks good, but I have a concern -- unrelated to the actual change. The error should be Windows-specific. Well, I can make the change later. Otherwise, looks good.

**Comment by AndyGerlicher** [comment]
LGTM

**Comment by cdmihai** [comment]
@ValMenn I agree, this is Windows specific. And if we want to have an applocal msbuild it would be best to get rid of the dependency anyway, regardless of the OS.

**Pull request merged**
