### PR TITLE
#439 - Removed usage "Microsoft.Win32.Registry" from project.json.

### PR DESCRIPTION
**Pull request by heXelium**
As advertised just removed usage of "Microsoft.Win32.Registry" from ...\msbuild\src\Utilities\project.json and ...\msbuild\src\XMakeTasks\project.json (#439).

### CODE REVIEW

**Comment by rainersigwald** [comment]
Seems like a good step, but `Microsoft.Win32.Registry` is used in several other `project.json`s. Is there a reason this is a subset?

**Comment by heXelium** [comment]
Heh, you are right. I did solution wide search but it did not return all results on first search for some reason. Removing it from other ```project.json```'s.

**Comment by rainersigwald** [comment]
Thanks! LGTM

**Comment by AndyGerlicher** [comment]
LGTM as well. Can you please squash into a single commit though?

**Comment by heXelium** [comment]
Sure. Done.

**Pull request merged**
