### PR TITLE
Remove cibuild.* and fix bash shebang

### PR DESCRIPTION
**Pull request by kasper3**

### CODE REVIEW

**Comment by kasper3** [comment]
@dotnet-bot test ci please

**Comment by kasper3** [comment]
@rainersigwald, can you please ask @dotnet-bot to test CI. I changed netci.groovy to call build.cmd/build.sh scripts, and now cibuild.cmd/sh are not required.

**Comment by AndyGerlicher** [comment]
Agreed with what Rainer said. Things could be clarified, but the cibuild is designed to specify arguments to the main build script and isn't redundant.

**Comment by kasper3** [comment]
I understand the sentiment. However, in this case it is literally 12 out of 13 redundant lines of code and the only line that is different has two extra arguments. This patch was a try to consolidate the implementations, so to dogfood the script in CI. Maintaining two scripts vs. one, mitigating the chances of non-ci one getting staled. With that being said, I respectfully disagree.

**Pull request closed without merging**
