### PR TITLE
Fixed a typo in TaskItemComparer

### PR DESCRIPTION
**Pull request by LordJZ**
(Courtesy of Viva64 and their PVS-Studio static analyzer. http://habrahabr.ru/company/pvs-studio/blog/268001/ )

### CODE REVIEW

**Comment by rainersigwald** [comment]
Looks like this is #81.  Can you add that to your commit description?

Related: #186, which has an identical fix but an unclear commit message.  I can live without the unit test I asked for over there; clearly we should fix this.

**Comment by LordJZ** [comment]
Cannot build and add tests because of #224, sorry. Amended the commit message.

**Comment by AndyGerlicher** [comment]
Thanks for updating. Looks good to me as well, this really needs to be fixed.

**Comment by rainersigwald** [comment]
LGTM.  And hopefully we've figured out #224--it looks like you need to add the VS feature that includes the Windows SDK to get our NuGet stuff to work.

**Pull request merged**
