### PR TITLE
Skip osx failing tests

### PR DESCRIPTION
**Pull request by JunielKatarn**
./cibuild.sh --scope Test now runs successfully on Mac OS X.

### CODE REVIEW

**Comment by radical** [comment]
It might be better to use a separate category for failing tests, like `netcore-osx-failing` and keep `nonosxtests` for tests that are not meant to be run on OSX.

**Comment by JunielKatarn** [comment]
@radical This is meant to be a transitory change. The idea is to get tests passing on OS X. Then, progressively fix failing ones (and remove the annotation).

Also, I'm new to the code base and don't know if creating a new trait that does exactly the same as `nonosxtests` would be simple enough or justified for such temporary measure.

**Comment by radical** [comment]
@JunielKatarn Sure, but IIUC, `nonosxtests` is for tests that are not meant to be run on OSX at all.
What you are trying to do is get to `0 tests failing` state so that any regressions after that, can hopefully be caught by the tests. And then slowly fix up those failing tests. For that, being able to see the remaining *failing*/broken tests as separate from just tests that should not be run on OSX, would be useful.

As for adding a new category, it is just a string and you can specify that on the xunit command line to get it to skip the tests. Like: https://github.com/radical/msbuild/commit/933fd56b8e46007bcf8a36a99156107e2c6d16b8

This is just a suggestion. I am not the one who will be approving the PR :)

**Comment by AndyGerlicher** [comment]
I agree with @radical, keep `nonosxtests` for tests that shouldn't pass / execute on OSX. Since this is just blind skipping to get to zero (which is good) it's better not to confuse those with the tests we don't necessarily want to fix.

Also please link to an issue to fix all `netcore-osx-failing` (or whatever tag for the tests to ignore for now) tests.

Thanks!

**Comment by cdmihai** [comment]
I initially pointed @JunielKatarn to using `nonosxtests`, naively thinking that they should all be passing :)
But I agree with @AndyGerlicher and @radical, the tests that must not run on osx should be marked separately from the tests that must pass on OSX but currently don't.

**Comment by cdmihai** [comment]
@JunielKatarn 

Also update the CI script to run tests on osx: https://github.com/Microsoft/msbuild/blob/xplat/netci.groovy#L38

**Comment by JunielKatarn** [comment]
Took suggestions from @AndyGerlicher and @radical. PR updated.

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by AndyGerlicher** [comment]
@dotnet-bot test this please

**Comment by radical** [comment]
@JunielKatarn Could you please look at the test failures?

**Comment by radical** [comment]
Also, it would be better to rebase your changes on top of the current `xplat` branch, with one or two clean commits. That would make it easier to review and give a clean history.

**Comment by radical** [comment]
The tests seem to be broken because of a different issue ( https://github.com/Microsoft/msbuild/issues/491 ).

**Comment by JunielKatarn** [comment]
CR updated based on provided feedback.
I see that automated checks fail constantly on Ubuntu and Windows_NT, but I don't believe those would be related to this change.

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
LGTM, thanks! The change to the Groovy script should take effect once this is merged if I understand correctly.

**Comment by AndyGerlicher** [comment]
LGTM as well, thanks!

**Pull request merged**
