### PR TITLE
Fix typo 'defintion'

### LINKED ISSUE #2785: Fix typo: defintion -> definition
Search the codebase for `defintion`

### PR DESCRIPTION
**Pull request by kkm000**
/cc @KirillOsenkov 
Closes #2785

### CODE REVIEW

**Comment by kkm000** [comment]
The CLA signing page is borked. I emailed their support, waiting on them, sorry.

**Comment by KirillOsenkov** [comment]
Thanks!

You probably need to rebuild full and make sure you include the generated API files in the PR:
https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/innerloop_Windows_NT_CoreCLR_prtest/642/consoleFull#1021753831a88e09de-24a0-4d30-bde4-a7b05a112182

```[ERROR] After building, there are changed files.  Please build locally (cibuild.cmd --target All) and include these changes in your pull request. ```

**Comment by kkm000** [comment]
@KirillOsenkov Thanks, did not know that!

Besides changing the ref library for netstandard1.3, the rebuild [rearranged lines only in build/NuGetPackages/Microsoft.Build.Framework.nuspec](https://github.com/Microsoft/msbuild/pull/2793/files#diff-3f1cd7c24d9510f3fb32908192d57260). Is this normal? Or should I better revert this one file?

**Comment by kkm000** [comment]
Hmm. looks like it is failing now because these lines reversed! So I have to revert it apparently. Is there some dependency on the host in the build scripts that orders the lines differently on different machines?

**Comment by kkm000** [comment]
Looks like I overwrote the diff I pointed to before with push -u. What happened after I rebuilt locally was lines rearranged in this single nuspec file:
```diff
--- a/build/NuGetPackages/Microsoft.Build.Framework.nuspec
+++ b/build/NuGetPackages/Microsoft.Build.Framework.nuspec
@@ -17,12 +17,12 @@
       <group targetFramework=".NETStandard1.3">
         <dependency id="System.Threading.Tasks.Parallel" version="4.0.1" />
         <dependency id="System.Runtime.Extensions" version="4.1.0" />
+        <dependency id="System.Resources.ResourceManager" version="4.0.1" />
         <dependency id="System.Collections" version="4.0.11" />
         <dependency id="System.Diagnostics.Debug" version="4.0.11" />
         <dependency id="System.Globalization" version="4.0.11" />
         <dependency id="System.Linq" version="4.1.0" />
         <dependency id="System.ObjectModel" version="4.0.12" />
-        <dependency id="System.Resources.ResourceManager" version="4.0.1" />
         <dependency id="System.Runtime" version="4.1.0" />
         <dependency id="System.Runtime.InteropServices" version="4.1.0" />
         <dependency id="System.Threading" version="4.0.11" />
```
This change caused the tests to fail, because of changed file with an exactly reverse diff. So something on my machine is different from the build workers--and from mostly everyone who builds locally too, maybe. A fairly minor issue, but eliminating this dependency from the build would improve the stability, I believe.

**Comment by KirillOsenkov** [comment]
@AndyGerlicher hmm, are those files generated? the list should be sorted if we control the code that generates it.

**Comment by kkm000** [comment]
A bit of a clue, if my naive attempt helps. I started the build in one window as `cibuild.cmd --target CoreCLR --scope Build` and cycled `git status` in another. The nuspec changed together with this message in the building console window:
```
  Microsoft.Build.Framework -> C:\Users\kkm\work\msbuild\bin\Debug-NetCore\AnyCPU\Windows_NT\Output\Microsoft.Build.Framework.dll
```
almost exactly the moment it was printed. Just repeated couple times. Looks it happens somewhere near the very end of its build.

**Comment by KirillOsenkov** [comment]
@AndyGerlicher what about the non-determinism of the generated nuspec? I've seen it as a real issue in other PRs as well. Should we file a separate issue to track that down?

**Comment by AndyGerlicher** [comment]
@KirillOsenkov It goes away when we move to SDK projects. So not going to fix until then :)

**Pull request merged**
