### PR TITLE
Enable Mono CI builds

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
FYI, this will start off with red mono builds, as there are a few tests remaining to be fixed. But I will fix those subsequently.

**Comment by cdmihai** [comment]
Let's get this in when all tests are passing locally. Can you please link this PR to the other PRs that need to go in to have a green build?

**Comment by radical** [comment]
PR #1462  is now the only PR required to get a green build for Mono/OSX.

**Comment by radical** [comment]
With the merge of PR #1462, this is now ready for review+merge!

**Pull request merged**
