### PR TITLE
Fix GetLastWriteFileUtcTime function for a directories

### PR DESCRIPTION
**Pull request by mfilippov**
If some additional item in GenerateResource Task will be a director ResourceCreateFile in GetLastWriteFileUtcTime return invalid handle and then resource item would be marked as dirty. I add FILE_FLAG_BACKUP_SEMANTICS file flag for avoiding it problem.

### CODE REVIEW

**Comment by rainersigwald** [comment]
What causes a directory to be passed in there? I didn't quite catch that.

Code change looks good, just want to make sure I understand the scenario.

**Comment by mfilippov** [comment]
We have an error in custom generated targets. We use MSBuildThisFileDirectory instead of MSBuildThisFile in MSBuildAllProjects property. But it is a bug was undiscoverable :) I think my patch also fixed different behaviour on Unix and Windows.

**Comment by AndyGerlicher** [comment]
Thanks for the contribution! This looks good in general, however given that it's pretty subtle and `GetLastWriteFileUtcTime` is called in many places, I would like to see a unit test added that covers the scenario that was broken previously. That seem doable? Then I'm good taking the change. Thanks!

**Comment by mfilippov** [comment]
@AndyGerlicher Ok, I try to do it.

**Comment by mfilippov** [comment]
@AndyGerlicher I'm not sure about this PR because I found GetLastWriteDirectoryUtcTime method special for directories. May be better way it is patch GenerateResource task?

**Comment by AndyGerlicher** [comment]
That sounds reasonable to me (patching GenerateResource task). Less impact since this method is used in so many places.

**Comment by AndyGerlicher** [comment]
@mfilippov did you look into another approach? As is with the test I don't object to taking this change. If you still think patching GenerateResource would be a better approach please close this PR. Thanks!

**Comment by mfilippov** [comment]
Ok, I not have time for that yet.

**Pull request closed without merging**
