### PR TITLE
Update SCI and SRM to the latest

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
test Windows_NT Build for Full please

**Comment by AndyGerlicher** [comment]
Updated title, this shouldn't go in yet (targeted for Preview 4)

**Comment by tmat** [comment]
test Ubuntu16.04 Build for CoreCLR please

**Comment by tmat** [comment]
test OSX10.13 Build for CoreCLR please

**Comment by tmat** [comment]
test OSX10.13 Build for CoreCLR please

**Comment by tmat** [comment]
test Ubuntu16.04 Build for CoreCLR please

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for CoreCLR please

**Pull request merged**
