### PR TITLE
Disable windowsonly tests when running on !Windows platforms

### PR DESCRIPTION
**Pull request by radical**
These changes were in the code earlier, but seem to have been lost
in the nunit->xunit migration. But they are still relevant, so, adding them
again.

### CODE REVIEW

**Comment by radical** [comment]
Updated the PR to fix an issue (use -notrait .. instead of -exclude) with my earlier patch.

**Comment by radical** [comment]
Changed the category `WindowsOnly` to `windowsonly` to be consistent with other categories.

**Comment by cdmihai** [comment]
Can you please use the [PlatformSpecific] attribute? (example: https://github.com/Microsoft/msbuild/blob/xplat/src/Shared/UnitTests/FileUtilities_Tests.cs#L855)

It's an xunit extension msbuild inherits from the buildtools package: https://github.com/dotnet/buildtools/blob/f6361d1f2d53a64ae6c0971be959981390f9d8a2/src/xunit.netcore.extensions/Discoverers/PlatformSpecificDiscoverer.cs#L23

**Comment by radical** [comment]
@cdmihai ah, my bad. Fixed.

**Comment by rainersigwald** [comment]
LGTM, thanks.

**Pull request merged**
