### PR TITLE
Fix shell injection issues in build.pl

### PR DESCRIPTION
**Pull request by drbo**
`build.pl` is vulnerable to shell command injection if there are metacharacters in various paths.  This patch fixes these issues.  It also does some cleanup of the Perl code.

### CODE REVIEW

**Comment by rainersigwald** [comment]
These changes look good to me, but @cdmihai has been doing more work with building on *nix lately.

**Comment by cdmihai** [comment]
After some reading up on Perl tutorials, LGTM :)

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
Thank you, @drbo!

**Pull request merged**
