### PR TITLE
Port: Fix build XamlBuildTask failure on 64-bit MSBuild (#2001) (#2020)

### PR DESCRIPTION
**Pull request by AndyGerlicher**
Port #2020 to `vs15.3-preview` branch.

### CODE REVIEW

**Comment by remusrg** [comment]
Is this available in 15.3 preview now, or even better 15.2?

**Comment by rainersigwald** [comment]
@remusrg It should be in 15.3, based on the tags listed [on the commit details page](https://github.com/Microsoft/msbuild/commit/3c9ab94ef60a538da7c12a4b3fda28d3325e12c4).

**Comment by remusrg** [comment]
Any idea when 15.3 comes out of preview?

**Comment by rainersigwald** [comment]
Not that I can share in public, sorry 😇 

Yes, for this issue you should be able to just patch those files.

**Pull request merged**
