### PR TITLE
Apply NGen Optimizations only for Full Framework binaries.

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Comment by livarcocc** [comment]
@tmat to speak on if this should be done in arcade directly. I wonder if this is happening to Roslyn as well, for instance.

**Comment by livarcocc** [comment]
@rainersigwald I will amend the commit to say why, but it is basically because having IBC data on the .NET Core binaries causes crossgen it, but for core, the training we did in VS is not right and causes a perf regression for the CLI scenarios.

**Comment by rainersigwald** [comment]
That's sufficient info, just want it there for future-us who's spelunking through history trying to figure out why optprof data is weird.

**Comment by tmat** [comment]
LGTM. 

> Should this be done at the Arcade level? Is it always wrong to apply optprof information to .NET Core assemblies, or is that a quirk of our optprof collection?

Good question. I believe CoreFX embeds IBC data to .NET Core assemblies, but they are using `full`. 
It just occurred to me that this condition is gonna be problematic for projects that target netstandard (like Roslyn), rather than multi-targeting. Seems like cross-gen infra should be able to deal with the assembly already having IBC data (e.g. have option to override them).

@brianrob

**Comment by livarcocc** [comment]
@rainersigwald @tmat I have fixed the commit message and also validated that the IBC data embedded in the generated assemblies is only present for full framework assemblies. So, this PR is good to go.

**Comment by tmat** [comment]
@livarcocc I think there is still an issue in crossgen that needs to be addressed. This seems like a workaround that won't work for netstandard libraries.

**Pull request merged**
