### PR TITLE
Update to .NET Core RC1 packages

### PR DESCRIPTION
**Pull request by dsplaisted**
The .NET Core RC1 packages are versioned `-beta-23516` and are available on NuGet.org.

### CODE REVIEW

**Comment by rainersigwald** [comment]
IIRC @cdmihai ran into some problems on OS X when doing this (?) update.

**Comment by cdmihai** [comment]
Bumping System.IO.* beyond -beta-23406 brings in a corefx bug (https://github.com/dotnet/corefx/issues/4274) that fails one of our tests.

However, the CI appears to fail before running tests.

**Comment by dsplaisted** [comment]
I had to explicitly add System.Linq.Expressions to runtime.project.json to avoid errors like the following:

    System.Linq.Expressions 4.0.11-beta-23516 provides a compile-time reference assembly for System.Linq.Expressions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86

@ericstj You previously helped me with a similar issue with NuGet where indirect references to packages with runtime-specific components didn't work.  Is this tracked as an issue for NuGet somewhere?

**Comment by rainersigwald** [comment]
LGTM

**Pull request merged**
