### PR TITLE
Ubuntu CI images with Mono 5.0.1

### PR DESCRIPTION
**Pull request by rainersigwald**

### CODE REVIEW

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

**Comment by karajas** [comment]
@dotnet-bot test ci please

**Comment by cdmihai** [comment]
I think this diff is needed to ignore the Windows - Mono combination: https://github.com/Microsoft/msbuild/pull/2347/commits/0907d07e5a768ce9e4fd43842cd34f266ddad275#diff-2d212ad84506951c8f928e21aed24580R24

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
Existing CoreCLR jobs are passing on the new image 👍 

I'm going to rework commits so this just moves us to the new images (and image specification approach) and separate out the actual "turn on Mono" stuff.

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
@dotnet-bot test OSX Build for CoreCLR please

**Pull request merged**
