### PR TITLE
Fix build under directory with spaces in the path

### PR DESCRIPTION
**Pull request by shalupov**

### CODE REVIEW

**Comment by rainersigwald** [comment]
LGTM

**Comment by jasonwilliams200OK** [comment]
Probably worth having consistent un-escaped quotes there are in dir.targets, dir.props and src/dir.targets.

**Comment by AndyGerlicher** [comment]
@dotnet-bot test this please

**Comment by shalupov** [comment]
I've fixed nuget restore too and rebased on latest xplat

**Pull request merged**
