### PR TITLE
Fixing the MachineIndependent solution configuration to use the project configuration of the same name.

### PR DESCRIPTION
**Pull request by mfilippov**

### CODE REVIEW

**Comment by rainersigwald** [comment]
@livarcocc I think we should pull this in after #3993 lands (no need to do this first then deal with churn there; that's big enough).

**Comment by livarcocc** [comment]
Is there a TLDR for this? I don't know what this refers to.

**Comment by mfilippov** [comment]
@AndyGerlicher @rainersigwald Are you ready to apply this PR? I could solve the conflict if yes.

**Comment by rainersigwald** [comment]
No objection here. @livarcocc?

**Comment by livarcocc** [comment]
None from me. @mfilippov would it be too much to ask you to resolve the merge conflicts? 👼

**Comment by mfilippov** [comment]
@livarcocc Sure

**Comment by radical** [comment]
I'm not sure I understand this. Why is this replacing `Release-MONO`?

**Comment by mfilippov** [comment]
@rainersigwald I think it not connected with Mono. We use separate conditions.

**Comment by rainersigwald** [comment]
@mfilippov Should the .sln changes then be to add configurations, rather than replacing the `Release-MONO` configuration?

**Comment by mfilippov** [comment]
@rainersigwald Oh, sorry it's my mistake. I should add new instead to replace Release-MONO.

**Comment by radical** [comment]
- it would be useful to include Andy's comment 
`Machine independent turns off features that you wouldn't want to use to be "machine independent". Like registry, GAC, etc. which could differ from machine to machine` in the commit message. 
- An explanation about why this was removed and why this is being restored now
- And how or what scenarios is this intended to be used

IMHO, the above should be included in the commit message.

**Comment by radical** [comment]
And the fact that this is being re-enabled for `MSBuildTaskHost`, besides restoring the configuration.

**Comment by mfilippov** [comment]
@radical I update commit message but I wrote similar text when I added this configuration in 594bee421cc25196aca00cd6c5bc9c01e245cbc0.
@rainersigwald MachineIndependent configuration doesn't use Release-MONO. I just restore behaviour changed by @jeffkl in 28511da98e358bde6338347d8c3d2c1d4a76904c

**Comment by radical** [comment]
@mfilippov Thanks for updating the commit message. I think it would be useful to reference the two commits you mentioned in the commit too, to give it proper context.
Also, this shouldn't be removing `Release-MONO`, so, you will need to add `MachineIndependent` config rather than replace.

**Comment by mfilippov** [comment]
@rainersigwald I don't remove ```Release-MONO``` I just replace configuration name in MachineIndependent solution configuration. ```Release-MONO``` still there and just use Release configuration (an example line 74).

**Comment by mfilippov** [comment]
@rainersigwald No problem, I little mess too :)

**Comment by radical** [comment]
@mfilippov ah, you are correct. So, what this PR is really doing is:

1. Fixing the MachineIndependent solution configuration to use the project configuration of the same name.
2. (maybe better as a separate commit?) *re-enable* MachineIndependent configuration for `MSBuildTaskHost` project.

IMHO, the commit *and* PR messages should be fixed.

**Comment by mfilippov** [comment]
@radical done

**Comment by rainersigwald** [comment]
Thanks!

**Pull request merged**
