### PR TITLE
Remove the disable intrinsic MSBuild tasks escape hatch

### PR DESCRIPTION
**Pull request by davkean**
This took 0.2% of CPU, and 0.1% of allocations in a .NET Standard/.NET Framework mixed project.

### CODE REVIEW

**Comment by davkean** [comment]
I have no idea why this variable exists - I cannot see a usage anywhere internally.

**Comment by davkean** [comment]
tag @pilchie

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Windows_NT Build for CoreCLR please

**Comment by AndyGerlicher** [comment]
Updated this to use our `Traits` class.

**Comment by jeffkl** [comment]
@AndyGerlicher can we just get rid of this escape hatch?  Would anyone ever want to disable the MSBuild or CallTarget task?  The whole entire internet hasn't heard of this one:

https://www.google.com/search?q=MSBUILDDISABLEINTRINSICMSBUILDTASK

**Comment by AndyGerlicher** [comment]
Sounds good let's just get rid of it.

**Pull request merged**
