### PR TITLE
Update to  RepoToolset 1.0.0-beta2-63103-01

### PR DESCRIPTION
**Pull request by rainersigwald**
Progress toward https://github.com/dotnet/arcade/issues/724.

Close to working; needs a couple of tweaks to the release that does ingestions to keep it working for 15.9 and 16.0 builds, but this can go in before that--it'll just require minor manual intervention when we want to insert.

### CODE REVIEW

**Comment by livarcocc** [comment]
NuGet made a breaking change were licenseUrl has been deprecated. We are working to have this fixed in arcade directly. For now, I would just add a NOWARN for that NuGet warning to unblock the PR.

**Comment by rainersigwald** [comment]
That's a good idea, but it is unfortunately not the major problem with this PR at the moment; the update somehow horks task loading, leading to errors like

```
   24:6>/home/vsts/work/1/s/artifacts/.dotnet/2.1.500/sdk/2.1.500/Roslyn/Microsoft.Managed.Core.targets(90,5): error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.MapSourceRoots" task could not be loaded from the assembly /home/vsts/work/1/s/artifacts/.dotnet/2.1.500/sdk/2.1.500/Roslyn/Microsoft.Build.Tasks.CodeAnalysis.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/home/vsts/work/1/s/src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj]
```

when built from .NET Core MSBuild.

**Comment by livarcocc** [comment]
I had similar issues with this in the CLI. There is a property that you can set to tell arcade to use the roslyn assemblies from sdk or to use assemblies from the package. Here is the property: `<UsingToolMicrosoftNetCompilers>false</UsingToolMicrosoftNetCompilers>`.

**Comment by livarcocc** [comment]
Closing this one in favor of https://github.com/Microsoft/msbuild/pull/3993.

**Pull request closed without merging**
