### PR TITLE
Fallback properties are case insensitive

### LINKED ISSUE #2023: Redirecting MsBuildExtensionsPath causes incorrect double-load warnings
We have an isolation system in place that doesn't depend on MsBuild installation.  As such, we alter $(MsBuildExtensionsPath) early in our project load order.  This has worked fine since MsBuild 4 and earlier, but as of v15 we get load warnings in VisualStudio.  Unclear if this is an MsBuild fault or a VisualStudio fault.

VS gives this warning
`	"D:\CorextCache\.A\MsBuild.Corext.sE2FwIuT0zUvdE9g6wU5UA\Extensions\Plugin\Props\MsBuild.Tasks.Corext.props" cannot be imported again. It was already imported at "D:\CorextCache\.A\MsBuild.Corext.sE2FwIuT0zUvdE9g6wU5UA\Environment.props (36,3)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\code\CorextExe\src\Common\Common.csproj]	Common	D:\CorextCache\.A\MsBuild.Corext.sE2FwIuT0zUvdE9g6wU5UA\Environment.props	36	
`
Where the code loading that task is essentially:
`  <Import Project="$(MsBuildExtensionsPath)\Plugin\Props\*" />`

There is only one file in the Props folder, and if I remove the wildcard and import only that file it works fine.  More interesting is that changing the property used to root it to something else, or using a hardcoded path at the beginning lets it work fine with wildcards.  For instance

`  <Import Project="$(AnyOtherProperty)\Extensions\Plugin\Props\*" />`

It seems there is special logic around the variable MsBuildExtensionsPath causing msbuild/VS to get confused over wildcard imports such that it thinks it has to import twice from this specific line.

### PR DESCRIPTION
**Pull request by cdmihai**
Closes #2023

### CODE REVIEW

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by cdmihai** [comment]
@dotnet-bot test ci please

**Comment by cdmihai** [comment]
@mmitche Do you know why CI isn't triggering for this branch (PR branch is from the same repo)?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@cdmihai Not sure at the moment.  Investigating.  It appears to be hung up while talking to github

**Comment by mmitche** [comment]
@cdmihai It's github rate limiting us.  It should resolve itself in a bit.

**Comment by cdmihai** [comment]
Perf results below.

CPU tends to be the same, but memory is regressed a bit. Evaluating all Roslyn projects allocates 2.5 mb more (579.5mb vs 582mb).


Timestamp | MsbuildIdentifier | TestProjectPath | Repetitions | Projects | Imports | ItemDefinitions | ItemTypes | Items | ItemsWithGlobs | Properties | Targets | EvaluationTime_Average (ms) | EvaluationTime_Median (ms) | EvaluationTime_StdDev (ms) | EvaluationTotalBytes_Average | EvaluationTotalBytes_Median | EvaluationTotalBytes_StdDev
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2017-09-11T09:52:15 | master | DotnetConsoleProject | 300 | 1 | 31 | 5 | 25 | 77 | 1 | 493 | 257 | 83.3472 | 85.7655 | 6.1369 | 4718651 | 4715448 | 23067
2017-09-11T09:56:41 | caseInsensitiveSearchPaths | DotnetConsoleProject | 300 | 1 | 31 | 5 | 25 | 77 | 1 | 493 | 257 | 82.1337 | 84.353 | 6.308 | 4732410 | 4731280 | 23022
2017-09-11T10:00:14 | master | DotnetWebProject | 300 | 1 | 47 | 6 | 27 | 86 | 1 | 538 | 283 | 119.2376 | 123.4736 | 11.9193 | 6177195 | 6173344 | 23236
2017-09-11T10:05:25 | caseInsensitiveSearchPaths | DotnetWebProject | 300 | 1 | 47 | 6 | 27 | 86 | 1 | 538 | 283 | 118.7622 | 123.1813 | 11.8285 | 6194013 | 6193680 | 22792
2017-09-11T10:11:09 | master | DotnetMvcProject | 300 | 1 | 47 | 6 | 30 | 195 | 5 | 538 | 283 | 220.7661 | 221.7926 | 12.7886 | 8459805 | 8457966 | 22961
2017-09-11T10:17:17 | caseInsensitiveSearchPaths | DotnetMvcProject | 300 | 1 | 47 | 6 | 30 | 195 | 5 | 538 | 283 | 208.8716 | 214.2272 | 25.023 | 8473845 | 8472252 | 23207
2017-09-11T10:28:08 | master | Picasso | 100 | 28 | 532 | 28 | 646 | 5088 | 0 | 12578 | 5740 | 659.2994 | 662.1414 | 16.5082 | 32228350 | 32223996 | 19106
2017-09-11T10:39:45 | caseInsensitiveSearchPaths | Picasso | 100 | 28 | 532 | 28 | 646 | 5088 | 0 | 12578 | 5740 | 649.3094 | 650.5244 | 19.775 | 32686566 | 32682598 | 18954
2017-09-11T10:46:39 | master | SmallP2POldCsproj | 300 | 4 | 80 | 4 | 88 | 260 | 0 | 1625 | 844 | 107.8403 | 109.1843 | 3.7827 | 5171388 | 5170288 | 11126
2017-09-11T10:53:47 | caseInsensitiveSearchPaths | SmallP2POldCsproj | 300 | 4 | 80 | 4 | 88 | 260 | 0 | 1625 | 844 | 107.8263 | 109.1728 | 4.5323 | 5237214 | 5236116 | 11451
2017-09-11T10:58:23 | master | Generated_100_100_v150 | 25 | 100 | 4700 | 2000 | 2900 | 29900 | 0 | 67600 | 36900 | 2033.1336 | 1923.9256 | 335.7936 | 175948194 | 175947680 | 17478
2017-09-11T11:02:43 | caseInsensitiveSearchPaths | Generated_100_100_v150 | 25 | 100 | 4700 | 2000 | 2900 | 29900 | 0 | 67600 | 36900 | 1928.4411 | 1903.1166 | 250.832 | 177028273 | 177026956 | 16898
2017-09-11T11:11:56 | master | LargeP2POldCsproj | 50 | 100 | 2000 | 100 | 2192 | 7105 | 0 | 40500 | 21100 | 1884.5879 | 1886.2869 | 24.9341 | 68200924 | 68201296 | 14620
2017-09-11T11:21:09 | caseInsensitiveSearchPaths | LargeP2POldCsproj | 50 | 100 | 2000 | 100 | 2192 | 7105 | 0 | 40500 | 21100 | 1894.8706 | 1903.021 | 41.1152 | 69898690 | 69896848 | 13982
2017-09-11T11:25:13 | master | roslyn | 10 | 148 | 7441 | 2160 | 4959 | 25358 | 161 | 120243 | 45390 | 12223.3308 | 12384.7154 | 781.4277 | 579595823 | 579596700 | 6432
2017-09-11T11:29:25 | caseInsensitiveSearchPaths | roslyn | 10 | 148 | 7441 | 2160 | 4959 | 25358 | 161 | 120243 | 45390 | 12485.4876 | 12467.3085 | 700.9226 | 582031035 | 582027988 | 9258

**Comment by AndyGerlicher** [comment]
Method | Mean | StdDev | Gen 0 | Allocated
-- | -- | -- | -- | --
StringReplaceCaseSensitive | 182.5850 ns | 0.2200 ns | 0.0229 | 184 B
StringReplaceCaseInsensitive | 564.3480 ns | 2.3276 ns | 0.0754 | 616 B

Bit slower for sure. Probably ok for this use? Shouldn't be a super hot path.

**Comment by AndyGerlicher** [comment]
With the optimization:
Method | Mean | StdDev | Gen 0 | Allocated
-- | -- | -- | -- | --
StringReplaceCaseSensitive | 184.9525 ns | 0.9262 ns | 0.0232 | 184 B
StringReplaceCaseInsensitive | 532.6140 ns | 3.1963 ns | 0.0406 | 408 B

**Pull request merged**
