### PR TITLE
🔀 15.8 to 15.9

### PR DESCRIPTION
**Pull request by rainersigwald**

### CODE REVIEW

**Comment by red0bear** [comment]
How to make this ?

**Comment by rainersigwald** [comment]
@red0bear What do you mean?

**Comment by red0bear** [comment]
I need compile this ? :-)

**Comment by rainersigwald** [comment]
@red0bear This PR, specifically, or the repo in general? You can build this PR with `build.cmd` after you [check it out](https://help.github.com/articles/checking-out-pull-requests-locally/).

**Comment by red0bear** [comment]
Do you need build with this check out ? I can try here.

**Comment by red0bear** [comment]
FALHA da compilação.

XUnit : warning : /run/media/felipe/FFCOSTA/PROGRAMAS/msbuild/build/../artifacts/2/Debug/TestResults/Microsoft.Build.Utilities.UnitTests_netcoreapp2.0_x64.log [netcoreapp2.0|x64] [/run/media/felipe/FFCOSTA/PROGRAMAS/msbuild/src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj]
XUnit : warning : /run/media/felipe/FFCOSTA/PROGRAMAS/msbuild/build/../artifacts/2/Debug/TestResults/Microsoft.Build.Utilities.UnitTests_netcoreapp2.1_x64.log [netcoreapp2.1|x64] [/run/media/felipe/FFCOSTA/PROGRAMAS/msbuild/src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj]
XUnit : error : Tests failed on platforms: netcoreapp2.0|x64, netcoreapp2.1|x64 [/run/media/felipe/FFCOSTA/PROGRAMAS/msbuild/src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj]
    2 Aviso(s)
    1 Erro(s)

Tempo Decorrido 00:04:41.90

**Comment by rainersigwald** [comment]
@red0bear No, the CI system is sufficient; I don't think I need extra coverage on this for my own sake. If you're just trying to build MSBuild, I'd use either the vs15.9 branch or master, and not worry about this PR.

Isn't that test failure the same one you were getting in #3580?

**Comment by red0bear** [comment]
Im just curious if it compile do you have a sample to test ?  i think i put your checkout. 15.9 . 

git branch
  master
* vs15.9

**Comment by rainersigwald** [comment]
Ok, let's move that conversation back to  #3580, since this PR is just keeping some branches up to date.

**Comment by rainersigwald** [comment]
@dotnet-bot test OSX10.13 Build for CoreCLR please
@dotnet-bot test Ubuntu16.04 Build for CoreCLR please

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Pull request merged**
