### PR TITLE
Use images containing mono 4.6.2.16

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@jeffkl This is what the 14.04 one spit out....looks correct?

https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/GenPRTest/job/innerloop_xplat_Ubuntu14.04_Mono/1/console

**Comment by jeffkl** [comment]
Its close, the build succeeded but the tests didn't run because mono wasn't found, maybe @radical knows why?  I'm not sure if mono has to be on the PATH or something?

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
I'll verify that the install is correct.  I would prefer not to put mono on the path (you can set it up as desired in the CI script) simply to avoid accidental cases where incorrect assemblies might be loaded.

**Comment by jeffkl** [comment]
Well looking at the output now it says that `csc.exe` failed.  @radical The second `csc.exe` used in our build comes from a Roslyn package and fails.  Any ideas?

https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/GenPRTest/job/innerloop_xplat_Ubuntu14.04_Mono/1/console

**Comment by mmitche** [comment]
Appears mono itself is on the path

dotnet-bot@ubuntu1404-20170109-37cdf0:~$ mono --version
Mono JIT compiler version 4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan  3 11:48:26 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by rainersigwald** [comment]
@jeffkl I'm pretty sure that error is coming up because the Roslyn compiler server doesn't work on Mono. I experimented a bit with setting `/p:UseSharedCompilation=false` but I don't think it worked: https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/_OSX_Mono_prtest/46/

**Comment by jeffkl** [comment]
It only passed `UseSharedCompiliation` to the first build (which was already succeeding) but I don't see it passing that property to the second build...

**Comment by AndyGerlicher** [comment]
Closing old PR. Now that we've stabilized for RTM we'd like to get the mono build up and running, but not sure if this PR is still relevant or not. Please reopen if it is.

**Pull request closed without merging**
