### PR TITLE
Remove unused Perl script

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
* Wiki suggests to use `msbuild/cibuild.sh`.
  https://github.com/Microsoft/msbuild/wiki/Building-on-OS-X-and-Linux

* CI is also using `cibuild.sh`.

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
@cdmihai, @mmitche, the Ubuntu job is failing. Is it a known issue?

Also, on OS X, although the test passed, I noticed few weird messages:

```sh
find: ftsopen: No such file or directory
```

and

```
Unsupported target detected: . Configuring as if for CoreCLR
Unsupported host detected: . Configuring as if for Mono
```

Is this message about Mono correct?

**Comment by rainersigwald** [comment]
Deletion LGTM. Pretty sure the Ubuntu CI failure is ok, but @cdmihai has the most up-to-date understanding of those.

**Comment by mmitche** [comment]
I'm not aware of any mono issues.

**Comment by jasonwilliams200OK** [comment]
Actually msbuild xplat didn't used mono at all (as I don't have it installed locally but built on OS X). It is using dotnet CLI, but the message says otherwise. :smile:

**Comment by jasonwilliams200OK** [comment]
Sorry I just figured I had mono installed in my OS X box. So we do have mono dependency even with dotnet cli downloaded during the script run.. :(

**Comment by AndyGerlicher** [comment]
LGTM

**Comment by cdmihai** [comment]
@jasonwilliams200OK 

If you want to do a .net core selfhost without using mono, try `./cibuild.sh --host CoreCLR`. Calling `cibuild.sh` with no args defaults to using a mono hosted msbuild to build for net core. Once https://github.com/dotnet/buildtools/pull/499 is accepted, I'll update cibuild to default to .net core. We need that PR to go into build tools because it fixes an issue which fails the tests on OSX (#504).

Ubuntu is known to be failing when hosted on mono. If you build it with --host CoreCLR it actually succeeds. However, even though it succeeds to compile and copy runtime dependencies, it has some failing tests (which due to lack of time we have not yet had the chance to investigate, but we do appreciate outside contributions :) ).

Error messages:
```
Unsupported target detected: . Configuring as if for CoreCLR
Unsupported host detected: . Configuring as if for Mono
```
This is outputed by cibuild when you do not provide values for --target and --host (`./cibuild -h` for more details). I agree that the messages should sound less like an error and more like a friendly reminder :)

```
find: ftsopen: No such file or directory
```
I do not know why this is getting printed, or who prints it. Needs investigation.

**Comment by jasonwilliams200OK** [comment]
Thanks for the detailed response. 

> I'll update cibuild to default to using Core CLR as host. We need that PR to go into build tools because it fixes an issue which fails the tests on OSX (#504).

Unsure if it is normal, but it makes me very excited to know that we are going to get mono-independent build process in place! I really want to try building msbuild in a Ubuntu VM / docker, where mono is unavailable. :)

> I do not know why this is getting printed, or who prints it. Needs investigation.

Investigated and fixed by https://github.com/Microsoft/msbuild/pull/513 . :smile:  :tada:

**Comment by jasonwilliams200OK** [comment]
@cdmihai, should this be merged then? :smiley_cat: 
I will try to make a separate PR for Ubuntu. :rocket:

**Pull request merged**
