### PR TITLE
Enable tests for the GenerateResource task

### PR DESCRIPTION
**Pull request by cdmihai**

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
LGTM. I'll assume that this change didn't fail 2327 tests.

**Comment by cdmihai** [comment]
I built from scratch and all tests still pass on my machine. Must be the CI.

Mihai

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

**Comment by rainersigwald** [comment]
Hmm, looks like tests are failing with

```
System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Are we missing something from the runtime package, maybe?  Change that came in through @ValMenn's Linux changes?

**Comment by AndyGerlicher** [comment]
@dotnet-bot test this please

**Pull request merged**
