### PR TITLE
 Fix race adding configuration in BuildManager

### PR DESCRIPTION
**Pull request by AndyGerlicher**
We have crash reports of a race condition in the AddNewConfiguration
method. Adding a lock to the only entry to that method currently without
a lock.

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/548385

### CODE REVIEW

**Comment by rainersigwald** [comment]
I'm very confused by the access/locking rules here. Do we need to guard all write accesses to `_configCache` in `BuildManager`? Several remain unguarded, including the `BuildManager.AddNewConfiguration` that's throwing in the bug, presumably because a configuration was inserted between `GetMatchingConfiguration` and `AddNewConfiguration`. I think this large lock is sufficient, since it's the public entry point I can find for `AddNewConfiguration`, but how will we know if it's too broad?

**Comment by cdmihai** [comment]
@rainersigwald I think the lock is not too broad. There's writes to shared state here and there all the way to the dataflow post method, which should be quick since it's async.

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by AndyGerlicher** [comment]
@dotnet-bot test OSX10.13 Build for CoreCLR please

**Comment by AndyGerlicher** [comment]
@dotnet-bot test OSX10.13 Build for CoreCLR please

**Pull request merged**
